### ISSUE TITLE
ERROR: failed to solve: process "/bin/sh -c 

### ISSUE THREAD

**Issue by yellowbean** [docker/build-push-action#1008]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

Suddenly build failed, but I didn't change anything about the workfile.

with same workflow file , it was a successful build on Build 86 but somehow failed at Build 87 

![Screenshot 2023-11-18 at 11 55 38](https://github.com/docker/build-push-action/assets/1008321/e6c5ca7e-f4c0-443c-9fbe-55c77369135e)

I can build successfully on my local.

### Expected behaviour

The workflow file should be run successfully

### Actual behaviour

it raise error :

    buildx failed with: ERROR: failed to solve: process "/bin/sh -c cd /opt/build && stack build --copy-bins --local-bin-path /opt/build --resolver lts-18.22 # --system-ghc" did not complete successfully: exit code: 1

### Repository URL

https://github.com/yellowbean/Hastructure/

### Workflow run URL

https://github.com/yellowbean/Hastructure/actions/runs/6814113581

### YAML workflow

```yaml
https://github.com/yellowbean/Hastructure/actions/runs/6814113581/workflow
```

**Comment by crazy-max** [comment]
Looking at the logs, I think this is an issue within your project and not the action or Buildx/BuildKit: https://github.com/yellowbean/Hastructure/actions/runs/6814113581/job/18754144029#step:6:6090

```
#12 935.9 Preprocessing executable 'Hastructure-exe' for Hastructure-0.20.2..
#12 935.9 Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.7: can't find source for FormBuilder in
#12 935.9 app,
#12 935.9 .stack-work/dist/x86_64-linux/Cabal-3.2.1.0/build/Hastructure-exe/autogen,
#12 935.9 .stack-work/dist/x86_64-linux/Cabal-3.2.1.0/build/global-autogen
```

Might be related to this change: https://github.com/yellowbean/Hastructure/compare/v0.22.5...v0.22.6#diff-0e14c027a17482b517041329a3ae4e7237fa7e8e6f303c3d6eda2c58aa29cee6R95

**Comment by yellowbean** [comment]
@crazy-max  Thank you very much on pin point to the root issue
