### ISSUE TITLE
outputs.digest not set if push = false

### ISSUE THREAD

**Issue by EajksEajks** [docker/build-push-action#1009]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

I have a GitHub workflow where I chain several docker build/push using the outputs.digest from one docker build/push to the next one. I only push on schedule/tags and it works fine. But on branches, I do not push but it doesn't work because outputs.digest is not set.

### Expected behaviour

outputs.digest set independent of push being true or false

### Actual behaviour

outputs.digest set only on push = true

### Repository URL

https://github.com/by-EAjks-Com/Development-Environments

### Workflow run URL

https://github.com/by-EAjks-Com/Development-Environments/actions/runs/6919392268

### YAML workflow

```yaml
https://github.com/by-EAjks-Com/Development-Environments/blob/main/.github/workflows/build-deploy-cpp-only.yaml
```

**Comment by crazy-max** [comment]
> But on branches, I do not push but it doesn't work because outputs.digest is not set.

This is expected if you don't export the build result (load or push).
