### ISSUE TITLE
context should observe working-directory defined on defaults

### ISSUE THREAD

**Issue by sombriks** [docker/build-push-action#1030]
### Description

currently i have a monorepo/multiprojec setup and a small action for each project.

for most actions, i set a `working-directory` so i can perform every action (npm install, checkout, etc) from that directory.

publish action does not observe this directory, always defaulting to repo root, so i need to set context regardless what i have on my `working-direction`.

see sample [here](https://github.com/sombriks/redline/blob/main/.github/workflows/node.js-service.yml#L56).

**Comment by sombriks** [comment]
what i am saying is there is a default section documented here: https://docs.github.com/en/actions/using-jobs/setting-default-values-for-jobs#example-set-the-default-shell-and-working-directory

and the action does not honor it.

i did exactly what you suggested but this is not what one could expect if there is a default setting for working-directory.

**Comment by crazy-max** [comment]
> see sample [here](https://github.com/sombriks/redline/blob/main/.github/workflows/node.js-service.yml#L56).

Your link returns a 404

**Comment by sombriks** [comment]
Here's a working one: https://github.com/sombriks/redline/blob/3b672a3064dc63a4ff513630e7fe435e9ea84904/.github/workflows/node.js-service.yml#L12 

i set up `working-directory: service-node-koa` as a default and it is observed by `Checkout Code`, `Use Node` and `Run tests` steps with one caveat for npm cache but that's all. they all know the proper working directory by defaults settings.

For `Build and Push` step indeed set context solves the issue, and thinking again about that, the defaults section is specific to run commands. I think it's fine to set it like this in this monorepo/multiproject scenario.

**Comment by crazy-max** [comment]
Looking at the docs, `working-directory` only works for `run:` steps, not for actions: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsworking-directory
