### ISSUE TITLE
v2: pushing to Github Container Registry fails

### ISSUE THREAD

**Issue by cicirello** [docker/build-push-action#105]
When pushing to the Github Container Registry, I get the following error:

```
#24 ERROR: server message: insufficient_scope: authorization failed
------
 > exporting to image:
------
failed to solve: rpc error: code = Unknown desc = server message: insufficient_scope: authorization failed
##[error]The process '/usr/bin/docker' failed with exit code 1
```

The PAT has what I believe is the required  scope: delete:packages, read:packages, repo, write:packages.

If the full workflow is useful, you can find it here: https://github.com/cicirello/alpine-plus-plus/blob/master/.github/workflows/docker-publish.yml

There are two jobs in the workflow, the first pushes to Docker Hub successfully.  The second attempts to push to the Github Container Registry, and fails.  The docker/login-action succeeds in logging in to the GitHub Container Registry.

**Comment by crazy-max** [comment]
@cicirello 

I have pushed to GHCR successfully on [this repo](https://github.com/crazy-max/docker-alpine-s6) with the [following workflow](https://github.com/crazy-max/docker-alpine-s6/blob/28509f295f17a9e2db79912ce8904d08aa3d3d1b/.github/workflows/build.yml).

> The PAT has what I believe is the required scope: delete:packages, read:packages, repo, write:packages.

I would have thought that your scopes were not enough but it looks good to me.

But lookling at the [build command generated by the action](https://github.com/cicirello/alpine-plus-plus/runs/1082215542?check_suite_focus=true#step:7:15), it looks like you forgot to prepend your tags with `ghcr.io/`.

**Comment by cicirello** [comment]
@crazy-max Awesome.  Thanks.  It was definitely due to my missing `ghcr.io/` at start of tags.  It works now.  It might be useful for v2 to have an example workflow for GHCR, as well as an example workflow for pushing to both Docker Hub and GHCR (e.g., your alpine-s6 workflow was helpful in simplifying mine).

**Comment by Burnett2k** [comment]
I just spent an hour or so trying to figure out this problem.. Would be nice if the example for pushing to GHCR in the readme actually included a correct tag or more information about that particularly vague error. It wasn't immediately apparent to me why my push wasn't working until I came across this thread.

**Comment by crazy-max** [comment]
@cicirello @Burnett2k https://github.com/docker/build-push-action#push-to-multi-registries

**Comment by bilelkhalsi** [comment]
Hi,
I am still facing the same error with v2. My [workflow](https://github.com/bilelkhalsi/ioServices/runs/1571018940?check_suite_focus=true) uses a custom PAT.
could someone please help?

**Comment by cicirello** [comment]
@bilelkhalsi based on your workflow, I think the problem is your first 2 tags. If you were pushing to both Docker Hub and the Github Container Registry, then you would need a step to log into Docker Hub, similar to how you logged into the GHCR. In that case your tags are fine as is. If you are only trying to push to the GHCR, then keep your tags that begin with ghcr.io/ and remove the other 2.

**Comment by crazy-max** [comment]
@bilelkhalsi Remove [these lines](https://github.com/bilelkhalsi/ioServices/actions/runs/428340714/workflow#L35-L36) and it should be ok to push to GHCR.

**Comment by bilelkhalsi** [comment]
it works!
Thank you @cicirello and @crazy-max , you saved my day 👍
