### ISSUE TITLE
Support push and load being set together

### ISSUE THREAD

**Issue by PeterJCLaw** [docker/build-push-action#1056]
### Description

Currently if the action is passed both `load: true` and `push: true` then it emits an error:

> ERROR: push and load may not be set together at the moment

It would be great if these options were supported at the same time.

Alternatively, it would be great if there was some more explanation as to why this isn't supported (it doesn't feel like it'd be hard to support?) and suggestions for what to do instead.

**Comment by crazy-max** [comment]
> ERROR: push and load may not be set together at the moment

Yes multiple exporters are currently not supported but will be in near future, see https://github.com/moby/buildkit/pull/4134

**Comment by PeterJCLaw** [comment]
Aha, thanks :)

**Comment by tonynajjar** [comment]
Can we keep this Issue open to track when this feature is available with build-push-action. I'm assuming some changes are needed in this repo as well

**Comment by crazy-max** [comment]
> Can we keep this Issue open to track when this feature is available with build-push-action. I'm assuming some changes are needed in this repo as well

No changes needed, will be available as soon as GitHub Runners update to latest buildx version

**Comment by tonynajjar** [comment]
Great, then you might want to update https://github.com/docker/build-push-action/issues/727 as well
