### ISSUE TITLE
Use a custom README file for the GitHub package rather than the main project README

### ISSUE THREAD

**Issue by eguiraud** [docker/build-push-action#1093]
### Description

Hi, 
we have a monorepo that produces several images and pushes them to the github registry.

They all pick up the main repository's readme, which gets displayed as the package's readme at https://github.com/project/packages.
It would be great if we could specify one readme per image, or if the action automatically picked up a README.md placed next to the dockerfile.

This is a continuation of as a continuation of https://github.com/docker/build-push-action/issues/722 in which this part of the issue didn't get resolved.

**Comment by crazy-max** [comment]
This is not something we control but GitHub. Atm it uses [predefined OCI annotations](https://github.com/opencontainers/image-spec/blob/main/annotations.md) to figure out from which repo it needs to take the README from: https://docs.github.com/en/packages/learn-github-packages/connecting-a-repository-to-a-package#connecting-a-repository-to-a-container-image-using-the-command-line

Don't think they have anything to specify its path though. Would suggest to open a thread in https://github.com/orgs/community/discussions/categories/packages

Thanks
