### ISSUE TITLE
Support multiple cache-from arguments

### ISSUE THREAD

**Issue by AdeelK93** [docker/build-push-action#1118]
### Description

Docker supports [multiples caches](https://docs.docker.com/build/cache/backends/#multiple-caches) - but there isn't really a way to provide multiple `cache-from` arguments.

One solution may be to allow sequences in the `cache-from`, perhaps like:
```yaml
cache-from:
- type=registry,ref=<registry>/<cache-image>:<branch>
- type=registry,ref=<registry>/<cache-image>:main 
```

**Comment by crazy-max** [comment]
This is actually supported but correct syntax is:

```yaml
cache-from: |
  type=registry,ref=<registry>/<cache-image>:<branch>
  type=registry,ref=<registry>/<cache-image>:main 
```
