### ISSUE TITLE
Allow to have a build summary without build record

### ISSUE THREAD

**Issue by ferferga** [docker/build-push-action#1151]
### Description

Hello

The new build summary it's awesome to quickly get the information of a build. However, I'd like to have more configuration options, specially regarding the build infos. I have a lot of artifacts in my workflows and having the build info it's just more noise if I'm not debugging anything, but the summary itself it's nice to have and more welcoming for users investigating workflow logs.

**Comment by crazy-max** [comment]
cc @colinhemmings

**Comment by colinhemmings** [comment]
This is great feedback @ferferga, this is something we are looking into. You mentioned this noise if you are not debugging. Do you think you would ever need the build artifact?

**Comment by ferferga** [comment]
@colinhemmings Thank you very much for taking this into consideration!

Right now I don't think so to be honest, though I was impressed when I saw this new feature (I think caching it's one of the hardest things to debug for newcomers to Docker). Though in this engineering field you never know all about anything, in my case I feel confident enough working with layers and debugging the bash scripts themselves it's probably my biggest gripes when working with containers (and probably not much Docker can do about that).
Also, for my biggest use case, it's probably not very helpful (I build multiarch images with buildx+qemu in a matrix in GH Actions. Their cache is exported so later on in another step it's merged and pushed to registries, so I'm at a 100% cache hit no matter what, [check source](https://github.com/jellyfin/jellyfin-vue/blob/af4444f6e2c52f50996c2e2dbbda514f42427b91/.github/workflows/package.yml). Totally unrelated, but it would be great if at some point we can load docker images from other platforms and merge their manifests without pushing to the registry so this secondary build step is completely unnecessary).

That said, I'm saying all of this without even pulling the artifacts and checking what is all about (not using Docker Desktop) but definitely would if I had the ability to use a CLI tool or, even better, a web application. I understand that probably both of those are out of the scope for you guys as you probably want Docker Desktop to shine, that's not issue, others can make those tools. The thing is, please make those files text-parseable and release reference docs so others can build upon this too! (again, I'm saying this without investigating anything at all in the hopes that, if something isn't currently as I suggest, it's taken into consideration)

My 2 cents in all of this.
Thank you very much as well to all of you for developing those amazing tools for us to enjoy.
