### ISSUE TITLE
Why request the production.cloudflare.docker.com ?

### ISSUE THREAD

**Issue by seepine** [docker/build-push-action#1162]
### Discussed in https://github.com/docker/build-push-action/discussions/1141

<div type='discussions-op-text'>

<sup>Originally posted by **seepine** June 17, 2024</sup>
The workflow yml
```yml
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: test:latest
```

And got the error
```
 > [linu***/arm64 internal] load metadata for docker.io/library/alpine:latest:
------
Dockerfile:1
--------------------
   1 | >>> FROM alpine
   2 |     CMD echo 'test docker build***!!'
--------------------
ERROR: failed to solve: docker.io/library/alpine: failed to resolve source metadata for docker.io/library/alpine:latest: failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/1d/1d34ffe**190be23d3de5**de0a436676**58f48f835c3a2d**68b798c15a7f1/data?verify=1718641860-garIfCZ**RLgwzS**JFgHb**0VE%3D": read tcp 172.17.0.3:42364->1*7.2*0.8.36:443: read: connection reset by peer
```

I am using Gitea with Gitea Action in a local network environment. And i have configured a registry mirror, run `docker pull alpine` is able to fetch the image.
Why does the `docker/build-push-action@v4` action need to request from production.cloudflare.docker.com, this leads to build failure.</div>

**Comment by crazy-max** [comment]
Seems an issue with Docker Hub and similar to https://github.com/docker/hub-feedback/issues/2394. Suggest to open an issue on https://github.com/docker/hub-feedback. Thanks.
