### ISSUE TITLE
Unable to Push images from GitHub Actions to Azure Container Registry (ACR)

### ISSUE THREAD

**Issue by Anto4595** [docker/build-push-action#1214]
### Description

Hello @crazy-max or anyone,

We are trying to push images through GitHub Actions to Azure Container Registry which is configured with Private Endpoint.

And whenever we try to push images we are getting Access denied error.

The Error we are getting is

error response from daemon: Get "https://.azurecr.io/v2/": denied: {"errors":[{"code":"DENIED","message":"client with IP \u0027172.214.169.102\u0027 is not allowed access. Refer
https://aka.ms/acr/firewall
to grant access."}]}*

Can you guide us on what can be the issue and guide us on this ?

Thank You...

**Comment by crazy-max** [comment]
If this is an issue with the action please create a proper bug report, not a feature request one: https://github.com/docker/build-push-action/issues/new?assignees=&labels=status%2Ftriage&projects=&template=bug.yml

Thanks
