### ISSUE TITLE
Add examples for arguments that expect lists

### ISSUE THREAD

**Issue by bschonec** [docker/build-push-action#1228]
### Description

There is no example for arguments that expects lists, such as "build-args".  It's difficult to know what the argument expects.

**Comment by crazy-max** [comment]
> There is no example for arguments that expects lists

This is explained at the very beginning of the inputs section: https://github.com/docker/build-push-action?tab=readme-ov-file#inputs

![image](https://github.com/user-attachments/assets/5d093e1b-2538-4f12-90f9-6c7d09549c90)
