### ISSUE TITLE
400 Bad request

### ISSUE THREAD

**Issue by SDCOM-0415** [docker/build-push-action#1251]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [ ] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

Yes, the documentation mentions it, but it doesn't work
After I successfully built it, it never built successfully again, and only reported an error 400 Bad request
`Error: buildx failed with: ERROR: failed to solve: failed to push ***/baota:latest: failed to copy: unexpected status from PUT request to https://registry-1.docker.io/v2/***/baota/blobs/uploads/***` It will prompt like this

![Image](https://github.com/user-attachments/assets/25701105-18c2-416a-bf4b-a0d14521cd3c)

是的，文档提到了，但是那并没有作用
在我构建成功过后，它就再也没有构建成功了，只会报错400 Bad request
`Error: buildx failed with: ERROR: failed to solve: failed to push ***/baota:latest: failed to copy: unexpected status from PUT request to https://registry-1.docker.io/v2/***/baota/blobs/uploads/***`它会这样提示

### Expected behaviour

It should be able to pull the mirrors I prepared for Chinese users normally and push it to docker hub normally

它应该被正常的拉取我在为中国用户所准备的镜像，并且正常的推送到docker hub

### Actual behaviour

`Error: buildx failed with: ERROR: failed to solve: failed to push ***/baota:latest: failed to copy: unexpected status from PUT request to https://registry-1.docker.io/v2/***/baota/blobs/uploads/***`

![Image](https://github.com/user-attachments/assets/25701105-18c2-416a-bf4b-a0d14521cd3c)

### Repository URL

https://github.com/SDCOM-0415/docker_push/

### Workflow run URL

https://github.com/SDCOM-0415/docker_push/blob/main/.github/workflows/docker-publish.yml

### YAML workflow

name: Deploy

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
          with:
            submodules: 'true'
        - name: ls
          run: ls 
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Login to DockerHub
          uses: docker/login-action@v1 
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push Docker image
          id: push
          uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
          with:
            context: .
            file: ./push/dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/baota:latest

**Comment by claylevering** [comment]
I haven't been able to debug what's happening in our GH Actions but I wanted to 👍🏻 this one mostly because our CI/CD publishes to a different repo (ECR) and uses GitHub / AWS OIDC connections.

This has just begun (randomly) and resolves itself (somewhat randomly)

**Comment by exaucae** [comment]
See https://github.com/docker/build-push-action/issues/901#issuecomment-2469210691

**Comment by crazy-max** [comment]
> and only reported an error 400 Bad request `Error: buildx failed with: ERROR: failed to solve: failed to push ***/baota:latest: failed to copy: unexpected status from PUT request to https://registry-1.docker.io/v2/***/baota/blobs/uploads/***` It will prompt like this
> 
> ![Image](https://github.com/user-attachments/assets/25701105-18c2-416a-bf4b-a0d14521cd3c)

We got some transient issues on Docker Hub past weeks but it should be solved now. If this still happens please open an issue on this repo: https://github.com/docker/hub-feedback/issues. Thanks!
