### ISSUE TITLE
Invalid domain name on push

### ISSUE THREAD

**Issue by ClementNerma** [docker/build-push-action#1269]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

This error is probably due to something I misunderstand because I can't find any report on it.

With the provided workflow (see below) I get this error at the very last build step (when pushing to the registry):

```
#26 ERROR: failed to push ClementNerma/tapo-rest:latest: failed to do request: Head "https://ClementNerma/v2/tapo-rest/blobs/sha256:2c8d23f4b7eecaf8c7661697fc5e1ea442839b15458bf7d9c6f318aaf9cb5fdd": dial tcp: lookup ClementNerma on 168.63.129.16:53: no such host
------
 > exporting to image:
------
ERROR: failed to solve: failed to push ClementNerma/tapo-rest:latest: failed to do request: Head "https://ClementNerma/v2/tapo-rest/blobs/sha256:2c8d23f4b7eecaf8c7661697fc5e1ea442839b15458bf7d9c6f318aaf9cb5fdd": dial tcp: lookup ClementNerma on 168.63.129.16:53: no such host
Reference
Check build summary support
Error: buildx failed with: ERROR: failed to solve: failed to push ClementNerma/tapo-rest:latest: failed to do request: Head "https://ClementNerma/v2/tapo-rest/blobs/sha256:2c8d23f4b7eecaf8c7661697fc5e1ea442839b15458bf7d9c6f318aaf9cb5fdd": dial tcp: lookup ClementNerma on 168.63.129.16:53: no such host
```

As you can see, it uses the repository's owner (`ClementNerma`) as the domain name, and I have no idea why.

Could someone please enlighten me? I don't know if it's a bug or an error on my side.

### Expected behaviour

The domain name should be Docker Hub's registry.

### Actual behaviour

The error depicted above

### Repository URL

https://github.com/ClementNerma/tapo-rest

### Workflow run URL

https://github.com/ClementNerma/tapo-rest/actions/runs/12088871482/job/33713179850

### YAML workflow

```yaml
name: ci

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: clementnerma
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ github.repository }}:latest
```

### BuildKit logs

```text

```

**Comment by thaJeztah** [comment]
This is probably due to how non-fully-qualified (i.e. without registry prefix) image references are normalised. When parsing image references, the default registry is docker hub (`docker.io/...`), however the format has some ambiguous situations;

- the first component (`ClementNerma` in this case) can be either a namespace on Docker Hub, an IP-address of a registry, or a domain (e.g. `docker.io`); domain can also be a local domain (`localhost`).
- Docker Hub does not allow uppercase namespaces (only lowercase), and given that the first element contains uppercase characters, it will treat it as a domain name (`ClementNerma`).

Assuming your intent is to push to Docker Hub registry, you need to tag the image using lowercase (`clementnerma`)

**Comment by ClementNerma** [comment]
Indeed, putting the username in lowercase characters solved the problem!

Thank you very much :)

**Comment by crazy-max** [comment]
> Indeed, putting the username in lowercase characters solved the problem!

See also https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md#repository-name-must-be-lowercase
