### ISSUE TITLE
Add an Option to Disable Manifest List Push During Build

### ISSUE THREAD

**Issue by omerap12** [docker/build-push-action#1279]
### Description

In the current setup for multi-architecture Docker builds using docker/build-push-action, the action automatically pushes images as a manifest list by default. Currently, there is no straightforward way to disable this automatic behavior which cause conflicts when attempting to create and manage manifests manually.

I would like to have a configuration option in the docker/build-push-action to disable automatic manifest list creation and push during the build phase. This could be controlled via a new input variable, for example:
```
disableManifestPush: true
```

When disableManifestPush is set to true the action pushes individual architecture-specific images instead of a manifest list and we can manage manifest lists manually without conflict.

**Comment by omerap12** [comment]
If anyone has alternative ideas, I’d greatly appreciate it. Currently, we are building images for ARM and AMD architectures on separate runners using the following setup:
```
- name: Docker Buildx Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ inputs.pushImage }}
          tags: ${{ steps.configure_tag_for_push.outputs.tags }}
          build-args: |
            ${{ steps.get-secrets.outputs.build_args }}
            ${{ steps.process-build-args.outputs.processed_args }}
            BRANCH_NAME="${{ needs.devops-init.outputs.branchName }}"
            IMAGE_VERSION="${{ needs.devops-init.outputs.newTag }}"
            GIT_SHA="${{ github.sha }}"
          platforms: linux/${{ matrix.architecture }}
```
This approach leads to a race condition, as shown in the following manifest data:
```
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.index.v1+json",
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:3480ee70ca128d19fc7570a659de2438471d6eb8fd2380979e972b7a2aeb6e4d",
      "size": 2580,
      "platform": {
        "architecture": "arm64",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:b8aa77efa056e1f0aff04f662b6a33f5c6e042fbeed7d9dbcc2ee2fb17b8fbb9",
      "size": 566,
      "annotations": {
        "vnd.docker.reference.digest": "sha256:3480ee70ca128d19fc7570a659de2438471d6eb8fd2380979e972b7a2aeb6e4d",
        "vnd.docker.reference.type": "attestation-manifest"
      },
      "platform": {
        "architecture": "unknown",
        "os": "unknown"
      }
    }
  ]
}
```

Since the ARM build finishes first, the AMD build fails to push the manifest as required.

To work around this, I attempted to handle manifest creation manually by tagging and pushing the images separately (e.g., -amd64 and -arm64) and then merging them. However, I ran into the following issue:
```
xxx.dkr.ecr.us-east-1.amazonaws.com/workflow-docker-build:0.15.1-pre-build.0-amd64 is a manifest list
```
The image is already a manifest list, preventing further manual merging.

**Comment by omerap12** [comment]
I’m closing this issue as I’ve found the solution. Simply add the following:

```
provenance: false
sbom: false
```
This ensures the image will be an image and not an image index.

**Comment by albertpurnama** [comment]
https://github.com/docker/build-push-action/issues/1279#issuecomment-2543154599

this works so well, thank you @omerap12

**Comment by amnuts** [comment]
I also just wanted to say thank you, @omerap12; your https://github.com/docker/build-push-action/issues/1279#issuecomment-2543154599 really helped!

**Comment by omerap12** [comment]
Glad I could help :)
