### ISSUE TITLE
Feature Request: Support Build and caching from docker-compose files

### ISSUE THREAD

**Issue by arnav13081994** [docker/build-push-action#128]
I was wondering if there was any plan to support build images from docker-compose as well?

**Comment by crazy-max** [comment]
@arnav13081994 

> I was wondering if there was any plan to support build images from docker-compose as well?

AFAIK this is not the scope of this action but we could create an action to handle [buildx bake](https://github.com/docker/buildx#buildx-bake-options-target). I have started an implementation here if you want take a look: https://github.com/crazy-max/ghaction-docker-buildx-bake

cc. @tonistiigi @chris-crone @nebuk89 @metcalfc

**Comment by chris-crone** [comment]
Thanks for raising this @arnav13081994!

As @crazy-max said this is currently out of scope but it is something we should think about. Could you please open an issue on our public roadmap for this? https://github.com/docker/roadmap
