### ISSUE TITLE
git token secret should be exposed automatically when building from git

### ISSUE THREAD

**Issue by tonistiigi** [docker/build-push-action#135]
https://github.com/docker/build-push-action#git-context

> If you use this action in a private repository, you have to pass the GitHub Token as a secret named GIT_AUTH_TOKEN to be able to authenticate against it with buildx:

There shouldn't be a need to pass `GIT_AUTH_TOKEN` when building from git, or at least when building from the current repository. I believe GH gives access to this secret always and we should automatically forward it when building from the current repo. Even on public repos I think it is better to use token.

**Comment by crazy-max** [comment]
@tonistiigi Yes LGTM

**Comment by crazy-max** [comment]
@tonistiigi 

> // This should be a token with access to your repository scoped in as a secret.
> // The YML workflow will need to set myToken with the GitHub Secret Token
>  // myToken: ${{ secrets.GITHUB_TOKEN }}
>  // https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token#about-the-github_token-secret

Looks like GitHub Token secret is [only available with user's consent through the workflow](https://github.com/actions/toolkit/blob/main/packages/github/README.md#usage). Can you confirm @clarkbw?
