### ISSUE TITLE
Add support --env-file in build 

### ISSUE THREAD

**Issue by rafilkmp3** [docker/build-push-action#142]
Exposing the --env-file option would be nice.

**Comment by crazy-max** [comment]
@rafilkmp3 [`--env-file` flag](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file) is only handled through `docker run` command and is therefore not compatible with this action which uses the build command (buildx for v2). If you want to inject variables in your image, you can use the [`build-args` input](https://github.com/docker/build-push-action#inputs) with this action. See also [Set build-time variables](https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg).

**Comment by rafilkmp3** [comment]
@crazy-max  but there is any way to read from a file to fill the `build-args`  ?

**Comment by crazy-max** [comment]
@rafilkmp3 AFAIK this is not supported by `docker build` or `docker buildx build`. You can open an issue on [docker/buildx](https://github.com/docker/buildx) if you need this feature.
