### ISSUE TITLE
Allow other options for latest

### ISSUE THREAD

**Issue by jrozner** [docker/build-push-action#146]
While the change in tagging for v2 has made it much simpler to setup it's also removed a lot of flexibility. Now that latest is tagged only via a git tag it breaks the ability to maintain multiple release branches. If I'm maintaining v1.0.x, v1.1.x, v1.2.x is in master any tag of v1.0.x or v1.1.x will end up taking the latest tag and could cause switches between major and minor incompatible versions. There should be a way to have latest always track main/master or a specified branch.

**Comment by crazy-max** [comment]
@jrozner If you talk about the [Complete workflow](https://github.com/docker/build-push-action#complete-workflow) example, you can change the behavior in the `Prepare` step.

In your case you want to push `latest` if changes have been made on the default branch (main/master):

```
-
  name: Prepare
  id: prep
  run: |
    DOCKER_IMAGE=name/app
    VERSION=noop
    if [[ $GITHUB_REF == refs/tags/* ]]; then
      VERSION=${GITHUB_REF#refs/tags/}
    elif [[ $GITHUB_REF == refs/heads/* ]]; then
      VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
    elif [[ $GITHUB_REF == refs/pull/* ]]; then
      VERSION=pr-${{ github.event.number }}
    fi
    TAGS="${DOCKER_IMAGE}:${VERSION}"
    if [[ $VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
      MINOR=${VERSION%.*}
      MAJOR=${MINOR%.*}
      TAGS="$TAGS,${DOCKER_IMAGE}:${MINOR},${DOCKER_IMAGE}:${MAJOR},${DOCKER_IMAGE}:latest"
    elif [ "${{ github.event.repository.default_branch }}" = "$VERSION" ]; then
      TAGS="${DOCKER_IMAGE}:latest"
    elif [ "${{ github.event_name }}" = "push" ]; then
      TAGS="$TAGS,${DOCKER_IMAGE}:sha-${GITHUB_SHA::8}"
    fi
    echo ::set-output name=version::${VERSION}
    echo ::set-output name=tags::${TAGS}
    echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
```
