### ISSUE TITLE
Outdated 'Complete workflow' documentation

### ISSUE THREAD

**Issue by avgur** [docker/build-push-action#149]
Current documentation on the main page contains 'Complete workflow section'.
It looks incorrect how 'tags' used there

DOCKER_IMAGE=name/app
...
TAGS="${DOCKER_IMAGE}:${VERSION}"
...
echo ::set-output name=tags::${TAGS}
...
tags: ${{ steps.prep.outputs.tags }}

The tag, at least when used with docker.pkg.github.com registry should be absolute (f.e. docker.pkg.github.com/name/app:latest)
while documentation propose to use  'name/app:latest' which does not work and fails

**Comment by crazy-max** [comment]
@avgur Documentation is based for the default registry (DockerHub) and is not intended to cover all registries in the wild. In your case you just have to prepend the registry uri like `DOCKER_IMAGE=docker.pkg.github.com/name/app`
See also https://docs.docker.com/registry/introduction/#understanding-image-naming
