### ISSUE TITLE
question/feature/doc how do you recommend push and docker image/docker-compose up?

### ISSUE THREAD

**Issue by xenoterracide** [docker/build-push-action#150]
currently you get an error that says that you can't do --load and --push together. How do you recommend accomplishing both? The reason I need to do this is I need to run `docker compose up` to do other actions, and I don't believe it will use the buildx cache. It would be good to update the docs with an example. here's my potential workflow ( may tweak it )

job1
1. buildx builder target
1. push builder
1. cache builder

job2
1. load builder cache
1. bake, or otherwise build services based on builder
1. docker-compose up
1. run tests
1. push final service images

I may simplify this and not push during the first job

**Comment by crazy-max** [comment]
@xenoterracide You could export the resulted image in `job1` like explained in https://github.com/docker/build-push-action/issues/147#issuecomment-703840959 then in `job2` download with [actions/download-artifact](https://github.com/actions/download-artifact) the artifact, load it through `docker load` and use it through `docker-compose`.

You could also only have one job that builds and loads the image in Docker with this action. I will add an example in the README for this case.
