### ISSUE TITLE
question/doc can you cache tags and images when load is set?

### ISSUE THREAD

**Issue by xenoterracide** [docker/build-push-action#151]
can you cache tags when load is set? so it's easy to run an image in a later job?

**Comment by crazy-max** [comment]
Yes you can cache image layers through [the registry](https://github.com/docker/build-push-action#cache-to-registry) or [GitHub cache](https://github.com/docker/build-push-action#leverage-github-cache).

**Comment by xenoterracide** [comment]
I've found that this doesn't work between jobs... perhaps it's a limitation of the cache between jobs?
