### ISSUE TITLE
Push to multiple registries?

### ISSUE THREAD

**Issue by robert-scheck** [docker/build-push-action#154]
I would like to be able to push a built image (the same image) to multiple registries, e.g. Docker Hub _and_ Quay. Based on the current [usage examples](https://github.com/docker/build-push-action#usage), it seems like only one registry at a time would be possible. If this is already supported, some example or hint about how to achieve this would be nice in the usage examples.

**Comment by crazy-max** [comment]
@robert-scheck I will add an example in the README.

**Comment by robert-scheck** [comment]
@crazy-max, thank you very much for the quick handling.

Unfortunately, it practically works only half for me, because the second tagging at Quay (as latest) fails as shown below (even the login user has all permissions I can grant).

```
          tags: |
            rpki/rpki-client:6.7p1
            rpki/rpki-client:latest
            quay.io/rpki/rpki-client:6.7p1
            quay.io/rpki/rpki-client:latest
```

Given the tagging works with Docker Hub, this is likely a Quay specific issue, right?

> 2020-10-04T20:26:29.5244373Z #​39 exporting to image
> 2020-10-04T20:26:29.5244710Z #​39 exporting layers
> 2020-10-04T20:26:31.5804584Z #​39 exporting layers 2.1s done
> 2020-10-04T20:26:31.5806062Z #​39 exporting manifest sha256:058c68f215ec281e8e7f34b84eee84a9b6c09c97edbb2dada9e9081ac37d1d4a done
> 2020-10-04T20:26:31.5807770Z #​39 exporting config sha256:07a6990eb699bb0619d4ead33dbea004c402597d6d53730fab089e3652a56e67 done
> 2020-10-04T20:26:31.5809577Z #​39 exporting manifest sha256:e023eb0b55afdc552d2f252ab4e37c0eceadcec4256f41d03daf8d1a39b9b34c done
> 2020-10-04T20:26:31.5812028Z #​39 exporting config sha256:11933a099391e4939f745564b02354f3ca011a744f9fc1a53abb5bedf235bf0f done
> 2020-10-04T20:26:31.5813198Z #​39 exporting manifest sha256:f231544054f3fc4534d31cb384f9f2d28e81833b7490106cbd1de340b6cf9d9a done
> 2020-10-04T20:26:31.5814610Z #​39 exporting config sha256:aaf1ab2a64eeb6b348fc82b9a8f17b928365f8a2af57633032c0e2449340b3a6 done
> 2020-10-04T20:26:31.5816180Z #​39 exporting manifest sha256:39a31c3f69aff477c0b500e7bf03b9ce5e7707fbc69e90fc80fcb964cc0bfc0b done
> 2020-10-04T20:26:31.5817894Z #​39 exporting config sha256:848d563d875a8b7d893fbfea4e111c6128564bfe11af06f9eb48ebe05d229afb done
> 2020-10-04T20:26:31.5819362Z #​39 exporting manifest sha256:8338e3b41fef3fe55ee4dde827338e09d2817e41d7bfbf13c9ebc332b5147a82 done
> 2020-10-04T20:26:31.5820834Z #​39 exporting config sha256:f30ef050efd0ea9e04f839f9b937442f107cfde66903924439af51844b46cc77 done
> 2020-10-04T20:26:31.7305824Z #​39 exporting manifest sha256:229be8f3756d2a90de63763347946caf33d6e6a5e7fdf4448594456faabc05a9 done
> 2020-10-04T20:26:31.7307265Z #​39 exporting config sha256:cd115fe2cc3277a29227e355f1b35c2467b0a2bbac8e048b23e3468265242ea5 done
> 2020-10-04T20:26:31.7308636Z #​39 exporting manifest sha256:22254c102a08837a014532add1a2640efab05be84feefa9d350a60a8aeadd7f0 done
> 2020-10-04T20:26:31.7310092Z #​39 exporting config sha256:91ab6c95083aaa1a4911d8f18b742a2f9c343cc351b27cb090baa5cc8f695f3e done
> 2020-10-04T20:26:31.7311515Z #​39 exporting manifest list sha256:c0e90516d58d4ecd13404118fe3187f9b9a4ae3636ba0e4e0d7eaab903104a1f done
> 2020-10-04T20:26:31.7312393Z #​39 pushing layers
> 2020-10-04T20:26:34.1328754Z #​39 pushing layers 2.4s done
> 2020-10-04T20:26:34.1329902Z #​39 pushing manifest for docker.io/rpki/rpki-client:6.7p1
> 2020-10-04T20:26:39.0455268Z #​39 pushing manifest for docker.io/rpki/rpki-client:6.7p1 5.0s done
> 2020-10-04T20:26:39.1889609Z #​39 pushing layers
> 2020-10-04T20:26:42.4918073Z #​39 pushing layers 3.4s done
> 2020-10-04T20:26:42.4919339Z #​39 pushing manifest for quay.io/rpki/rpki-client:6.7p1
> 2020-10-04T20:26:53.3011895Z #​39 pushing layers
> 2020-10-04T20:26:53.3013776Z #​39 pushing manifest for quay.io/rpki/rpki-client:6.7p1 10.7s done
> 2020-10-04T20:26:54.6522363Z #​39 pushing layers 1.4s done
> 2020-10-04T20:26:54.6523911Z #​39 pushing manifest for docker.io/rpki/rpki-client:latest
> 2020-10-04T20:26:59.0009618Z #​39 pushing manifest for docker.io/rpki/rpki-client:latest 4.4s done
> 2020-10-04T20:26:59.8610759Z #​39 pushing layers 0.9s done
> 2020-10-04T20:26:59.8613035Z #​39 pushing manifest for quay.io/rpki/rpki-client:latest
> 2020-10-04T20:27:00.1962333Z #​39 pushing manifest for quay.io/rpki/rpki-client:latest 0.3s done
> 2020-10-04T20:27:00.1964491Z #​39 ERROR: failed commit on ref "manifest-sha256:e023eb0b55afdc552d2f252ab4e37c0eceadcec4256f41d03daf8d1a39b9b34c": unexpected status: 401 UNAUTHORIZED
> 2020-10-04T20:27:00.1966003Z ------
> 2020-10-04T20:27:00.1966354Z  > exporting to image:
> 2020-10-04T20:27:00.1966810Z ------
> 2020-10-04T20:27:00.1968841Z failed to solve: rpc error: code = Unknown desc = failed commit on ref "manifest-sha256:e023eb0b55afdc552d2f252ab4e37c0eceadcec4256f41d03daf8d1a39b9b34c": unexpected status: 401 UNAUTHORIZED
> 2020-10-04T20:27:00.2123709Z ##[error]The process '/usr/bin/docker' failed with exit code 1

**Comment by crazy-max** [comment]
@robert-scheck Do you have a link to your repo/workflow?

**Comment by robert-scheck** [comment]
Sorry – of course: https://github.com/rpki-client/rpki-client-container/blob/master/.github/workflows/image.yml

**Comment by crazy-max** [comment]
@robert-scheck Looks like [it works](https://github.com/rpki-client/rpki-client-container/runs/1206312031?check_suite_focus=true#step:9:4022)?

**Comment by robert-scheck** [comment]
@crazy-max, no the [failed](https://github.com/rpki-client/rpki-client-container/runs/1206279333) one is where I am struggling with (same [workflow](https://github.com/rpki-client/rpki-client-container/blob/6.7p1/.github/workflows/image.yml) content). The master branch gets tagged as edge.

**Comment by crazy-max** [comment]
@robert-scheck Looks like the same issue as #126. Can you try what I suggest in https://github.com/docker/build-push-action/issues/126#issuecomment-693723334?

**Comment by robert-scheck** [comment]
@crazy-max, yes, that solved the issue - thank you very much! It might be worth to include this hint into the usage examples, too.

**Comment by crazy-max** [comment]
@robert-scheck 

> It might be worth to include this hint into the usage examples, too.

@tonistiigi Can you update the `buildx-stable-1` tag with the fix?
