### ISSUE TITLE
Examples don't work as expected

### ISSUE THREAD

**Issue by antmerlino** [docker/build-push-action#163]
### Troubleshooting
Before sumbitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

### Behaviour
I am trying to use buildx with cache in place of the default docker build. I am attempting to follow the general directions in the README.md of this project. 

First, I am trying to just convert to using buildx in place of build. For this, I've tried using `--load` to get the images into docker. I am building images off of each other, meaning container-2 uses FROM container-1 in the Dockerfile. When using this approach, buildx doesn't find container-1, even after building it and loading it into docker. Normal docker build works just fine.

Next, I am trying to use a local registry to cache things.  I am attempting to follow the instructions found here:
https://github.com/docker/build-push-action#local-registry

#### Steps to reproduce this issue
Please see repository linked below. I have reduced these issues to a very simple sample repository with parallel workflows demonstrating each attempt.

https://github.com/antmerlino/ghaction-docker-buildx

#### Expected behaviour
For buildx with `--load`, the expected behavior is that it builds just like regular docker build.

For buildx with local registry, the expected behavior is that I can communicate with the local registry.

#### Actual behaviour
For buildx with `--load`, the actual behavior is that buildx can't find the first container, when building the second.

For buildx with local registry, the actual behavior is that I get a TCP error. (I think this has to do with the fact that buildx is running using the docker-container driver and something isn't right getting back to where the docker daemon is running.) Not sure what I'm doing wrong here.

### Configuration
Please see the repo linked below for a full working (or not working) example of the issues
https://github.com/antmerlino/ghaction-docker-buildx

### Logs
Github action on the above repo contains all logs. If something more specific is needed to help, please let me know.

### Other remarks
I think if we can get this repository working with the various workflows, demonstrating what is outlined in the README.md this repository could serve as a good reference for other users who'd like to have a working reference.

Thanks for the help!

**Comment by crazy-max** [comment]
@antmerlino 

* For `--load` to be actually effective with your workflow you have to use the docker driver with buildx. You can find an example [here](https://github.com/crazy-max/docker-alpine-s6/blob/master/.github/workflows/test.yml).
* I think it fails because the namespace is not properly defined. Try with this tag: `localhost:5000/user/container-1:latest`

**Comment by antmerlino** [comment]
@CrazyMax Thanks for the input. I've just made both changes you suggested.

I now get the error message below. Looks like I can't use cache with the docker driver. What is the recommended practice then if I want cache? Is it to use the local registry?
Run docker build -t container-1:latest -f container-1/Dockerfile --cache-from "type=local,src=/tmp/.buildx-cache" --cache-to "type=local,dest=/tmp/.buildx-cache" --load .
  docker build -t container-1:latest -f container-1/Dockerfile --cache-from "type=local,src=/tmp/.buildx-cache" --cache-to "type=local,dest=/tmp/.buildx-cache" --load .
  shell: /bin/bash -e {0}
cache export feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
Error: Process completed with exit code 1.
I've tried adding the /user/ segment to the tag. Still not working
#7 ERROR: failed to do request: Head http://localhost:5000/v2/user/container-1/blobs/sha256:f3be6499e02d6ff397a0c498abd6ed308ef2f4be0a51f1c748b37e5c211dc56a: dial tcp 127.0.0.1:5000: connect: connection refused
------
 > exporting to image:
------
failed to solve: rpc error: code = Unknown desc = failed to do request: Head http://localhost:5000/v2/user/container-1/blobs/sha256:f3be6499e02d6ff397a0c498abd6ed308ef2f4be0a51f1c748b37e5c211dc56a: dial tcp 127.0.0.1:5000: connect: connection refused
Error: Process completed with exit code 1.

**Comment by crazy-max** [comment]
@antmerlino 

* `cache export feature is currently not supported for docker driver`. You have to disable cache in the meantime.
* The local registry is not registered in the [build](https://github.com/antmerlino/ghaction-docker-buildx/blob/fb3d933c3579e9fc71a128960b17650a35a8abd9/.github/workflows/buildx-local-registry.yml#L15) job. Remember that [each job runs in his own runner](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobs).

**Comment by antmerlino** [comment]
Thanks for helping me out with this @crazy-max  Much appreciated. Now everything is working except local registry.

- I get that cache isn't supported by docker driver now. But I guess my question still stands. If my goal is to have Github Actions build docker containers with build cache, what's the best way of achieving this? Is the recommendation then to do the local registry?
- I didn't realize how I had them nested. Thanks for catching that. Now the first image is built and successfully pushed, but the second container still fails to find the reference to the first. I tried it with `/user/` and without. Same error. 
```

#3 [internal] load metadata for docker.io/library/container-1:latest
#3 ERROR: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

#4 [1/1] FROM docker.io/library/container-1:latest
#4 resolve docker.io/library/container-1:latest
#4 resolve docker.io/library/container-1:latest 0.2s done
#4 ERROR: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
------
 > [internal] load metadata for docker.io/library/container-1:latest:
------
------
 > [1/1] FROM docker.io/library/container-1:latest:
------
failed to solve: rpc error: code = Unknown desc = failed to load cache key: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
Error: Process completed with exit code 1.
```

**Comment by crazy-max** [comment]
@antmerlino The [FROM is not correct](https://github.com/antmerlino/ghaction-docker-buildx/blob/5923d50359c32bbb1864241bb93315235447a65f/container-2/Dockerfile#L1). It should be `localhost:5000/container-1:latest`

**Comment by antmerlino** [comment]
@crazy-max But I wouldn't want to specify in my Dockerfile where the registry is, what if it moves? How does this work when you simply say `FROM ubuntu`? Your not including the registry host:port in that, but it's still able to resolve things. I'm sorry if I'm misunderstanding something.

Still, my biggest remaining question is this:

 **If my goal is to have Github Actions build docker containers with build cache, what's the best way of achieving this? Is the recommendation then to do a local registry?**

**Comment by crazy-max** [comment]
@antmerlino 

> FROM ubuntu? Your not including the registry host:port in that, but it's still able to resolve things. I'm sorry if I'm misunderstanding something.

See [`docker tag` doc](https://docs.docker.com/engine/reference/commandline/tag/) about naming convention. In short the default registry if none is defined will be Docker Hub (`docker.io`). If no user/org is defined it will be `library` (long name for `_`). So for `ubuntu` it will be resolved with `docker.io/library/ubuntu`.

> If my goal is to have Github Actions build docker containers with build cache, what's the best way of achieving this? Is the recommendation then to do a local registry?

**Comment by antmerlino** [comment]
@crazy-max Thanks again for all the help. You definitely cleared some things up for me. 

I had read about one big advantage of buildx being its ability to do remote build cache, and I thought that many of the users of this action were caching their builds somehow. 

I will let you know if I figure anything out too. And I look forward to seeing any progress or insights you may have about accomplishing this.

**Comment by crazy-max** [comment]
@antmerlino 

> I had read about one big advantage of buildx being its ability to do remote build cache, and I thought that many of the users of this action were caching their builds somehow.

Yes you can use export inline cache metadata to image configuration with `docker` driver as explained [here](https://github.com/docker/buildx#--cache-tonametypetypekeyvalue). (`inline` type). If you need support for other cache types (registry, local) for `docker` driver you can open an issue on [buildx](https://github.com/docker/buildx) repo.

**Comment by simpers** [comment]
@crazy-max as somebody pointed out, the example is not working. I have basically copy-pasted your example for how to cache with GitHub local cache and it is giving me the same error as above. Why do you have this example, and reference it, when people say it is not working?

The _real_ version that seems to work involves setting these values in the BuildX setup:

```yaml
   ...
   - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver: docker-container
        driver-opts: |
          image=moby/buildkit:master
          network=host
   ...
```

And the settings, `driver` and `driver-opts`, are not documented in the example as necessary so it is a very misleading example.

**Comment by crazy-max** [comment]
@simpers 

> And the settings, `driver` and `driver-opts`, are not documented in the example as necessary so it is a very misleading example.

https://github.com/docker/setup-buildx-action#inputs

**Comment by simpers** [comment]
> @simpers
> 
> > And the settings, `driver` and `driver-opts`, are not documented in the example as necessary so it is a very misleading example.
> 
> https://github.com/docker/setup-buildx-action#inputs

Did you just miss what I said? Your example that you kept linking to is not up to date or accurate and _that_ is the issue. The fact that you said "just check them example!" and then it doesn't work just makes people waste time. Why don't you update the example?

**Comment by crazy-max** [comment]
@simpers 

> Did you just miss what I said? Your example that you kept linking to is not up to date or accurate and that is the issue. The fact that you said "just check the example!" and then it doesn't work just makes people waste time. Why don't you update the example?

If you talk about [this](https://github.com/docker/build-push-action/blob/master/docs/advanced/local-registry.md) example, [it](https://github.com/docker/build-push-action/blob/c0c3e27be378d83cb938420544a628401394135d/.github/workflows/ci.yml#L151-L207) works [fine](https://github.com/docker/build-push-action/runs/2361768943?check_suite_focus=true#step:6:16).

**Comment by simpers** [comment]
> @simpers
> 
> > Did you just miss what I said? Your example that you kept linking to is not up to date or accurate and that is the issue. The fact that you said "just check the example!" and then it doesn't work just makes people waste time. Why don't you update the example?
> 
> If you talk about [this](https://github.com/docker/build-push-action/blob/master/docs/advanced/local-registry.md) example, [it](https://github.com/docker/build-push-action/blob/c0c3e27be378d83cb938420544a628401394135d/.github/workflows/ci.yml#L151-L207) works [fine](https://github.com/docker/build-push-action/runs/2361768943?check_suite_focus=true#step:6:16).

I'm not. I'm talking about this: [GitHub Cache ](https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache)
Found by following Cache -> GitHub ache under [Advanced usage](https://github.com/docker/build-push-action#advanced-usage)

**Comment by RobinDaugherty** [comment]
The example that is repeatedly linked to, [/docs/advanced/cache.md](https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md), **doesn't work**. In my testing and according to [this snarky reply](https://github.com/docker/build-push-action/issues/163#issuecomment-703829942), the docker driver _does not support "cache export"_.

While @simpers [suggests](https://github.com/docker/build-push-action/issues/163#issuecomment-824079057) that setting the driver to "docker-container" will fix it, according to [the setup-build-action docs](https://github.com/docker/setup-buildx-action#inputs) the default is already "docker-container".

The error says that the **docker** driver doesn't support cache export, while the **docker-container** driver is the one that should be in use.

Why does [this example](https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md) still exist when it doesn't work? Can someone please provide some clarity to this mess?

**Comment by RobinDaugherty** [comment]
It looks like I found the edge case that was causing my jobs to fail. I had the steps in this order:

- `docker/setup-docker-buildx`
- `azure/docker-login`
- `docker/build-push-action`

The `azure/docker-login` action was setting the `DOCKER_CONFIG` environment variable _for later steps_ so buildx setup was modifying the default configuration file (`~/.docker`), then the later steps all used a different configuration file. Two solutions worked here: either change from `azure/docker-login` to `docker/login-action`, or change the order so that `azure/docker-login` comes before `docker/setup-docker-buildx`.

So if you're using `docker/setup-docker-buildx` action with the default driver (`docker-container`) and your `docker/build-push-action` complains about the _`docker` driver_ you might have a configuration file issue.

**Comment by estiller** [comment]
Thanks, @RobinDaugherty, you saved me a lot of time debugging this.
This issue should probably be documented somewhere.

**Comment by wenoptics** [comment]
Also noted a similar documentation issue (at lease misleading) from this page [https://docs.docker.com/ci-cd/github-actions/](). 

The `## Optimizing the workflow` section quotes code without a [`docker/setup-buildx-action` step](https://github.com/docker/docker.github.io/blob/master/ci-cd/github-actions.md?plain=1#L116-L118). But if you run without `setup-buildx-action` you will get the same error saying:

> cache export feature is currently not supported for docker driver. Please switch to a different driver

Not necessarily related to `type=gha` cache but hope it help people who search the error and land here.
