### ISSUE TITLE
Nightly builds have missing labels

### ISSUE THREAD

**Issue by sagikazarmark** [docker/build-push-action#165]
#### Steps to reproduce this issue

1. Setup a repo with a complete example
2. Wait for the nightly schedule to trigger (or use a custom time to trigger it)

#### Expected behaviour

Labels should be filled with the proper values

#### Actual behaviour

Nightly builds have missing labels (when using the complete example):

```
    "org.opencontainers.image.url": "",
    "org.opencontainers.image.licenses": "",
    "org.opencontainers.image.source": ""
```

### Configuration

* Repository URL (if public): https://github.com/drakkan/sftpgo
* Build URL (if public): https://github.com/drakkan/sftpgo/runs/1214158303?check_suite_focus=true
* Package URL: https://github.com/users/drakkan/packages/container/sftpgo/111582

https://github.com/drakkan/sftpgo/blob/87f78b07b3bfc88bb821525f478f2dc8742c6a26/.github/workflows/docker.yml

### Logs

[logs_254.zip](https://github.com/docker/build-push-action/files/5333908/logs_254.zip)

## Root cause

The issue is caused by the [schedule](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#schedule) event not having a payload at all. Maybe using the [github](https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#github-context) context instead would make sense in this case

**Comment by crazy-max** [comment]
@sagikazarmark This should fix your issue: https://github.com/docker/build-push-action/pull/170/files

**Comment by sagikazarmark** [comment]
Sweet, thanks @crazy-max !

**Comment by drakkan** [comment]
Hi, thanks the logs now look correct however the description no longer appears for both edge and nightly, take a look here:

https://github.com/users/drakkan/packages/container/sftpgo/124553
https://github.com/users/drakkan/packages/container/sftpgo/122974

I think this started after adding support for [arm64](https://github.com/drakkan/sftpgo/blob/master/.github/workflows/docker.yml#L90).

I'm not sure if this issue is related to this action or is a GitHub issue. What do you think about it? Thank you

**Comment by crazy-max** [comment]
@drakkan I don't think the package description (for a specific tag) is populated through `org.opencontainers.image.description` label. You should ask on [GitHub Community forum](https://github.community/) about this. WDYT @clarkbw?

**Comment by drakkan** [comment]
> @drakkan I don't think the package description (for a specific tag) is populated through `org.opencontainers.image.description` label. You should ask on [GitHub Community forum](https://github.community/) about this. WDYT @clarkbw?

Yes, I'll try to ask on GitHub forum, and probably this is a separate issue from the one reported here, however since it started to appear after adding arm64 support it could be related to this action too, thank you

**Comment by clarkbw** [comment]
Yes, post in the forum please and we'll look if it's on the GitHub side.
