### ISSUE TITLE
Digest is no longer exported since the latest v2 release

### ISSUE THREAD

**Issue by webbertakken** [docker/build-push-action#191]
Same workflow worked [a few hours before](https://github.com/Unity-CI/docker/runs/1279830756?check_suite_focus=true) the new publication (see the step that reads `image digest`). But now doesn't export [digest](https://github.com/Unity-CI/docker/runs/1283969149?check_suite_focus=true) anymore (again see the step that reads `image digest`). 

Any workarounds to get the digest?

**Comment by webbertakken** [comment]
I seem to also not be able to find any reference to what commit was checked out before 7 hours ago, as there's no trace of the previous v2 tag, and neither does it show in the github actions logs.

Do you happen to remember the previous commit hash that was used for release? We'd gladly be reverting back to the previous version, as it was working really well before (thanks for that by the way!).

**Comment by crazy-max** [comment]
@webbertakken I think I've found the issue. Keep you in touch.

**Comment by crazy-max** [comment]
@webbertakken Should be fixed now.
