### ISSUE TITLE
Update Readme and description with push on Docker hub

### ISSUE THREAD

**Issue by SivaKesava1** [docker/build-push-action#21]
Currently, if we use the Github action with this repo, the image is built and pushed to the Docker hub, but the Readme and description are not updated on the Docker hub webpage. It would be nice to have this in the future to use this action and altogether disable auto build.

**Comment by zappy-shu** [comment]
Hi @SivaKesava1. We want to take a look at matching functionality with auto-builds so this is great feedback. Any thoughts @nebuk89?

**Comment by felipecassiors** [comment]
By the way, I've been using https://github.com/marketplace/actions/docker-hub-description to do that.

**Comment by christian-korneck** [comment]
Here's another github action that can set/update the container repo description from the README in the github repo.
It supports container repos on Docker Hub, Harbor v2 and Quay.

[update-container-description](https://github.com/marketplace/actions/update-container-description-action)

**Comment by lirantal** [comment]
@crazy-max and folks, can we re-open this to get this core capability as part of this official docker action? I'd rather use that than start piling up on third-party actions. Regardless of the community ecosystem around Docker related actions, I think this is a very core capability that I'd expect to have with this action.

**Comment by christian-korneck** [comment]
@lirantal +1 for this. For the meantime, I created a [Docker CLI plugin](https://github.com/christian-korneck/docker-pushrm) and a [github action](https://github.com/marketplace/actions/update-container-description-action) based on it to fill this gap. Feel free to open an issue if you feel it doesn't serve your needs. (Yes, it's an additional action/job step ... but github actions is all about modularity imho).

**Comment by lirantal** [comment]
Thanks!

Maybe it's worth to ping @peter-evans and ask if they'd like to contribute a pull request that adds this capability to this official action?

**Comment by crazy-max** [comment]
We will work on this. Keep you in touch! (cc @technicallyjosh)

**Comment by christian-korneck** [comment]
> @whizzzkid Did the team ever got around fixing this?

yes, it's now possible to set the repo description when authenticated with a PAT (was fixed earlier this year, there was another github issue about it that I can't seem to find at the moment). (Thanks to anyone from the Docker Hub team involved with this!)

**Comment by djbrown** [comment]
the documentation using the third party action is available here: https://docs.docker.com/build/ci/github-actions/examples/#update-docker-hub-repository-description

but this issue is open to add that functionality into this action, correct?

**Comment by srstsavage** [comment]
+1, pushing updates to the Docker Hub README should 100% be part of the core functionality.

**Comment by Alw3ys** [comment]
@djbrown is broken, for the next ones coming here to find the link. here it is:

https://docs.docker.com/build/ci/github-actions/update-dockerhub-desc/

**Comment by technicallyjosh** [comment]
Seems this one went a bit under the radar for too long 😅. Should be an easy PR to pop in. Will work on this week to include repo description to update.

**Comment by baruchiro** [comment]
@technicallyjosh Are you working on this?

**Comment by baruchiro** [comment]
@technicallyjosh @crazy-max Can you please give us a link to the new issue you're working with, so we can follow the work there?

Thank you!

**Comment by add-n2x** [comment]
Should this be still working? I get "forbidden" messages and assume it's not working in the free DockerHub plan anymore.

**Comment by christian-korneck** [comment]
@add-n2x I haven't tried this action, but my tool [Docker Push Readme](https://github.com/christian-korneck/docker-pushrm), which roughly uses the same mechanism, still works. (Tried today with Docker Hub, with a free account, with a personal access token (PAT)). So there's unlikely a new restriction on the Docker Hub side.

**Comment by snowdream** [comment]
I have tried [christian-korneck/update-container-description-action](https://github.com/marketplace/actions/update-container-description-action) .

This github action updates the description of a container repo on [Docker Hub](https://hub.docker.com/), [Quay](https://quay.io/) or [Harbor](https://goharbor.io/) v2 from a README file.

This is useful when building and pushing Docker images with github actions. It can ensure that the description of a container repo stays in sync with the README file in the github repo.
