### ISSUE TITLE
buildx call failed with: failed to solve: rpc error: code = Unknown desc = failed to compute cache key

### ISSUE THREAD

**Issue by tenjaa** [docker/build-push-action#220]
Hi,
I upgraded to v2 of you GitHub actions and have the following issue:
```
buildx call failed with: failed to solve: rpc error: code = Unknown desc = failed to compute cache key: failed to walk /tmp/buildkit-mount102943583/build/libs: lstat /tmp/buildkit-mount102943583/build/libs: no such file or directory
```

### Troubleshooting
- disable cache => same issue (https://github.com/tenjaa/concourse-github-app-token/runs/1370587907?check_suite_focus=true)

#### Steps to reproduce this issue
You can have a look at my repo linked below.
The last commit  to master worked fine. All other following commits via pull requests are failing even though stuff like a Java dependency update would be expected to fail in the gradle build job and not while creating a docker image.
Weird thing is, that even the current master doesnt seem to work anymore:: https://github.com/tenjaa/concourse-github-app-token/pull/44

#### Expected behaviour
Do not throw this error. For example like the last commit to master worked fine:
https://github.com/tenjaa/concourse-github-app-token/runs/1198450198

#### Actual behaviour
An error gets thrown, e.g.:
```
buildx call failed with: failed to solve: rpc error: code = Unknown desc = failed to compute cache key: failed to walk /tmp/buildkit-mount102943583/build/libs: lstat /tmp/buildkit-mount102943583/build/libs: no such file or directory
```
The last part varies a little but the first part is always the same:
```
buildx call failed with: failed to solve: rpc error: code = Unknown desc = failed to compute cache key: xxxxxxx
```

### Configuration

* Repository URL (if public): https://github.com/tenjaa/concourse-github-app-token
* Build URL (if public): https://github.com/tenjaa/concourse-github-app-token/pull/44/checks?check_run_id=1370633453
* workflow.yaml: https://github.com/tenjaa/concourse-github-app-token/blob/3beeef1784c56c14c265f7ef4f5a1eb4974a3233/.github/workflows/ci.yml

### Logs
Are attached and should also be visible in the repo. If not just tell me how to make them public.

**Comment by crazy-max** [comment]
@tenjaa Same as #209. The default behavior of this action is to use the Git context invoked by your workflow if no `context` is specified. That's why `build/libs` from previous steps is not available. To solve this you have to use the [Path context](https://github.com/docker/build-push-action#path-context):

```yaml
- name: Build and push Docker image
  uses: docker/build-push-action@v2
  with:
    context: .
    push: true
    tags: tenjaa/concourse-github-app-token:${{ github.sha }}
```

**Comment by tenjaa** [comment]
So there was some update in between I guess without increasing the version number?
IIRC I updated already before you promoted v2 of your resource to GA.
But thanks a lot for the qick reply! That is fixed now!
