### ISSUE TITLE
Question / Docs: User Agent

### ISSUE THREAD

**Issue by felixoi** [docker/build-push-action#228]
The docs do not contains anything about the user agent used for all docker / http actions done in this github action.
Is it the default user agent used by docker like `Docker-Client/19.03.13-ce (linux)`?

**Comment by crazy-max** [comment]
@felixoi This action is kind-of a wrapper around the buildx command and does not implement any HTTP client. If it's about buildkit, you should open an issue on [this repo](https://github.com/moby/buildkit).
