### ISSUE TITLE
Add tag_prefix input

### ISSUE THREAD

**Issue by jdbruijn** [docker/build-push-action#23]
I think an input for `tag_prefix` would be very useful in some usecases. If given, this value would be prefixed to all tags on on the image. With the current inputs, the `tag_prefix` would be prefixed to the following tag inputs. Note that I've included `tags` here as wel as I think that would be most consistent, but that is the one I'm the least sure about whether that would make sense.

- [`tags`](https://github.com/docker/build-push-action#tags)
- [`tag_with_ref`](https://github.com/docker/build-push-action#tag_with_ref)
- [`tag_with_sha`](https://github.com/docker/build-push-action#tag_with_sha)

One example, which is my usecas for this input and is something the official [ubuntu image](https://hub.docker.com/_/ubuntu) tags reflect as well.

When we have one GitHub repository with multiple Dockerfiles ([see mine as example here](https://github.com/vidavidorra/docker-linux/tree/master/docker)) to build different images (Ubuntu versions in my case). Let's say we have the following images we want to build.
- `bionic`
- `xenial`
- `focal`

WIth the `tag_prefix` with the values of the list above and e.g. a SHA of `abc1234`, these images would get the following tags.
- `bionic-sha-abc1234`
- `xenial-sha-abc1234`
- `focal-sha-abc1234`

I hope I explained everything in here correctly, but I'd be happy to elaborate and discuss.

Edit:
I've locally tested this and it should work as described above.

[input_tag_prefix.patch.txt](https://github.com/docker/build-push-action/files/4398986/input_tag_prefix.patch.txt)

**Comment by jdbruijn** [comment]
> Would you envision these prefixes being applied to all tags including those auto generated with tag_with_sha and tag_with_ref?

Yeah, especially for those. The manual `tags` is debatable IMHO since the prefix could also be added manually and might intervene with tagging that a user want to do manually. I see a couple of options to prevent this.
1. Create separate prefixes e.g. `auto_tag_prefix` and `manual_tag_prefix`.
2. Add flag e.g. `prefix_manual_tags` that enables/disables prefixing `tags`.
3. Only applying the prefix to auto generated tags.

Honestly, I could work with all these options so doesn't matter too much which one. I think option 1 might be the most user friendly.

**Comment by inodb** [comment]
This would be neat - we have the same use case with multiple dockerfiles in a single repo. Although we use a suffix instead of a prefix

Maybe one can use the stripped ref in tags?

```
tags: ["{\1}-bionic"]
```

or something along those lines. On docker hub they allow you to use a regex for the ref that you can then use with `{\1}` in the tag

**Comment by wildlifehexagon** [comment]
I also love this idea. We have been using the command line in our workflows to build custom tags (i.e. `docker build -t repo:tag-$(git rev-parse --short HEAD)`), but I would really like to replace that method with this official action.

**Comment by bryantbiggs** [comment]
I think this would also solve #66

**Comment by tonistiigi** [comment]
Opened https://github.com/moby/buildkit/issues/1569 . For build matrix take a look at `docker buildx bake` https://github.com/docker/buildx#buildx-bake-options-target
