### ISSUE TITLE
Add image tag as action output

### ISSUE THREAD

**Issue by duxi90** [docker/build-push-action#24]
Add image tag as action output so other actions in pipeline can use it.

**Comment by marius311** [comment]
This would indeed be super useful. I'm wondering if in the meantime there's a robust workaround to get this that anyone can think of?

**Comment by duxi90** [comment]
You could write an action which calculates the tag and sets it as output. Call this first and then overwrite the tag in the `build-push-action` and other subsequent jobs.

**Comment by duxi90** [comment]
I think having all of those as separate output parameters would be nice, and a fully qualified one to round things out. Also, while we're there image ID and other meta info you get when building an image could be useful as well.

**Comment by crazy-max** [comment]
Tags are now handled by yourself in v2. You can find an example in [Complete workflow](https://github.com/docker/build-push-action#complete-workflow) section. Digest is also available as an [output](https://github.com/docker/build-push-action#outputs) in v2. If you need more info, leave a comment.

**Comment by t3mi** [comment]
Is it possible to add imageId output in addition please? As in case of just image build (without push) digest isn't populated in RepoDigest field and as a result docker could not find image by digest.
```docker
$ docker image ls --digests
REPOSITORY                TAG           DIGEST      IMAGE ID            CREATED             SIZE
localhost:5000/nginx      a19477e1      <none>      91ef28407c59        4 hours ago         261MB
localhost:5000/nginx      latest        <none>      91ef28407c59        4 hours ago         261MB
```
