### ISSUE TITLE
[Docs] invalid URL around Git context

### ISSUE THREAD

**Issue by yumetodo** [docker/build-push-action#240]
> The default behavior of this action is to use the [Git context invoked](https://github.com/docker/build-push-action/blob/master/src/context.ts#L31-L35)
by your workflow.

```md
The default behavior of this action is to use the [Git context invoked](https://github.com/docker/build-push-action/blob/master/src/context.ts#L31-L35)
by your workflow.
```

https://github.com/docker/build-push-action/blob/master/src/context.ts#L31-L35
is used.

The `master` branch is not suitable for documentation. You should specify the commit hash you want to describe explicitly.
This was caused by #198 ( @crazy-max ).
I investigate the parent commit of #198 : that is 99ba0e6cbff2b9920361b79d42f93dab2cd53ead.  However, I cannot understand what @crazy-max -san trying to tell us.

https://github.com/docker/build-push-action/blob/99ba0e6cbff2b9920361b79d42f93dab2cd53ead/src/context.ts#L31-L35

**Comment by crazy-max** [comment]
@yumetodo Should be fixed through #241. Thanks.
