### ISSUE TITLE
Question - publish to ECR public registry 

### ISSUE THREAD

**Issue by bhautikpip** [docker/build-push-action#248]
Can we publish to [ECR public registry](https://gallery.ecr.aws/) using this action?

**Comment by crazy-max** [comment]
@bhautikpip 

> Can we publish to ECR public registry using this action?

Sure, most registries are compatible with this action. For ECR you just have to adapt the [Login step](https://github.com/docker/login-action#aws-elastic-container-registry-ecr) and change tags according to the registry. See also https://github.com/docker/build-push-action#push-to-multi-registries
