### ISSUE TITLE
Support for shm-size?

### ISSUE THREAD

**Issue by rickshawhobo** [docker/build-push-action#263]
I'm not seeing the ability to specify `shm-size`? Is this supported?

**Comment by crazy-max** [comment]
@rickshawhobo Same as #224, this is currently not supported by [buildkit](https://github.com/moby/buildkit) and doesn't really make sense when used with GitHub Actions. Do you have a use case?

**Comment by rickshawhobo** [comment]
Thanks for your reply @crazy-max The problem we keep running into is when we're using chrome headless to do tests we keep getting an invalid session id (about 1 out of every 20 tests) same as this issue => https://github.com/chilio/laravel-dusk-ci/issues/38 they suggested increasing the shm-size would solve it.

**Comment by crazy-max** [comment]
Tracked in https://github.com/docker/buildx/issues/418

**Comment by TomAugspurger** [comment]
Now that https://github.com/docker/buildx/issues/418 is merge and released, would this action need to be updated to add shm-size as an argument?
