### ISSUE TITLE
How can I integrate with container-structure-test?

### ISSUE THREAD

**Issue by felipecrs** [docker/build-push-action#269]
Most likely it would require a new input, such as:

`pre-publish-command: container-structure-test --image test/image`

**Comment by crazy-max** [comment]
@felipecrs We could add an input in this action but I think this should be handled by buildkit. WDYT @tonistiigi?

**Comment by felipecrs** [comment]
Any different idea here? It does not need to be like I said, if there is any other approach that could help with integrating test tools would be really helpful.
