### ISSUE TITLE
error: failed to solve: rpc error: code = Unknown desc = failed commit on ref "layer-sha256:5526117f37c73bc448a7ce1fe43f946f155cb3ceac81061b84836cf2f1839cc6": invalid content digest in response: invalid checksum digest format

### ISSUE THREAD

**Issue by DRSchlaubi** [docker/build-push-action#278]
### Behaviour

Push to Github Packages Container Registry fails

#### Steps to reproduce this issue

1. try to push to a github packages repo

### Configuration

* Repository URL (if public): https://github.com/bankobotv14/docdexdocker/
* Build URL (if public): https://github.com/bankobotv14/docdexdocker/actions/runs/496967987

Workflow: https://github.com/bankobotv14/docdexdocker/blob/c2a5af10adda80df865b1c0f487cf67de1297fad/.github/workflows/ci.yml

**Comment by crazy-max** [comment]
@DRSchlaubi https://github.com/docker/build-push-action/issues/148#issuecomment-702278002
