### ISSUE TITLE
Ability to tag without rebuild?

### ISSUE THREAD

**Issue by deitch** [docker/build-push-action#284]
Is there any way to cut tags (i.e. manifests) without rebuilding? The use cases is fairly straightforward:

1. PR 1 gets merged into master, image is built and pushed, perhaps with a git hash tag
2. PR  2 gets merged in, same thing
3. Rinse, wash, repeat
4. I am ready to cut release 1.0.0 which is just pointing at the latest manifest. Even if it needed a new manifest, all of the layers and config already exist, so it should just be generating a new manifest (or, at most, one manifest per platform plus an index).

This is not an issue locally, since I likely have everything in my local docker cache, but on Actions, where every run gets a new VM, for long builds, this can be a very long and slow release process.

I could probably try and play with `cache-from` and such, but even that is pulling layers down and then seeing if it needs to rebuild. In this case, I really am just creating a new tag or, at most, a few manifests.

Thanks!

**Comment by crazy-max** [comment]
@deitch You can use the [`docker buildx imagetools create` cmd](https://github.com/docker/buildx#buildx-imagetools-create-options-source-source) like we have done on [BuildKit repo](https://github.com/moby/buildkit/blob/master/.github/workflows/buildx-image.yml) using the [`workflow_dispatch` event](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/).
