### ISSUE TITLE
Support no context and Dockerfile from stdin

### ISSUE THREAD

**Issue by jennydaman** [docker/build-push-action#288]
Is there a way to achieve the following?

https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#pipe-dockerfile-through-stdin

```bash
docker build -<<EOF
FROM busybox
RUN echo "hello world"
EOF
```

**Comment by crazy-max** [comment]
@jennydaman There is no way to pipe through stdin atm. What's your use case?

**Comment by jennydaman** [comment]
Just some pedantic optimizations, though I recently found out that `*` in `.dockerignore` has the same effect.
