### ISSUE TITLE
path doesn't work, value remains . even if input setted with another value

### ISSUE THREAD

**Issue by shouze** [docker/build-push-action#29]
See how I've setted path to `./php` in [gogaille/docker#1](https://github.com/gogaille/docker/pull/1/files#diff-b79912647d9624f869507d01dce54fecR22)
...but value remains to `.` value [during step execution](https://github.com/gogaille/docker/runs/588572259?check_suite_focus=true#step:4:9) :sob:.

**Comment by zappy-shu** [comment]
Hi @shouze. It looks like you have the workflow file in the wrong place (workflows have to go in `.github/workflows/`). Actually you appear to have 2 copies of the workflow, one in the wrong place and one in the right.

`.github/continuous-integration.yaml` the one you linked and have changed the `path` input on isn't the one that will be run.
`.github/workflows/continuous-integration.yaml` is the file that is getting run if my guess is correct.

Can you try updating the second one and seeing if that works?

**Comment by shouze** [comment]
My fault, damned! sorry for bugging you. Thx @zappy-shu
