### ISSUE TITLE
docker push to an image on docker hub via gitlab ci/cd giving "denied: requested access to the resource is denied"

### ISSUE THREAD

**Issue by mannawar** [docker/build-push-action#291]
Hello Folks:
I am trying to set up cicd pipeline.
I have successfully build image and tagged it.
My repo on docker hub is private.
Whenever i am trying to push to docker hub it is giving "denied: requested access to the resource is denied"
Stack trace from gitalb is below:
```
The push refers to repository [docker.io/myrepo/myimage-frontend-nginx]
5ef23ebecc6b: Preparing
a57fd3e3021d: Preparing
01e894db9460: Preparing
6c7de695ede3: Preparing
2f4accd375d9: Preparing
ffc9b21953f4: Preparing
ffc9b21953f4: Waiting
denied: requested access to the resource is denied
```

**Comment by crazy-max** [comment]
@mannawar Please create a proper [bug report](https://github.com/docker/build-push-action/issues/new?assignees=&labels=&template=bug_report.md).

**Comment by mannawar** [comment]
@crazy-max below fmore info on this:

### Troubleshooting

Before sumbitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

### Behaviour
When trying to set up ci/cd in gitlab. 
#### Steps to reproduce this issue
This id .gitlab-ci.yml file config
variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
docker-build-master:
  # Official docker image.
  image: docker:18-git
  stage: build
  services:
    - docker:18-dind
  before_script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_TOKEN" $CI_REGISTRY
  script:
    - echo "Deploying Frontend..."
    - IMAGE_NAME="$CI_REGISTRY_REPO/$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
    - docker build --pull -t "$IMAGE_NAME" -f angular/Dockerfile .
    - docker push "$IMAGE_NAME"
    - echo "Frontend Deployment Complete! "
  only:
    - master

#### Expected behaviour
This should push to the docker hub private repo.

> Tell us what should happen

#### Actual behaviour

> Tell us what happens instead
request access denied showing on gitlab terminal
### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
# paste your YAML workflow file here and remove sensitive data
```

### Logs
```
The push refers to repository [docker.io/user/repo/image-frontend-nginx]
c5ce8056bb7b: Preparing
86e25071a550: Preparing
8e89381bb9fb: Preparing
6c7de695ede3: Preparing
2f4accd375d9: Preparing
ffc9b21953f4: Preparing
ffc9b21953f4: Waiting
denied: requested access to the resource is denied
Cleaning up file based variables
```

> Download the [log file of your build](https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#downloading-logs) and [attach it](https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

**Comment by crazy-max** [comment]
@mannawar That's not the right place to create an issue. This repo is about **GitHub Actions** for Docker, not Gitlab. I suggest to open a thread on [Docker Community forums](https://forums.docker.com/) about your issue. Thanks.
