### ISSUE TITLE
Feature Request: ability to skip the build step

### ISSUE THREAD

**Issue by dungahk** [docker/build-push-action#30]
My use case is I have a docker-compose file with the build steps on it. I build the images using docker-compose then I want to push to a registry. It would be nice to have this.

This is one of the things that was mentioned in this article https://www.docker.com/blog/first-docker-github-action-is-here/
And the reasoning behind the single-action approach is really good, this is the only issue, the build step is not _skipable_.

**Comment by zappy-shu** [comment]
Thansk for your feedback @dungahk. This appears to be a duplicate of #17. Would you agree?

**Comment by dungahk** [comment]
Agree, thanks!

**Comment by ddotpdot** [comment]
really relevant for me too. I uses maven jib plugin to build java docker images. and only want to push .
hence the action could allow me to push an image only.
Would be great addition
