### ISSUE TITLE
Pass in different build args depending on platform/architecture or pass platform as build-arg?

### ISSUE THREAD

**Issue by din14970** [docker/build-push-action#309]
Sorry if this is not the right place to ask/post this.

For the past few days I have been struggling with the following case: 

I want to build a project for multiple architectures. Inside the dockerfile, a release of some package must be downloaded which is platform dependent, so I have to be able to pass in a build variable that somehow indicates the platform. As I understand it, `build-args` passes in the same information to all the builds. Now I invoke `build-push-action` a number of times separately for each platform, but that means I have to assign all of them a different tag. Manually trying to join these tags with `docker manifest` also doesn't seem to work.

Is there a way in which I can pass information about the platform into the build-args so it can be used by my dockerfile?

**Comment by crazy-max** [comment]
@din14970 You don't need to pass any build arg for that, this already handled.

> A list of build arguments like `BUILDPLATFORM` and `TARGETPLATFORM` is available automatically inside your Dockerfile and can be leveraged by the processes running as part of your build.

More info: https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope

**Comment by din14970** [comment]
Awesome, exactly what I was looking for and couldn't find for days. Thanks!

**Comment by ItalyPaleAle** [comment]
Sorry for resurrecting this very old thread. I currently have the same issue, except the built-in args are not enough in my case.

In essence, I need to use a certain base image for some archs, and a completely different base image for different archs (it's an entirely different publisher, so the difference is not just in the architecture tag).

This doesn't seem to be possible with Docker buildx today, is it?

**Comment by crazy-max** [comment]
@ItalyPaleAle You can with a hacky pattern like: https://github.com/moby/moby/pull/44735/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R32-R45

**Comment by ItalyPaleAle** [comment]
Thanks @crazy-max , it's indeed hacky but should do the trick
