### ISSUE TITLE
How to check if image is already in docker hub?

### ISSUE THREAD

**Issue by saheerb** [docker/build-push-action#311]
### Troubleshooting

Sorry, as this is not a bug in first place. I am looking for some information and I believe this is the right place at least to start with.

In my pipeline, I would like to:

* Build docker image (using --load )
* Check if image already in docker hub
* If not, test the image and push to docker hub

The pipeline will be triggered both on PR and nightly basis. 

### Behaviour
Issues, I see are:
* Every docker build is creating a new docker image with new digest/ID. To counter this, I created GitHub Cache. Is it the only way to solve this?
* What is the right way to check if docker image is already in remote repo? For now, I am pulling the image and checking it's ID and then building the image and checking the ID of that image. Is there a better way?

#### Steps to reproduce this issue

1.
2.
3.

#### Expected behaviour

> Tell us what should happen

#### Actual behaviour

> Tell us what happens instead

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
# paste your YAML workflow file here and remove sensitive data
```

### Logs

> Download the [log file of your build](https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#downloading-logs) and [attach it](https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

**Comment by crazy-max** [comment]
@saheerb 

> * Check if image already in docker hub
> * If not, test the image and push to docker hub

That's not something that can be done with this action but you could use a dedicated step and check its outcome using the [`steps.<step id>.outcome` and/or `steps.<step id>.conclusion`](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#steps-context) in a further step to test the pulled image. We use this context to check whether or not a step should fail [here for example](https://github.com/docker/build-push-action/blob/c0c3e27be378d83cb938420544a628401394135d/.github/workflows/ci.yml#L221-L239).

**Comment by jcushman** [comment]
I'm not proud of my bash scripting skills, but this is what I came up with ...

```
      - name: Check if we need to rebuild
        id: check-need-build
        run: |
          RETURN_CODE=`docker manifest inspect myimage:mytag > /dev/null && echo $? || echo $?`
          echo "::set-output name=need-build::$RETURN_CODE"

      - name: Build docker image
        if: github.event_name != 'pull_request' && steps.check-need-build.outputs.need-build == '1'
        uses: docker/build-push-action@v2
        ...
```
