### ISSUE TITLE
support for --network option when build

### ISSUE THREAD

**Issue by touchinno** [docker/build-push-action#317]
I'm not seeing the ability to specify --network option? Is this supported?

**Comment by crazy-max** [comment]
@touchinno We could add this input for this action. Do you have a use case?

**Comment by touchinno** [comment]
> @touchinno We could add an input for this action. Do you have a use case?

It is my case to use docker internal DNS to access some resources on container (such as apt cache, and so on) when build custom image in github action agent.

thank you for considering...
