### ISSUE TITLE
Default to using BuildKit

### ISSUE THREAD

**Issue by garethr** [docker/build-push-action#32]
I'm finding myself always needing to remember to add the following to my actions:

```yaml
env:
        DOCKER_BUILDKIT: 1
```

I wonder if this should be a first-class part of the interface, rather than needing to know the environment variable? I also wonder if this should default to using BuildKit?

**Comment by zappy-shu** [comment]
Hi @garethr this is something I'd like to do as well. It shouldn't be too difficult to implement. 
@ndeloof any thoughts?

**Comment by crazy-max** [comment]
Version 2 has been [merged to the main branch](https://github.com/docker/build-push-action#readme) and is therefore available via `uses: docker/build-push-action@v2` (mutable tag).

As a reminder, this new version changes drastically and works with 3 new actions ([login](https://github.com/docker/login-action#readme), [setup-buildx](https://github.com/docker/setup-buildx-action#readme) and [setup-qemu](https://github.com/docker/setup-qemu-action#readme)) that we have created. Many [usage examples](https://github.com/docker/build-push-action#usage) have been added to handle most use cases.

And it should fix this current issue. Don't hesitate if you have any questions.

**Comment by theogravity** [comment]
With v2, do I need to use the `DOCKER_BUILDKIT` env variable at all? Not clear from the readme and the discussion thread here.
