### ISSUE TITLE
Bug: README hyperlinks no longer valid

### ISSUE THREAD

**Issue by cep21** [docker/build-push-action#329]
Hi,

The README  file inputs section links to `https://github.com/docker/buildx#--cache-tonametypetypekeyvalue` (Along with others on buildx)

This is no longer an anchor link on that page.  Is there another page the README should link to for

**Comment by crazy-max** [comment]
Hi @cep21,

> This is no longer an anchor link on that page.

Yes, we need to update these links (see https://github.com/docker/buildx/issues/571#issuecomment-806458839).

> Is there another page the README should link to for

https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md
