### ISSUE TITLE
buildx call failed: (503 Service Unavailable, failed to fetch oauth token)

### ISSUE THREAD

**Issue by azzamsa** [docker/build-push-action#334]
The error vanishes after using `containerd` steps in troubleshooting guides. However, I still reporting here hoping this will add more info to the maintainer for future bug fixes.

If the no error using `containerd`, what is the next step that I should take? should I stick with `containerd`?. 

### Troubleshooting

I have tried the troubleshooting steps. and it works.
Reporting here to collect and share more information.

#### Steps to reproduce this issue

1.
2.
3.

#### Expected behaviour

The built docker image should be pushed docker hub.

#### Actual behaviour

I tried the build multiple times. Both always comes up:
- buildx call failed with: error: failed to solve: rpc error: code = Unknown desc = unexpected status: 503 Service Unavailable
- buildx call failed with: error: failed to solve: rpc error: code = Unknown desc = failed to fetch oauth token: Get https://auth.docker.io/token?scope=repository%3Abiznetgio%2Fknot-exporter%3Apull%2Cpush&service=registry.docker.io: EOF

```
#17 [auth] biznetgio/knot-exporter:pull,push token for registry-1.docker.io
#17 sha256:6f892c18b455413e4928128d75846cf67f9dfdb5a339e2e23c217bcc6190d094
#17 DONE 0.0s

#16 exporting to image
#16 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#16 pushing layers 22.5s done
#16 ERROR: unexpected status: 503 Service Unavailable
------
 > exporting to image:
------
error: failed to solve: rpc error: code = Unknown desc = unexpected status: 503 Service Unavailable
Error: buildx call failed with: error: failed to solve: rpc error: code = Unknown desc = unexpected status: 503 Service Unavailable
```

```
#17 [auth] biznetgio/knot-exporter:pull,push token for registry-1.docker.io
#17 sha256:607060e234dad9841b4c4fad98e3bb890f090bc9a7c126382bcc602af457de19
#17 DONE 0.0s

#15 exporting to image
#15 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#15 pushing layers 3.9s done
#15 ERROR: failed to authorize: rpc error: code = Unknown desc = failed to fetch oauth token: Get auth.docker.io/token?scope=repository%3Abiznetgio%2Fknot-exporter%3Apull%2Cpush&service=registry.docker.io: EOF
------
 > exporting to image:
------
error: failed to solve: rpc error: code = Unknown desc = failed to fetch oauth token: Get auth.docker.io/token?scope=repository%3Abiznetgio%2Fknot-exporter%3Apull%2Cpush&service=registry.docker.io: EOF
Error: buildx call failed with: error: failed to solve: rpc error: code = Unknown desc = failed to fetch oauth token: Get auth.docker.io/token?scope=repository%3Abiznetgio%2Fknot-exporter%3Apull%2Cpush&service=registry.docker.io: EOF
```

### Configuration

* Repository URL (if public): https://github.com/BiznetGIO/knot-exporter/

* Build URL (503 Service Unavailable): https://github.com/BiznetGIO/knot-exporter/actions/runs/715086727
* Build URL (failed to fetch oauth token): https://github.com/BiznetGIO/knot-exporter/actions/runs/715112846

before using the troubleshooting step:

```yaml
name: release

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
 release:
    name: Push Docker image
    runs-on: ubuntu-16.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Prepare env
        run: |
          echo "BUILD_VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Show env
        run: |
          echo "BUILD_VERSION is: ${{ env.BUILD_VERSION }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: biznetgio/knot-exporter
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            BUILD_VERSION=${{ env.BUILD_VERSION }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

```

#### failed to fetch oauth token

[failed-to-fetch-oauth-token.txt](https://github.com/docker/build-push-action/files/6253486/failed-to-fetch-oauth-token.txt)

#### 503 Service Unavailable

[503-Service-Unavailable.txt](https://github.com/docker/build-push-action/files/6253489/503-Service-Unavailable.txt)

**Comment by crazy-max** [comment]
@azzamsa https://github.com/docker/build-push-action/issues/333#issuecomment-812929171

**Comment by crazy-max** [comment]
@azzamsa Maybe linked to https://github.com/docker/build-push-action/issues/333#issuecomment-812929171. Can you try again and let me know?

**Comment by azzamsa** [comment]
Oh my bad, next time I should check any service's status before digging deeper. 
I also feel surprised, because I don't change anything in my workflow config.


I purposely didn't delete the commit on the master, waiting any response here. 
Alright, I will make a backup branch, then revert the master branch to the previous state.

**Comment by azzamsa** [comment]
![image](https://user-images.githubusercontent.com/17734314/113492433-7c6dab00-9501-11eb-9f0b-e61a4297c66f.png)

![image](https://user-images.githubusercontent.com/17734314/113492439-8abbc700-9501-11eb-8fa2-eca65785f357.png)

Thanks a lot for all your contribution for open source community @crazy-max
