### ISSUE TITLE
Example of multistep workflow

### ISSUE THREAD

**Issue by DemiusAcademius** [docker/build-push-action#34]
How to use build artifact from previous workflow step?

I did not find examples
My script does not work (does not see the artifact collected in the previous step)

Thanks!

**Comment by zappy-shu** [comment]
Hi @DemiusAcademius can you give us an example script?

**Comment by DemiusAcademius** [comment]
I new to github actions ( migrate from gitlab)
my script:
(build-and-push step does not see contend of package dir and  periodically
interrupts )

name: SIA backend on Quarkus CI

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - 'docs/src/main/asciidoc/**'
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'ADOPTERS.md'
      - 'LICENSE.txt'
      - 'dco.txt'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/autoissuelabeler.yml'
      - '.github/boring-cyborg.yml'
      - '.github/NativeBuildReport.java'
      - '.dependabot/**'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'docs/src/main/asciidoc/**'
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'ADOPTERS.md'
      - 'LICENSE.txt'
      - 'dco.txt'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/autoissuelabeler.yml'
      - '.github/boring-cyborg.yml'
      - '.github/NativeBuildReport.java'
      - '.dependabot/**'

jobs:
  build:
    name: Build artifact with gradle
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        run: ./gradlew quarkusBuild --uber-jar
      - uses: actions/upload-artifact@v2-preview
        with:
          name: package
          path: ./build/*-runner.jar

  deploy:
    name: Create & push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Download Gradle build artifact
        uses: actions/download-artifact@v1
        with:
          name: package
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}
          tag_with_ref: true


ср, 22 апр. 2020 г. в 17:03, Nick Adcock <notifications@github.com>:

**Comment by DemiusAcademius** [comment]
My Dockerfile:

FROM adoptopenjdk:14.0.1_7-jre-openj9-0.20.0

VOLUME /tmp

COPY package/*-runner.jar app.jar

EXPOSE 8443

RUN adduser --disabled-password --gecos "" -u 1001 --no-create-home app_user && \
    chown -R app_user /tmp && \
    chown app_user /app.jar && \
    chmod 444 /app.jar

USER app_user

ENTRYPOINT [ "java", \
        "-Dfile.encoding=UTF-8", \
        "-Djava.security.egd=file:/dev/./urandom", \
        "-Duser.timezone=Europe/Chisinau", \
        "-jar","app.jar" ]

**Comment by crazy-max** [comment]
@DemiusAcademius Each job is isolated in his own runner so the fs is not shared but you can [pass data between jobs in a workflow](https://docs.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts#passing-data-between-jobs-in-a-workflow).
