### ISSUE TITLE
https with local registry

### ISSUE THREAD

**Issue by hokamc** [docker/build-push-action#353]
Can I use https with local registry? Any work around to fix this? Thanks
`error: Get http://localhost:8443/v2/: EOF`

**Comment by crazy-max** [comment]
@hokamc Do you have a link to your repo and/or workflow? Are you using a self-hosted runner?

**Comment by hokamc** [comment]
I can briefly describe the situation. I port forward the private registry (HTTPS) using kubernetes in github runner, I expected docker build will connect to the registry through https. However, it doesn't. So, I want to know whether there is way to force docker build connecting with https.

**Comment by crazy-max** [comment]
@hokamc Would need your workflow and logs as I don't have any clue of the underlying behavior of your runner. If you're using the `docker` driver to build your image, check if `localhost:8443` is not configured in `insecure-registries` in your `daemon.json`. If you're using the `docker-container` driver, you can passe specify a [BuildKit config](https://github.com/moby/buildkit/blob/master/docs/buildkitd.toml.md) through [buildx create](https://github.com/docker/buildx/blob/master/docs/reference/buildx_create.md#config) and change the behavior of your registry: `[registry."localhost:8443"]`.
