### ISSUE TITLE
Add support for multi-arch builds via buildx

### ISSUE THREAD

**Issue by maxromanovsky** [docker/build-push-action#36]

**Comment by StefanScherer** [comment]
Multi-arch would be very nice, I agree ;-)

**Comment by deitch** [comment]
Yes, please. I get that it is experimental, but if you include buildx with it, someone has the option to enable and use it.

**Comment by luiscajl** [comment]
Please +1!

**Comment by crazy-max** [comment]
This will be available through [build-push-action v2](https://github.com/docker/build-push-action/tree/v2-build-push) (#92).
You can already try it with:

* https://github.com/docker/setup-buildx-action
* https://github.com/docker/setup-qemu-action
* https://github.com/docker/login-action

**Comment by crazy-max** [comment]
Closing. See https://github.com/docker/build-push-action/issues/32#issuecomment-689859982
