### ISSUE TITLE
failed to authorize: rpc error: code = Unknown desc = failed to fetch anonymous token (Bad Request)

### ISSUE THREAD

**Issue by jc-lab** [docker/build-push-action#372]
#### Steps to reproduce this issue

workflow : https://github.com/joseph-jclab/open-vm-tools-builder/blob/e49844400fd0d01bbf8fcb9fad956185927230d3/.github/workflows/build.yaml

log : https://github.com/joseph-jclab/open-vm-tools-builder/runs/2680858043?check_suite_focus=true

#### Expected behaviour

> Should be able to access docker hub anonymously.

#### Actual behaviour

> failed to authorize

### Configuration

See "Steps to reproduce this issue"

```yml
      - name: Build in Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: local/temp:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
```

### Logs

```
docker/setup-buildx-action#3 ERROR: failed to authorize: rpc error: code = Unknown desc = failed to fetch anonymous token: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fubuntu%3Apull&service=registry.docker.io: Bad Request
------
 > [internal] load metadata for docker.io/library/ubuntu:20.04:
------
error: failed to solve: rpc error: code = Unknown desc = failed to fetch anonymous token: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fubuntu%3Apull&service=registry.docker.io: Bad Request
Error: buildx call failed with: error: failed to solve: rpc error: code = Unknown desc = failed to fetch anonymous token: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fubuntu%3Apull&service=registry.docker.io: Bad Request
```

**Comment by crazy-max** [comment]
Looks like this is an issue with your [self-hosted runner](https://github.com/joseph-jclab/open-vm-tools-builder/blob/e49844400fd0d01bbf8fcb9fad956185927230d3/.github/workflows/build.yaml#L5). Works fine on my side with GitHub runners (`ubuntu-latest`). Guess your are behind a corporate proxy.

**Comment by tgelu** [comment]
I am experiencing the same error, but not when I directly `docker pull <image>`. It seems to me like `docker compose ...` fetches images differently than `docker pull`

**Comment by maclonghorn** [comment]
Same issue here.  We host using internal Artifactory.  Using VPN.  I can ping the registry host and get an internal IP address, but `docker compose up` gives me similar error.  My issue is that it's  trying to authorize via external IP, which we are not allowing.  Any idea how to clear the docker cache?

**Comment by crazy-max** [comment]
> but `docker compose up` gives me similar error.

Well this repo is not about compose but build with GitHub Actions. Suggest to open an issue on https://github.com/docker/compose
