### ISSUE TITLE
Feature request: provide way to add --ssh argument to docker build command

### ISSUE THREAD

**Issue by adam-olema** [docker/build-push-action#39]
There does not appear to be a way to turn on the newish --ssh forwarding capability of docker build with this action.   This is needed to access private github repos from inside the Dockerfile (etc).  If this is in some way available, it is not documented.

Some way to place the ssh key(s) (or inject them from a repo secret) and get them to work with RUN --mount=type=ssh would be great.  If this ability is already present, then documentation would be greate!

**Comment by adam-olema** [comment]
I have tried using "build_args" for this, but with no success.

**Comment by ruimarinho** [comment]
I don't think this is supported for the time being. Have you found a workaround @adam-olema ?

**Comment by adam-olema** [comment]
No workaround for now.  I am just running docker build directly in my workflow instead of using the action.  This allows me to pass whatever environment and set any args I need.

**Comment by adam-olema** [comment]
While a combined action would make my workflow a lot simpler, in the end I need a level of control this action does not offer.

**Comment by whiteyhat** [comment]
I can not believe this is not implemented yet...

**Comment by crazy-max** [comment]
Will be available through #71 / #92

**Comment by whiteyhat** [comment]
@crazy-max can't wait! Any estimates for this?


@adam-olema can you share a code snippet example?

**Comment by crazy-max** [comment]
@whiteyhat 

> can't wait! Any estimates for this?

See #123

**Comment by vnikolaienko-neattech** [comment]
Sorry, maybe I missleading. How to use that -ssh flag. It's should be file?

**Comment by andyfcx** [comment]
@vnikolaienko-neattech 
https://github.com/webfactory/ssh-agent#using-the-dockerbuild-push-action-action

This is a good solution
