### ISSUE TITLE
Enable use of non-master branch as "latest"

### ISSUE THREAD

**Issue by hugorodgerbrown** [docker/build-push-action#40]
From the `tag_with_ref` docs: 

> If {branch-name} is master then the tag will be latest.

We use a workflow that has separate `master` and `dev` branches, with strict rules around the interaction between them. Anything that requires a rebuild of the image (i.e. updating dependencies, rather than source files) must go through `dev` first. We have set `dev` as our main branch in Github, and it's locked, with controls around how devs can push to it.

We would like to have the `latest` tag always applied to the `dev` branch.

Appreciate we may be outliers here, but if it was possible to add a setting, it would really make a difference for us. I'll dig around myself and if I can see how to do it, will submit a PR.

**Comment by JakeWharton** [comment]
With the recent effort to migrate away from `master` in both git and GitHub this seems more important than ever. I'm currently using `trunk` for my primary integration branch and struggling with this.
