### ISSUE TITLE
Cann't push to docker image ot pull image from local registry

### ISSUE THREAD

**Issue by ipa-rwu** [docker/build-push-action#402]
#### Steps to reproduce this issue

1. I set up a docker registry locally. The config as shown in [here](https://github.com/ipa-rwu/docker-registry/blob/main/config.yml)
2. Then I followed this [example](https://github.com/docker/build-push-action/blob/master/docs/advanced/local-registry.md) to set up a workflow

#### Expected behaviour

> I expected that the image will be pushed to my local registry.

#### Actual behaviour

> In fact, I can't find this image locally

### Configuration

The workflow yml is as described [here](https://github.com/ipa-rwu/rossystem-deployment/blob/use_local_registry/.github/workflows/docker_images_generation_with%20_local_registry.yml)

### Logs

> [logs_85.zip](https://github.com/docker/build-push-action/files/6772260/logs_85.zip)

### Question
1. Do I need to use a self-hosted runner?
2. Do I need to set my local registry to https?

**Comment by crazy-max** [comment]
Would need logs and a link to your workflow/repo.

**Comment by ipa-rwu** [comment]
I added logs and workflow in the description.

**Comment by crazy-max** [comment]
@ipa-rwu Oh sorry :sweat_smile:. Will take a look thx.

**Comment by ipa-rwu** [comment]
Thank you for your help!

**Comment by crazy-max** [comment]
@ipa-rwu As I can see you want to reuse an image pushed to a local registry in another job of your workflow. You can't do that as each job is isolated in its own runner. To share a build image between jobs see https://github.com/docker/build-push-action/blob/master/docs/advanced/share-image-jobs.md
