### ISSUE TITLE
Make input variable names POSIX-compliant

### ISSUE THREAD

**Issue by gperdomor** [docker/build-push-action#404]
### Troubleshooting

Environment variables provided to the docker build push action through with that contain a '-' are not easily accessible, and are moreover not POSIX-compliant.

At the end, something like `cache-to` is translated to `INPUT_CACHE-TO` by the actions toolkit. Let's say that we need to set that environment variable depending of the output of other command using `export INPUT_CACHE-TO=some-value`, we can't.

#### Expected behaviour

Maybe is a good idea to switch to a underscore variable names like `cache_to`, `cache_from` and make all input names POSIX-compliant...

This is already mentioned in a toolkit issue https://github.com/actions/toolkit/issues/219

**Comment by crazy-max** [comment]
docker/metadata-action#114
