### ISSUE TITLE
Best practice for environment variables

### ISSUE THREAD

**Issue by grapevineai** [docker/build-push-action#41]
Sorry for creating an issue for a question but there is no other place where I can ask a question.

How environment variables should be set? Can I simply use the env setup of the Github's workflow or do I have to use the ENV command in the Dockerfile?

**Comment by zappy-shu** [comment]
Do you mean for setting env vars inside the image you are building? If so then this should be done inside the Dockerfile using `ENV`.

If you need to set these dynamically then you can use `build_args` to injects `ARG` values and set the env var with that value in the Dockerfile. See here for details https://docs.docker.com/engine/reference/builder/#arg

**Comment by trajan0x** [comment]
@zappy-shu why can't these be set using -e?
