### ISSUE TITLE
tag fails when branch contains an underscore

### ISSUE THREAD

**Issue by fredericrous** [docker/build-push-action#414]
#### Steps to reproduce this issue

1. Create a branch that follows the group convention mentioned in the [git book](https://git-scm.com/book/en/v2/Distributed-Git-Maintaining-a-Project). For example:  `sc/ruby_client`
2. Create a commit a push your branch
3. Create a PR
4. Look at the error

![image](https://user-images.githubusercontent.com/702227/126150751-09a5539e-876f-4252-abd3-5f9c6c1bce63.png)

#### Expected behaviour

> I would expect the branch group to be removed or converted with dashes, or maybe a combination of both: first group gets removed, the next ones gets dashes

#### Actual behaviour

> The build fails when it contains an underscore

### Configuration

* Repository URL (if public): https://github.com/qdm12/ddns-updater/
* Build URL (if public): https://github.com/qdm12/ddns-updater/runs/3098788320

### Logs

see the first screenshot

**Comment by crazy-max** [comment]
@fredericrous Image name `qmcgaw/ddns-updater` is valid but `provider/porkbun` tag [is not](https://docs.docker.com/engine/reference/commandline/tag/#extended-description):

> A tag name must be valid ASCII and may contain lowercase and uppercase letters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters.

**Comment by fredericrous** [comment]
ok, I'll do that. thank you
