### ISSUE TITLE
Cache intermediate images?

### ISSUE THREAD

**Issue by mrkurt** [docker/build-push-action#417]
We're trying to use buildx caching on GitHub Actions to improve a multistage build. The problem is, it seems to only cache the final image and discard layers from intermediate builds.

Is there a way to make it cache all the layers so repeat builds are faster?

This is the Dockerfile, for context:

```Dockerfile
ADD package.json package-lock.json .npmrc ./
RUN npm install --production=false

# setup production node_modules
FROM node:14-slim as production-deps

ARG REMIX_TOKEN
ENV REMIX_TOKEN=${REMIX_TOKEN}

RUN mkdir /app/
WORKDIR /app/

COPY --from=deps /app/node_modules /app/node_modules
ADD package.json package-lock.json .npmrc /app/
RUN npm prune --production

# build app
FROM node:14-slim as build

ARG REMIX_TOKEN
ENV REMIX_TOKEN=${REMIX_TOKEN}

RUN mkdir /app/
WORKDIR /app/

COPY --from=deps /app/node_modules /app/node_modules

ADD . .

RUN npm run build

# build smaller image for running
FROM node:14-slim

ARG REMIX_TOKEN
ENV REMIX_TOKEN=${REMIX_TOKEN}
ENV NODE_ENV=production

RUN mkdir /app/
WORKDIR /app/

COPY --from=production-deps /app/node_modules /app/node_modules
COPY --from=build /app/build /app/

CMD ["npm", "run", "start"]
```

**Comment by crazy-max** [comment]
@mrkurt You can add `mode=max` in [your workflow](https://github.com/mrkurt/remix-kentcdodds/blob/dcc7d526ef76130173f793c41ba4882c71153c2c/.github/workflows/deploy.yml#L75):

```yaml
cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
```

See also https://github.com/moby/buildkit#--export-cache-options

**Comment by mrkurt** [comment]
@crazy-max oh interesting! I added that and based on the cache size reported, it looks like it included _more_ layers. It's still missing a bunch, though.

You can see the whole run here. Prior the `mode=max` it was caching ~80mb, with that setting it's doing ~200mb. It should be closer to 1GB I think: https://github.com/mrkurt/remix-kentcdodds/runs/3124854713?check_suite_focus=true

**Comment by crazy-max** [comment]
@mrkurt 

> Edit: I misunderstood what was happening, this might be working the way I want now.

LGTM from what I see in the last run: https://github.com/mrkurt/remix-kentcdodds/runs/3136719953?check_suite_focus=true
