### ISSUE TITLE
How to create a presonal registry and allow to push by github actions.

### ISSUE THREAD

**Issue by jeffrey-lunaon** [docker/build-push-action#44]
I created a docer registry but have no https certificate, and I don't known how to push automatic by github actions.

I can push image locally if I configer in `/etc/docker/daemon.json`
```json
{
    "insecure-registries": [
        "xxxx:5000"
    ]
}
```

But I don't know how to push it when I use the Github Actions, I tried to edit the `/etc/docker/daemon.json` at the workflows, but It told me Permission denied.

![image](https://user-images.githubusercontent.com/64452590/81924307-877dcb00-9611-11ea-88ad-b97afa9a634a.png)

Push image directly:
![image](https://user-images.githubusercontent.com/64452590/81924500-cad83980-9611-11ea-9823-9c064aa3ff3d.png)

**Comment by jeffrey-lunaon** [comment]
Update:
I tried to create a free https certificate by acmesh.sh and access it successed on the chrome, but when I push the image, it told me `http: server gave HTTP response to HTTPS client`

**Comment by jeffrey-lunaon** [comment]
I'm already solved this problem, I can't use nginx proxy_pass the https to registry, it's not stable and I got some error.

**Comment by robbyawaldi** [comment]
i have same problem, how to solve it?

**Comment by andylamax** [comment]
how is this solved?

**Comment by michelkok** [comment]
To anyone coming back to this much later like I did.
It can be solved using #551.
Specifically make sure to configure Docker Buildx like so:
```
name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          config-inline: |
            [registry."custom-repo.net"]
              http = true
              insecure = true
```

**Comment by tonydawhale** [comment]
@michelkok 
> To anyone coming back to this much later like I did. It can be solved using #551. Specifically make sure to configure Docker Buildx like so:
> 
> ```
> name: Set up Docker Buildx
>         uses: docker/setup-buildx-action@v1
>         with:
>           config-inline: |
>             [registry."custom-repo.net"]
>               http = true
>               insecure = true
> ```
I tried using this strategy, but I had a problem once I reached the login step. Any thoughts?
![image](https://github.com/docker/build-push-action/assets/75507889/26ebb3a1-e4b9-44e4-81fb-be346ea76b56)

**Comment by michelkok** [comment]
I'm using it in a similar way except my registry does not require a login (and I use v2 of the repo's, but I doubt that's really anything). Are you sure your credentials are right?

**Comment by tonydawhale** [comment]
Yes, when I log in via the CLI with the registry URL in the `insecure-registries` section of the docker engine settings tab in Docker Desktop, I can log in with my creds with no problem. Without putting the registry URL in that config, I encounter the same exact error when trying to log in.
```bash
❯ docker login my-domain
Username: my-user
Password:
Error response from daemon: Get "https://my-domain/v2/": http: server gave HTTP response to HTTPS client
```

**Comment by michelkok** [comment]
Okay, sorry, then I don't know but I doubt it's the config as for me (and I suppose for someone else liking my post) that usually the config should be passed. 
I keep it relatively safe by keeping it in an internal network, but definitely will add credentials at some point. There has not really been a need up to now.

**Comment by PhoenixNazarov** [comment]
I was unable to do this using the suggested solution `docker/setup-buildx-action@v3`. I did this using the usual docker commands. Perhaps `truncate` is too much here.


```
    - name: Insecure Docker Repository
      run: |
        sudo truncate -s-2 /etc/docker/daemon.json
        echo ", \"insecure-registries\": [\"${{ vars.DOCKER_HOST }}\"]}" | sudo tee -a /etc/docker/daemon.json
        sudo systemctl restart docker
    - name: Docker Auth
      run: docker login ${{ vars.DOCKER_HOST }} --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
```

![telegram-cloud-photo-size-2-5353046375455117069-y](https://github.com/docker/build-push-action/assets/51478160/9053c02d-b9aa-465b-9a5e-399ae2905171)

**Comment by onursedef** [comment]
> I was unable to do this using the suggested solution `docker/setup-buildx-action@v3`. I did this using the usual docker commands. Perhaps `truncate` is too much here.
> 
> ```
>     - name: Insecure Docker Repository
>       run: |
>         sudo truncate -s-2 /etc/docker/daemon.json
>         echo ", \"insecure-registries\": [\"${{ vars.DOCKER_HOST }}\"]}" | sudo tee -a /etc/docker/daemon.json
>         sudo systemctl restart docker
>     - name: Docker Auth
>       run: docker login ${{ vars.DOCKER_HOST }} --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
> ```
> 
> ![telegram-cloud-photo-size-2-5353046375455117069-y](https://user-images.githubusercontent.com/51478160/280680384-9053c02d-b9aa-465b-9a5e-399ae2905171.jpg)

This was a perfect solution for me. Thanks for the work!

**Comment by tonydawhale** [comment]
> I was unable to do this using the suggested solution `docker/setup-buildx-action@v3`. I did this using the usual docker commands. Perhaps `truncate` is too much here.
> 
> ```
>     - name: Insecure Docker Repository
>       run: |
>         sudo truncate -s-2 /etc/docker/daemon.json
>         echo ", \"insecure-registries\": [\"${{ vars.DOCKER_HOST }}\"]}" | sudo tee -a /etc/docker/daemon.json
>         sudo systemctl restart docker
>     - name: Docker Auth
>       run: docker login ${{ vars.DOCKER_HOST }} --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
> ```
> 
> ![telegram-cloud-photo-size-2-5353046375455117069-y](https://user-images.githubusercontent.com/51478160/280680384-9053c02d-b9aa-465b-9a5e-399ae2905171.jpg)

@PhoenixNazarov Were you still able to push to that registry? I am encountering a new, yet similar issue in my build-push action:
```
Error: buildx failed with: ERROR: failed to solve: failed to push ***/***-v3:latest: failed to do request: Head "https://***/v2/***-v3/blobs/sha256:2ac50195915c3fbb68a8083db890ef3a0bc6c4f2b9917961f7bcb24fa41ee707": http: server gave HTTP response to HTTPS client
```

**Comment by andream7** [comment]
> - name: Docker Auth
>       run: docker login ${{ vars.DOCKER_HOST }} --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

I've encountered the same issue as well.

**Comment by stevenlafl** [comment]
> To anyone coming back to this much later like I did. It can be solved using #551. Specifically make sure to configure Docker Buildx like so:
> 
> ```
> name: Set up Docker Buildx
>         uses: docker/setup-buildx-action@v1
>         with:
>           config-inline: |
>             [registry."custom-repo.net"]
>               http = true
>               insecure = true
> ```

Thanks. This works. It tripped me up at first, because of the `[registry.`. If your registry is accessible at registry.domain.com, and you push to registry.domain.com, you still need `[registry."registry.domain.com"]` - it looks weird, but it isn't like other docker configuration where you -would- do it this way: ["registry.domain.com"], like your local docker engine config.

**Comment by pedropilla** [comment]
I'm running k8s from docker-desktop, registry and runners inside it and can confirm that this works fine on my case:
```
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [registry."docker-registry.docker-registry.svc.cluster.local:5000"]
              http = true
              insecure = true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:github_runner/sample"
          push: true
          tags: docker-registry.docker-registry.svc.cluster.local:5000/test/ubuntu:latest
```

**Comment by 8192K** [comment]
```
- name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [registry."${{ secrets.DOCKER_REGISTRY_DOMAIN }}"]
              http = true
              insecure = true
```
does not work for me. But for some reason

```
- name: Insecure Docker Repository
      run: |
        sudo truncate -s-2 /etc/docker/daemon.json
        echo ", \"insecure-registries\": [\"${{ secrets.DOCKER_REGISTRY_URL }}\"]}" | sudo tee -a /etc/docker/daemon.json
        sudo systemctl restart docker
```
has stopped working, too after it ran fine a couple months ago still. I found out that daemon.json does not exist any more and has to be created first. So I came up with this solution, which works:

```
 name: Allow insecure Docker registry
      run: |
        sudo mkdir -p /etc/docker
        echo "{\"insecure-registries\": [\"${{ secrets.DOCKER_REGISTRY_URL }}\"]}" | sudo tee -a /etc/docker/daemon.json
        sudo systemctl restart docker
```

**Comment by ivictbor** [comment]
2025 update:

Two things, 

1) `buildkitd-config-inline` should be used instead of `config-inline`,  second one does not exist in [documentation](https://github.com/docker/setup-buildx-action?tab=readme-ov-file#customizing), at least in v3
2) `http=true` is enough to make registry insecure, `secure=true` [brakes it](https://github.com/moby/buildkit/issues/4915#issuecomment-2113966315)

Working snipet:

```
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [registry."1.2.3.4:5000"]
              http = true

```

⚠️ However, please note that marking the registry insecure, especially when you are trying to connect via the internet without additional tunneling is subject to MITM attacks. You can instead configure TLS certificates, here is a [detailed guide about TLS deployment from GitHub actions](https://adminforth.dev/blog/compose-ec2-deployment-github-actions-registry/), this is a little bit more complex then mark as insecure, but not dramatically. The example above has terraform sourcecode where you can find places about TLS and CA setup

**Comment by micael95** [comment]
2025 march update:

About manual restart docker:


`      - name: Insecure Docker Repository
        run: |
          if [ -f /etc/docker/daemon.json ]; then
            sudo cp /etc/docker/daemon.json /etc/docker/daemon.json.backup
          else
            echo "Arquivo daemon.json não encontrado, criando um novo."
          fi

          if [ ! -s /etc/docker/daemon.json ]; then
            echo '{"insecure-registries": ["${{ secrets.DOCKER_REPO }}"]}' | sudo tee /etc/docker/daemon.json
          else
            sudo jq --arg repo "${{ secrets.DOCKER_REPO }}" '.["insecure-registries"] += [$repo]' /etc/docker/daemon.json | sudo tee /etc/docker/daemon.json > /dev/null
          fi

          sudo systemctl restart docker`
