### ISSUE TITLE
Question: How would I access an artifact from the download-action, in the same runner, using build-publish@v2

### ISSUE THREAD

**Issue by janderssonse** [docker/build-push-action#444]
### Troubleshooting

Using the download action for artifacts https://github.com/actions/download-artifact, the build-publish actionv2 always mounts under var/lib/-buildkit.../ and so one can't access for example root /tmp/myartifcat.jar on the current runner. I guess this is becuause buildkit uses isolated runners in V2.Or am I missing something. I have tried various context changes etc. How can I achevie the same simple behaviour as in v1?

### Behaviour

Any attempt reach the download artifact from will fail (which will work in v1). 

#### Steps to reproduce this issue

See the pipe at https://raw.githubusercontent.com/janderssonse/encore/adabeaef121db25432ed91cc3511cdd62ee0d476/.github/workflows/publish.yaml - it works, and is v1. See also the commented items in my try to achive the same thing with v2

**Comment by crazy-max** [comment]
@janderssonse 

> Any attempt reach the download artifact from will fail (which will work in v1).

Do you have a link to a workflow using v2 and a failed run? I don't see anything on https://github.com/janderssonse/encore.

**Comment by janderssonse** [comment]
See the failed action https://github.com/janderssonse/encore/actions  here and the pipeline here https://raw.githubusercontent.com/janderssonse/encore/dockerci/.github/workflows/publish.yaml .

**Comment by janderssonse** [comment]
I used https://github.com/actions/cache  instead and it did what I wanted. While I could not get the artifact upload/download to work it does not matter, as the cache-action would let me achieve the same end result. Thanks anyway for the work on this and other actions.

**Comment by crazy-max** [comment]
Looks like it [works](https://github.com/janderssonse/encore/runs/3527421833?check_suite_focus=true#step:8:229) now:

```
...
#7 [2/5] COPY build/libs/encore*.jar /app/encore.jar
#7 DONE 0.4s
...
```
