### ISSUE TITLE
Not able to use docker/build-push-action@v2 without buildx setup action

### ISSUE THREAD

**Issue by chandankumar-kr** [docker/build-push-action#445]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

#### Steps to reproduce this issue

1. Use action `docker/build-push-action@v2` without setting up buildx
2.
3.

#### Expected behaviour

- It should build the image

#### Actual behaviour

Got this error `Error: Docker buildx is required. See https://github.com/docker/setup-buildx-action to set up buildx.`

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
# paste your YAML workflow file here and remove sensitive data
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs) and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

**Comment by crazy-max** [comment]
Buildx is required for this action as explained in the [README](https://github.com/docker/build-push-action#upgrade-from-v1). You can still use [v1](https://github.com/docker/build-push-action/tree/releases/v1) if you want.
