### ISSUE TITLE
Checking if an image exists

### ISSUE THREAD

**Issue by sir-farfan** [docker/build-push-action#446]
Is it possible to use this action or it's relatives to check whether or not a particular image exists in the repository and skip jobs based on that?

**Comment by crazy-max** [comment]
@sir-farfan 

> Is it possible to use this action or it's relatives to check whether or not a particular image exists in the repository and skip jobs based on that?

Not sure about your use case but no, this action doesn't have this kind of behavior. You could add a step that makes this check and play with the [step context outcome/conclusion](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#steps-context) to skip/continue the workflow.

**Comment by rkochar** [comment]
> Not sure about your use case

If there are no changes to the Docker image, why push? [A possible work around](https://stackoverflow.com/a/70711156/12555857).
