### ISSUE TITLE
[feature] Please consider adding a soft-fail flag

### ISSUE THREAD

**Issue by jauderho** [docker/build-push-action#462]
### Troubleshooting

So I've been working on multi-platform builds as I find time, and what I'm finding is that there are some inconsistencies on shipped packages for say Ubuntu on different architectures. If I simply specify all the platforms I want to build, say linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6,linux/s390x,linux/ppc64le, it would be nice to be able to set a soft-fail where the successful platforms continue on and I get error messages about the platforms that failed.

This makes it much easier to triage which platforms (more than 1) failed and why. Else, I have to manually step through and commit individual platforms to debug what went wrong 

### Behaviour

See above

#### Steps to reproduce this issue

1. Add large number of platforms : linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6,linux/s390x,linux/ppc64le
2. If any fail, the entire workflow fails

#### Expected behaviour

Enable the ability to set a soft-fail flag so that successful builds continue on and does not break the entire build

#### Actual behaviour

See above.

### Configuration

See above. 

### Logs

See above.

**Comment by crazy-max** [comment]
@jauderho Can you open an issue on https://github.com/moby/buildkit for this please? Thanks
