### ISSUE TITLE
Did't push the image to github package, but workflow completed job

### ISSUE THREAD

**Issue by bwhyman** [docker/build-push-action#47]
Hello, I am trying to integrate maven build and docker push. There are no errors after workflow script execution, but there is no image in my package.

Workflow script:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: bwhyman/githubactions-examples/githubactions
        tag: latest
logs
![image](https://user-images.githubusercontent.com/16377378/82772145-df69cc80-9e70-11ea-9abb-b1a5f1349652.png)

And the following script by using docker command works fine.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: docker push
      run: |
        docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
        docker build . -t docker.pkg.github.com/bwhyman/githubactions-examples/githubactions
        docker push docker.pkg.github.com/bwhyman/githubactions-examples/githubactions

Did I miss something??
Thanks a lot

**Comment by MaxHorstmann** [comment]
+1

**Comment by MaxHorstmann** [comment]
@bwhyman 

> `tag: latest`

try `tags: latest` 

The broader issue appears to be that it fails silently.

**Comment by bwhyman** [comment]
how stupid i am ... It's working fine now.
I think if the input like: tags: [tag1, tag2] and show error logs if the input property name is incorrect, is better.
Thank you @MaxHorstmann
