### ISSUE TITLE
"tags" not required, but omitting it doesn't do what you'd expect

### ISSUE THREAD

**Issue by MaxHorstmann** [docker/build-push-action#48]
The `tags` input is currently [optional](https://github.com/docker/build-push-action/blob/master/action.yml#L25)...

```
tags:
    description: Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
    required: false
```

... but when it's omitted, no images are actually pushed to the registry. You'll typically see something like this in the logs:

```
...
Successfully built 36c976682bcd
Pushing image []
```

The workflow will succeed, since technically it was successful in pushing 0 images, but that's a little misleading. It would be reasonable to expect it to push an image with the `:latest` default tag, like the Docker CLI does when there's no tag - e.g.

```
$ docker build org/repo .
$ docker push org/repo 
```

It would seem sensible here to either make `tags` a required input (explaining in the comment that `latest` needs be specified explicitly, if so desired) *or* implement a default tag `latest`, analogous to the Docker CLI.

**Comment by mikemol** [comment]
So, I don't use `tags`, I use tag_with_ref ... `tags` should not be mandatory if any other tagging mechanism is available.

Also, I have used Docker build processes for ephemeral build+test pipelines; the `docker build` step creates a clean environment to download code, build it and run tests against it. I don't need to care about the docker image that's built as part of this; just the existence of the ephemeral build and test environments is all I need. Requiring tags in that circumstance as a way of forcing image pushes would be contrary to that use case.

Possible alternatives:

- Don't require `tags` if any of the `tag_with` fields are set to `true`.
- Default to requiring some form of tagging if pushing is enabled, but allow pushing to be disabled.

**Comment by crazy-max** [comment]
Version 2 has been [merged to the main branch](https://github.com/docker/build-push-action#readme) and is therefore available via `uses: docker/build-push-action@v2` (mutable tag).

As a reminder, this new version changes drastically and works with 3 new actions ([login](https://github.com/docker/login-action#readme), [setup-buildx](https://github.com/docker/setup-buildx-action#readme) and [setup-qemu](https://github.com/docker/setup-qemu-action#readme)) that we have created. Many [usage examples](https://github.com/docker/build-push-action#usage) have been added to handle most use cases.

This new version should fix your issue. See also https://github.com/docker/build-push-action#complete-workflow. Don't hesitate if you have any questions.
