### ISSUE TITLE
Question: How is docker run cache handled across rebuilds

### ISSUE THREAD

**Issue by nmiculinic** [docker/build-push-action#482]
For example I have the following lines in the dockerfile:

```
RUN --mount=type=cache,target=/go/pkg/mod go mod download
RUN --mount=type=cache,target=/root/.cache/go-build --mount=type=cache,target=/go/pkg/mod CGO_ENABLED=0 go build -ldflags "${LDFLAGS}" -o app ./cmd/controlplane
```

How are those cache lines handled across rebuilds? I'm missing details in the documentation to understand what's happening.

**Comment by Richard87** [comment]
This would be amazing for my `RUN yarn install` and `RUN composer install` lines!

**Comment by crazy-max** [comment]
Since https://github.com/docker/buildx/pull/672 BuildKit state is saved in a named volume. We should be able to cache it and mount it back but that would require some changes in the [setup-buildx-action](https://github.com/docker/setup-buildx-action). Will think about it.

**Comment by crazy-max** [comment]
Tracked in https://github.com/docker/setup-buildx-action/issues/122
