### ISSUE TITLE
Question: Can the multiplatform feature with QUEMU run in parallell for every platform given as argument?

### ISSUE THREAD

**Issue by janderssonse** [docker/build-push-action#492]
Using the multiplatform feature as given in the example https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md I noticed the the platforms are not build in parallel, as the build time essentially doubles for every platform target added.

 Is there any way to configure every platform build to run in parallel, or/and to offload every platform build to another runner.If, so are there any examples?

**Comment by crazy-max** [comment]
@janderssonse 

> I noticed the the platforms are not build in parallel

They should. Do you have a link to your repo? Are you using a self-hosted runner?

> or/and to offload every platform build to another runner

You can set the [platforms supported by a node](https://github.com/docker/buildx/blob/master/docs/reference/buildx_create.md#-set-the-platforms-supported-by-the-node) with `docker buildx create --platforms ...`.

**Comment by janderssonse** [comment]
Thanks for the answer, we actually skipped the multibuild for other reasons as of now, but I think the other pointer you gave would help me achieve what I want next time. (creating nodes ) Yes, I noticed they were actually running in parallel, just on the same node btw. So for me, this Question can be closed, and thanks for the link.
