### ISSUE TITLE
Push readme to docker.hub

### ISSUE THREAD

**Issue by movative** [docker/build-push-action#512]
### Troubleshooting

I know that this issue realy did not to fit in this repo, but maybe someone can tell where I should put it.
I want to push my readme's from my image's to docker.hub from the CI but the current API only allows user+password+no2FA.

#### Steps to reproduce this issue

1. Use docker
2. Use 2FA
3. Build images
4. Try to upload a readme in your ci

**Comment by crazy-max** [comment]
#21
