### ISSUE TITLE
Option to allow disable automatic repository checkout

### ISSUE THREAD

**Issue by cl8dep** [docker/build-push-action#514]
Currently I have a project in which before building the image I modify some internal manifest files with configuration values and other details. When using this Github Action it is impossible since even if you modify the files before doing build they are ignored by the step..

The idea is not to have to move that logic with the files to the image construction process.

**Comment by Ashniu123** [comment]
By using `context: .` you can skip the checkout.

**Comment by crazy-max** [comment]
@cl8dep https://github.com/docker/build-push-action/issues/483#issuecomment-944263860

**Comment by cl8dep** [comment]
> By using `context: .` you can skip the checkout.

Oh. I will use this way. But the doc provided made it difficult for me to reach that conclusion.  it would be good if it was commented on in the action doc.

**Comment by Ashniu123** [comment]
I agree. The documentation for this action is not up to the mark.
