### ISSUE TITLE
Question: Does the docker build check the repository?

### ISSUE THREAD

**Issue by tomeichlersmith** [docker/build-push-action#52]
I am using this action to build an image with a lot of dependencies in it for the application I am developing. These several dependencies take a long time to build and install onto the docker image, and therefore the docker image takes a long time to build.

When I am developing the docker image locally, the docker cache stores the intermediate layers so that it only needs to rebuild the layers after and including any changes I made. I am wondering if this action has a similar feature. Does it pull down the image from dockerhub to see which layer to start from?

Thank you

**Comment by hholst80** [comment]
Nope. But check this. https://dev.to/dtinth/caching-docker-builds-in-github-actions-which-approach-is-the-fastest-a-research-18ei

**Comment by tomeichlersmith** [comment]
Awesome, thank you very much.

**Comment by crazy-max** [comment]
This will be available through [build-push-action v2](https://github.com/docker/build-push-action/tree/v2-build-push) (#92) which uses buildx. You can already try it with:

* https://github.com/docker/setup-buildx-action
* https://github.com/docker/setup-qemu-action
* https://github.com/docker/login-action

**Comment by crazy-max** [comment]
Version 2 has been [merged to the main branch](https://github.com/docker/build-push-action#readme) and is therefore available via `uses: docker/build-push-action@v2` (mutable tag).

As a reminder, this new version changes drastically and works with 3 new actions ([login](https://github.com/docker/login-action#readme), [setup-buildx](https://github.com/docker/setup-buildx-action#readme) and [setup-qemu](https://github.com/docker/setup-qemu-action#readme)) that we have created. Many [usage examples](https://github.com/docker/build-push-action#usage) have been added to handle most use cases.

And it should fix this current issue. Don't hesitate if you have any questions.
