### ISSUE TITLE
Error: Temporary failure in name resolution

### ISSUE THREAD

**Issue by suyar** [docker/build-push-action#520]
### Behaviour

Login to Aliyuncs then build and push to registry.cn-hangzhou.aliyuncs.com fail:

```
...
...
#11 pushing layer 70c4d730b083 275.3s
#11 pushing layer 70c4d730b083 281.9s
#11 pushing layer 60dfd935fe1a 285.2s done
#11 pushing layer abccda59f4a2 285.2s done
#11 pushing layer bc7ce6357b22 285.2s done
#11 pushing layer 47003bc5e131 285.2s done
#11 pushing layer 70c4d730b083 285.2s done
#11 pushing layer 9c60a520fbc2 280.8s done
#11 pushing layer 197778d10010 280.8s done
#11 pushing layer b65c3076245b 280.8s done
#11 pushing layer 5dfc40c1b4dd 280.8s done
#11 pushing layer 02eef72b445f 280.8s done
#11 pushing layer e45a78df7536 280.8s done
#11 pushing layer ddcd8d2fcf7e 280.8s done
#11 pushing layer 87c8a1d8f54f 280.8s done
#11 ERROR: dial tcp: lookup dockerauth.cn-hangzhou.aliyuncs.com: Temporary failure in name resolution
------
 > pushing ***/***/php:7.2-fpm with docker:
------
error: dial tcp: lookup dockerauth.cn-hangzhou.aliyuncs.com: Temporary failure in name resolution
Error: buildx failed with: error: dial tcp: lookup dockerauth.cn-hangzhou.aliyuncs.com: Temporary failure in name resolution
```

But sometimes there are no mistakes.

#### Steps to reproduce this issue

1. Push code and start actions.
2. Wait for the result.

![image](https://user-images.githubusercontent.com/15704489/146482108-1803b862-babc-44b7-a13b-d73e16510732.png)

#### Expected behaviour

> Successful push

#### Actual behaviour

> Build success but push fail.

### Configuration

* Repository URL (if public): registry.cn-hangzhou.aliyuncs.com
* Build URL (if public): https://github.com/suyar/docker-php/actions/runs/1590233406
* yml: https://github.com/suyar/docker-php/blob/main/.github/workflows/build-php-images.yml

**Comment by crazy-max** [comment]
Looks like a (DNS) network issue on GitHub runners. Suggest you open a support ticket to GitHub about this: https://support.github.com/contact
