### ISSUE TITLE
add support for specifying the deckerignore file

### ISSUE THREAD

**Issue by raffaelespazzoli** [docker/build-push-action#523]
Please add support for specifying a docker ignore file different from the default.
Thanks

**Comment by crazy-max** [comment]
You can override with `<path/to/Dockerfile>.dockerignore`: https://github.com/moby/buildkit/pull/901. See also https://docs.docker.com/engine/reference/commandline/build/#use-a-dockerignore-file. More context in https://github.com/moby/moby/issues/12886
