### ISSUE TITLE
Unable to pull from Dockerhub during load from metadata step on self-hosted runners

### ISSUE THREAD

**Issue by dresselm** [docker/build-push-action#536]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

### Behaviour

When running on GitHub-hosted runners, there is NO issue. 

When running on self-hosted runners, we fail during the build and push step.

All of our projects that use the `build-push-action` have been failing today at the same step in the build process:

### Python-alpine
```
#3 [linux/amd64 internal] load metadata for docker.io/library/python:3.8-alpine
106
#3 ERROR: failed to do request: Head "https://registry-1.docker.io/v2/library/python/manifests/3.8-alpine": read tcp x.x.x.x:50474->y.y.y.y:443: read: connection reset by peer
```

### Alpine
```
#3 [internal] load metadata for docker.io/library/alpine:3.10.9
808
#3 ERROR: failed to do request: Head "https://registry-1.docker.io/v2/library/alpine/manifests/3.10.9": read tcp x.x.x.x:38070->y.y.y.y:443: read: connection reset by peer
```

#### Steps to reproduce this issue

1. Use self-hosted runner
2. Using Dockerfile that points to Dockerhub
3. Run all the actions for build-push flow:
a. `docker/login-action@v1`
b. `docker context create gac-builder`
c. `docker/setup-buildx-action@v1`
d. `docker/build-push-action@v2.7.0` with platforms: `linux/arm64/v8,linux/amd64`

Notes:
1. we can communicate with Dockerhub.io from our runners when we shell in
2. Github propagated a new version of their runner this morning: `v2.285.1` to `v2.286.0`: https://github.com/actions/runner/compare/v2.285.1...v2.286.0

#### Expected behaviour

> The Dockerfile builds and pushes as it does in the non-self-hosted runner case

#### Actual behaviour

> Fetching meta data from Docker.io fails

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
# paste your YAML workflow file here and remove sensitive data
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs) and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

**Comment by dresselm** [comment]
Mostly curious if others are seeing this issue or if this is isolated to us

**Comment by dresselm** [comment]
Heads up to those following along that our issue was related to some internal misconfigurations related to iptables: https://github.com/docker/buildx/issues/191

**Comment by jizusun** [comment]
We have the same problem!

**Comment by dlhck** [comment]
Running into the same problem. Any solution?
