### ISSUE TITLE
Example on how to use outputs.metadata in follow on steps

### ISSUE THREAD

**Issue by Nevario** [docker/build-push-action#554]
I'm trying to populate an ECS task definition and need to retrieve the generated image name from the metadata output.

This has proved more challenging than expected (I'm new to Github actions).

Initially I tried

```
  image: ${{ steps.docker-build.outputs.metadata.image.name }}
```

but this doesn't work because its JSON and I've learnt that you can't access properties like this.

Then I tried adding an intermediate step that parses through the JSON with `jq` but my syntax is wrong.

```
-   id: get-build-name
    run: |
        imageName=$( steps.docker-build.outputs.metadata | jq '.image.name' )
        echo "::set-output name=image_name::$imageName"
```

Before I continue down this rabbit hole, could someone please confirm that I'm not missing something obvious?

**Comment by crazy-max** [comment]
@Nevario You can handle JSON output with the [`fromJSON` function](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#fromjson) expression:

```yaml
    run: |
        imageName=${{ fromJSON(steps.meta.outputs.json)."image.name" }}
        echo "::set-output name=image_name::$imageName"
```

**Comment by Nevario** [comment]
@crazy-max Thank-you for the tip.

Unfortunately I'm still having a syntax issue 

> The workflow is not valid. .github/workflows/deploy.yml (Line: 62, Col: 22): Unexpected symbol: '"image'. Located at position 47 within expression: fromJSON(steps.docker-build.outputs.metadata)."image.name"

```
-   id: get-build-name
    run: |
        imageName=${{ fromJSON(steps.docker-build.outputs.metadata)."image.name" }}
        echo "::set-output name=image_name::$imageName"
```

Thanks for your help.

**Comment by crazy-max** [comment]
Sorry my bad I was _jq-thinking_ :sweat_smile:. This syntax should work:

```yaml
-   id: get-build-name
    run: |
        imageName=${{ fromJSON(steps.docker-build.outputs.metadata)['image.name'] }}
        echo "::set-output name=image_name::$imageName"
```

**Comment by Nevario** [comment]
Thank you so much!
