### ISSUE TITLE
Add support --squash in build

### ISSUE THREAD

**Issue by junghans** [docker/build-push-action#56]
Exposing the `--squash` option would be nice.

**Comment by crazy-max** [comment]
@junghans Not [yet implemented](https://github.com/docker/buildx/blob/bda4882a65349ca359216b135896bddc1d92461c/commands/build.go#L75). See moby/buildkit#819.

**Comment by crazy-max** [comment]
Tracked in https://github.com/moby/buildkit/issues/819

**Comment by nctiggy** [comment]
I know this got closed, but following the link provided does not help me understand if this was implemented or is going to be implemented. I am probably just not fully understanding. Can anyone comment on this?

**Comment by wildone** [comment]
oh man...

**Comment by Arkasha18** [comment]
yes need!
