### ISSUE TITLE
Upgrade to buildx 0.8.0 to get `.env` file support

### ISSUE THREAD

**Issue by nomiro** [docker/build-push-action#562]
At the moment, as best as I can tell, this action uses buildx 0.7.0 (based on `hack/build.Dockerfile`). (If I am incorrect, can you please tell me where you specify the buildx version?)

Unfortunately, [buildx 0.7.0 does not support `.env` files](https://github.com/docker/buildx/issues/282), and this action provides no way to configure the `.env` file.

Fortunately, [buildx 0.8.0 now supports `.env` files](https://github.com/docker/buildx/pull/905). The [0.8.0 milestone](https://github.com/docker/buildx/milestone/11) appears to be complete. However, as of writing, [0.8.0 has not been released yet](https://github.com/docker/buildx/releases).

When buildx releases 0.8.0, can you please upgrade to 0.8.0 so that we can use `.env` files with this action?

**Comment by crazy-max** [comment]
> (based on `hack/build.Dockerfile`).

The only purpose of this Dockerfile is to build the action.

> this action uses buildx 0.7.0

This action uses whatever version of buildx is available on the GitHub runner but you can use the [setup-buildx-action](https://github.com/docker/setup-buildx-action) to set the buildx version you want.

If you want the `.env` support you can try the [v0.8.0-rc1](https://github.com/docker/buildx/releases/tag/v0.8.0-rc1).
