### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by jtagcat** [docker/build-push-action#566]
`tag-semver: true`

https://semver.org/  
If tag fits / is compatible with semantic versioning (such as v1.2.3), tag `xyz/foobar:1`, `xyz/foobar:1.2`, `xyz/foobar:1.2.3`.

Thoughts?

**Comment by jtagcat** [comment]
(might want to use https://github.com/jtagcat/action-docker-ghpackages/blob/main/.github/workflows/docker-ghcr.yml as a partial reference)

**Comment by crazy-max** [comment]
See https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md#handle-tags-and-labels to handle tags. More info: https://github.com/docker/metadata-action#typesemver
