### ISSUE TITLE
readme says buildx is not required, but action fails if its not there

### ISSUE THREAD

**Issue by rethab** [docker/build-push-action#567]
_this is just a small docs issue so I took the liberty and removed the official bug template_

In the readme, it says on buildx:

> This is not required but recommended

But in the [code](https://github.com/docker/build-push-action/blob/master/src/main.ts#L15), there's this condition:

```typescript
    if (!(await buildx.isAvailable())) {
      core.setFailed(`Docker buildx is required. See https://github.com/docker/setup-buildx-action to set up buildx.`);
      return;
    }
```

I think it would be good to update the readme and make it clear that buildx is in fact required :)

**Comment by crazy-max** [comment]
If you talk about [this section](https://github.com/docker/build-push-action#usage) in the README, it says [`setup-buildx` action](https://github.com/docker/setup-buildx-action) is not required. Not buildx itself.

**Comment by beebird** [comment]
@crazy-max  refer to  https://github.com/docker/setup-buildx-action , seems this can be skipped by setting `install` `driver`
