### ISSUE TITLE
Copied files and folders are granted with chmod 777

### ISSUE THREAD

**Issue by shinsenter** [docker/build-push-action#570]
### Troubleshooting

Files and folders copied to image are all granted with 777 permissions when using docker buildx with default context (the Git context).

#### Steps to reproduce this issue

```Dockerfile
FROM scratch
COPY bin/ /usr/bin/
```

#### Expected behavior

The `/usr/` and `/usr/bin/` folders should not have chmod 777.

#### Actual behavior

The `/usr/` and `/usr/bin/` folders are granted chmod 777.

**Comment by crazy-max** [comment]
Would need a repro. Do you have a link to your repo?

**Comment by shinsenter** [comment]
@crazy-max 
I created a sample here, but I could not represent the issue at the time running this action. 😅
https://github.com/shinsenter/playground/runs/5546846140?check_suite_focus=true
