### ISSUE TITLE
Feature request: Build from compose file

### ISSUE THREAD

**Issue by mfloresVicomtech** [docker/build-push-action#572]
Hi, I miss the option of building multiple images from a compose file. This would be very helpfull in monorepo repositories where all services are under the same hood.
Same layer caching and other options that make this action great, and maybe some way to even be able to apply multiple tags and push to different image repos.
For the time being I do this with a composite action that loops over a list of requested services to build and applies all the required tags and push to repo all of them, but I miss the cache option and implies an additional action to manage.

**Comment by crazy-max** [comment]
You can use the [bake-action](https://github.com/docker/bake-action) for that purpose. See also https://github.com/docker/buildx/blob/master/docs/reference/buildx_bake.md#examples
