### ISSUE TITLE
 build-push-action can't push image to docker hub

### ISSUE THREAD

**Issue by newconceptconsulting** [docker/build-push-action#587]
now, I'm can't push image to docker hub #21 exporting to image #21 pushing layers 0.2s done #21 ERROR: server message: insufficient_scope: authorization failed  #25 [auth] ***/image,push token for registry-1.docker.io #25 DONE 0.0s ------  > exporting to image: ------ error: failed to solve: server message: insufficient_scope: authorization failed Error: buildx failed with: error: failed to solve: server message: insufficient_scope: authorization failed

**Comment by crazy-max** [comment]
Please create a proper [bug report](https://github.com/docker/build-push-action/issues/new?assignees=&labels=&template=bug_report.md)

**Comment by newconceptconsulting** [comment]
ok
