### ISSUE TITLE
buildx failed with: error: failed to solve: server message: insufficient_scope: authorization failed

### ISSUE THREAD

**Issue by Zak4sad** [docker/build-push-action#588]
### Troubleshooting

<img width="946" alt="image" src="https://user-images.githubusercontent.com/20495839/161788718-5c3f8bbc-c10f-4a00-b85a-dd27b3ef0c70.png">

#### Steps to reproduce this issue

1. Created my pipeline
2. Used already existing buildx images ( and build one by myself )
3. login to my docker registry
4. trying to push the image with multiple architectures

#### Expected behaviour
Image pushed successfully to my docker hub repo
> Tell us what should happen
Image pushed successfully to my docker hub repo
#### Actual behaviour
error: failed to solve: server message: insufficient_scope: authorization failed
> Tell us what happens instead
error: failed to solve: server message: insufficient_scope: authorization failed

**Comment by crazy-max** [comment]
Looks like auth/perm issue. Can you post your workflow please?
