### ISSUE TITLE
Question: how do I know what buildkit version the action is using?

### ISSUE THREAD

**Issue by inductor** [docker/build-push-action#591]
Hello. I'd like to use Dockerfile's new feature (1.4) but I don't know if I can do it with this action or not.

How can I know the BuildKit version this action is using?

**Comment by crazy-max** [comment]
@inductor If you're using the [`setup-buildx-action` action](https://github.com/docker/setup-buildx-action) along with this one, you can see the BuildKit version being used in the logs:

![setup-buildx-action](https://user-images.githubusercontent.com/1951866/162498630-aba12b2e-648d-4543-bacc-37d1e56a15e1.png)

If you're not using the `setup-buildx-action` then it will use the BuildKit backend in the Docker engine. In current Docker engine version (20.10.14), it's an old BuildKit version embedded (~v0.8.3) atm so I suggest to add `setup-buildx-action` in your workflow to have an up to date version of BuildKit (v0.10.1 atm).

Also if you want to use latest features of the Dockerfile frontend, you can add on top of your Dockerfile the `# syntax=docker/dockerfile:1` comment. More info: https://docs.docker.com/engine/reference/builder/#syntax

**Comment by inductor** [comment]
Ah. I'm using the setup action. Thanks for the quick answer!
