### ISSUE TITLE
Where is the source code of this action?

### ISSUE THREAD

**Issue by kwladyka** [docker/build-push-action#61]
Sorry, I am probably blind but I can't find the source code of this action. Where is it? For example where is code for `tag_with_ref` tags add? It would be nice to link to this in README.md.

**Comment by rikimaru0345** [comment]
https://github.com/docker/github-actions

https://github.com/docker/github-actions/blob/826b584752ffa6abc1a2d94da26f348e3e4f73d0/internal/options/tag.go#L15

:)
