### ISSUE TITLE
How to use the GitHub cache feature with a strategy matrix?

### ISSUE THREAD

**Issue by toast-gear** [docker/build-push-action#624]
https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache

Is it possible to use the GitHub cache feature when building multiple images from a strategy? The behaviour I'm seeing is the cache only works for 1 job only. I would think you'd need to be able to define a cache key as part of the `build-push-action` cache configuration which isn't possible atm. Would this require an enhancement to the action to support?

**Comment by toast-gear** [comment]
The linked issue (https://github.com/moby/buildkit/issues/2885) contains the solution, perhaps the docs could do with pointing out a key can be defined, perhaps though that's best in documented in buildkit repo. I'll leave it up to the maintainers to decide.

**Comment by crazy-max** [comment]
Sorry forgot to leave a comment here, will see how we can enhance our docs about the scope attribute. Btw left a comment in your PR: https://github.com/actions-runner-controller/actions-runner-controller/pull/1484
