### ISSUE TITLE
allow cache-to to fail nicely

### ISSUE THREAD

**Issue by tisdall** [docker/build-push-action#632]
There's currently a service disruption for `gha` which is preventing `build-push-action` from completing on the `cache-to` stage.  Ideally, if a cache fails to function then the action should just work the same as if no cache was used.  However, I don't know if this is something that can be solved on this level or would have to be altered in `buildx`.

Here's what's happening on `cache-from`:
```
#5 importing cache manifest from gha:123123123123123
#5 ERROR: GitHub Actions is temporarily unavailable. Please visit https://www.githubstatus.com/ for the status of our services.
```

And on `cache-to`:
```
#18 exporting cache
#18 preparing build cache for export 0.0s done
#18 ERROR: GitHub Actions is temporarily unavailable. Please visit https://www.githubstatus.com/ for the status of our services.
------
 > importing cache manifest from gha:123123123123123:
------
------
 > exporting cache:
------
error: failed to solve: GitHub Actions is temporarily unavailable. Please visit https://www.githubstatus.com/ for the status of our services.
Error: buildx failed with: error: failed to solve: GitHub Actions is temporarily unavailable. Please visit https://www.githubstatus.com/ for the status of our services.
```

The error on `cache-to` is failing the whole action.  Is it possible to have this output as a warning instead? (similar to how `cache-from` only gave a warning)

Here's the configuration I'm using for this step:
```yml
      - name: Build Docker Container
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
```

**Comment by crazy-max** [comment]
Yes this is already being addressed upstream. See https://github.com/moby/buildkit/issues/2836
