### ISSUE TITLE
Marketplace page links

### ISSUE THREAD

**Issue by the-matt-morris** [docker/build-push-action#636]
Links under the [advanced usage](https://github.com/marketplace/actions/build-and-push-docker-images#advanced-usage) section of the Marketplace page direct to a missing location.  The links from the README work fine, but this page directs them to a missing page.

For example: [Multi-platform image](https://github.com/docker/build-push-action/blob/docs/advanced/multi-platform.md) directs to `https://github.com/docker/build-push-action/blob/docs/advanced/multi-platform.md`, rather than `https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md`.

**Comment by crazy-max** [comment]
Page in marketplace is the README from this repo but looks like relative links are broken on the marketplace. This should be addressed to GitHub Staff though but thanks for pointing this out.

**Comment by crazy-max** [comment]
GitHub is working on a fix, thanks!

**Comment by the-matt-morris** [comment]
> GitHub is working on a fix, thanks!

Ah, got it...thanks!
