### ISSUE TITLE
Support arrays for tags and args

### ISSUE THREAD

**Issue by ptr727** [docker/build-push-action#648]
Building multiple containers using a matrix, and the matrix is JSON, the JSON contains all the build parameters, including tags and args as string arrays.  
Problem is that there is no easy way to convert from an array to a multi-line strings for use with args or tags.

The `join(array, '\n')` does [not work](https://github.community/t/how-to-convert-json-string-array-to-multiple-strings/260525/4) as it uses the literal `\n` not a newline character.
The value then needs to be set in a different build step using e.g. `join(',')` and `tr` to replace the `,` with a `\n`.
```
JArgs="${{ join(matrix.containers.args, ',') }}"
JArgs="$(echo "$JArgs" | tr ',' '\n')"
```

Problem is that newlines are [not transferred](https://github.community/t/set-output-truncates-multiline-strings/16852/2) between steps, and the string needs to be encoded.
```
MLArgs="${MLArgs//'%'/'%25'}"
MLArgs="${MLArgs//$'\n'/'%0A'}"
MLArgs="${MLArgs//$'\r'/'%0D'}"
```

Alternative is to use a unescaped newline in the join, not pretty, but works:
```
tags: |-
            ${{ join(matrix.containers.tags, '
            ') }}
```

This is all very cumbersome, and it would be much easier if arrays were supported for tags and args. (or `join()` fixed)

Please add support for array types vs. just multiline string types for tags and args.

**Comment by zackartz** [comment]
:+1: please do this

**Comment by crazy-max** [comment]
`tags` input is already a comma or newline delimited string: https://github.com/docker/build-push-action#inputs. We are actively using this with the metadata-action if yo uwant to take a look: https://github.com/docker/metadata-action#basic. Also not possible to be a comma-delimited string for `build-args` as values could not be parsed properly.
