### ISSUE TITLE
Allow multi platform build to be sequential

### ISSUE THREAD

**Issue by mesudip** [docker/build-push-action#654]
It's already reported in #621 that the multi platform build fails with OutOfMemory error.

I noticed on the log that the build for both platform is running in parallel 
```
#11 [linux/amd64 cabaldependency 4/5] RUN cabal update
#11 80.82 HEAD is now at a65c29b6a Merge #3801
#11 81.27 Cloning into '/app/dist-newstyle/src/project-3b55de0732f6b166'...
#11 ...
#14 [linux/arm64 cabaldependency 4/5] RUN cabal update
#14 77.43 HEAD is now at 7497a29 Rename forked package
#14 77.62 Cloning into '/app/dist-newstyle/src/ouroboros_-268d3b2310e5b441'...
#14 ...
```

I tried configuring  [jobs.<job_id>.strategy.max-parallel](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymax-parallel) but it has no effect.

build-push-action should either respect it or make it possible to set the parallelism for build

**Comment by gitlawr** [comment]
It is configurable in `docker/setup-buildx-action`
Ref: https://github.com/docker/setup-buildx-action/blob/master/docs/advanced/buildkit-config.md
Example:
```
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2
        with:
          config-inline: |
            [worker.oci]
              max-parallelism = 1
```
