### ISSUE TITLE
Cannot access image locally

### ISSUE THREAD

**Issue by pmantica3** [docker/build-push-action#664]
### Behaviour

Cannot access image locally after building it. Exactly the same issue as https://github.com/orgs/community/discussions/26723

#### Steps to reproduce this issue

  - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ env.IMAGE_URI }}
          cache-from: type=gha
          cache-to: type=gha
      - name: CI
        run: >
            docker run ${{ env.IMAGE_URI }} /bin/bash

#### Error 

Unable to find image '***.dkr.ecr.us-east-2.amazonaws.com/theiablockchain:ec6bf46f8a894d7fe760696cc543cfa9eac61da4' locally

**Comment by jedevc** [comment]
This seems similar to https://github.com/moby/buildkit/issues/2343, where we already have a lot of discussion around this.

You might also be interested in https://github.com/docker/buildx/blob/master/docs/guides/bake/build-contexts.md#using-a-result-of-one-target-as-a-base-image-in-another-target for how you can solve this using buildx bake target context overrides.

Additionally, the next release of buildkit will likely include https://github.com/moby/buildkit/pull/2827 which might help solve some of the use cases.

Going to close this for now, but if the above issues/solutions don't describe your setup at all, then feel free to re-open :tada:
