### ISSUE TITLE
docs question

### ISSUE THREAD

**Issue by artemijspavlovs** [docker/build-push-action#678]
The [original README](https://github.com/docker/build-push-action#git-context) mentions that 

> By default, this action uses the [Git context](https://github.com/docker/build-push-action#git-context) so you don't need to use the [actions/checkout](https://github.com/actions/checkout/) action to check out the repository because this will be done directly by [BuildKit](https://github.com/moby/buildkit).

The [multi-platform support example](https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md) uses the checkout action as the first step.

Is there a typo in one of these statements/examples or that's intentional

**Comment by Axedyson** [comment]
Pretty sure it works without using the git checkout action, so yes, I think it's a mistake that the checkout action is in use in that example, but I could be wrong though

**Comment by crazy-max** [comment]
Not intentional, just an example but it will also work using a Git context.

Closing this issue since that should answer your question, but feel free to re-open if it doesn't. Thanks.
