### ISSUE TITLE
Always_pull has no effect

### ISSUE THREAD

**Issue by paullaffitte** [docker/build-push-action#68]
The title is quite straightforward, always_pull doesn't "pull a newer version of the image". It actually seems to do nothing more, which is quite annoying since it means that I have to use another action to [pull the image first](https://github.com/docker/build-push-action/issues/50#issuecomment-634960705) to enable caching.

**Comment by tonistiigi** [comment]
`always_pull` means base images are pulled instead of using `docker images`. `--cache-from` only pulls images when BuildKit is used. https://docs.docker.com/engine/reference/commandline/build/#specifying-external-cache-sources
