### ISSUE TITLE
question: How can an image be squashed before pushing it?

### ISSUE THREAD

**Issue by T145** [docker/build-push-action#683]
It seems like this should be feasible due to the ["Test before push"](https://github.com/docker/build-push-action/blob/master/docs/advanced/test-before-push.md) example. I'd like to run something like the following between the initial build step and the push step:
```bash
docker run --name tmp ${{ env.DOCKER_TAG }}
docker image save tmp | docker import - ghcr.io/${{ env.DOCKER_TAG }}
docker container stop tmp
docker container rm tmp
```

**Comment by crazy-max** [comment]
Not yet supported, see tracking issue here: https://github.com/moby/buildkit/issues/819

Closing this issue since that should answer your question, but feel free to re-open if it doesn't. Thanks.
