### ISSUE TITLE
build-args doesn't resolve env vars

### ISSUE THREAD

**Issue by Craig1f** [docker/build-push-action#684]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

### Behaviour

I need to pass a build-arg that is set dynamically.

#### Steps to reproduce this issue. Current behavior

      - name: Set BUILD_DATE
        run: echo "BUILD_DATE=$(date '+%Y%m%d')" >> $GITHUB_ENV

      - name: Build and push with caching
        uses: docker/build-push-action@v3
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: example
          IMAGE_TAG: pr-${{ github.event.number }}
          HELP_DESK_EMAIL_ADDRESS: fake@fake.fake
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.login-ecr.outputs.registry }}/${ECR_REPOSITORY}:isolated-pr-${{ github.event.number }}
          target: serve-isolated
          build-args: |
            BUILD_DATE=${BUILD_DATE}
            HELP_DESK_EMAIL_ADDRESS="${HELP_DESK_EMAIL_ADDRESS"}

#### Expected behaviour

Expected Behavior: ENV VARs set in GitHub Actions should resolve in build-args

#### Actual behaviour

Result: Build date is equal to "${BUILD_DATE}" instead of being resolved into the value I set up in the previous action. Same issue happens with help desk email.

**Comment by crazy-max** [comment]
Syntax does not look correct, should be:

```yaml
      build-args: |
        BUILD_DATE=${{ env.BUILD_DATE }}
        HELP_DESK_EMAIL_ADDRESS=${{ env.HELP_DESK_EMAIL_ADDRESS}}
```

Closing this issue since that should answer your question, but feel free to re-open if it doesn't. Thanks.

**Comment by Craig1f** [comment]
Thanks @crazy-max . I did not see an example anywhere that uses that syntax, however I was about to also close this ticket with the following example that solved my problem: 

``` yaml
          build-args: |
            BUILD_DATE
            HELP_DESK_EMAIL_ADDRESS
```

With this syntax, the normal `docker build` behavior of pulling build-args from the environment is applied and works, IF the build-arg and env var have identical names.

**Comment by crazy-max** [comment]
Yes that also works!
