### ISSUE TITLE
Please explain when to use which type of cache

### ISSUE THREAD

**Issue by KonradHoeffner** [docker/build-push-action#686]
https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md lists several mutually exclusive (?) different methods for caching but I am not sure when to use which of those methods. I would appreciate a few lines of documentation on when I should use which of those methods.

**Comment by jedevc** [comment]
Good call out - we're actually working on a rework of our cache docs across buildkit/buildx/actions repos.

It'll be good to get some more info on the available cache methods and how to use them in actions, as well as update to include information on the upcoming s3 cache.

**Comment by pantelis-karamolegkos** [comment]
That would be extremely useful since I wasn't able either to figure out which cache to use when by reading the guide.

**Comment by jedevc** [comment]
Closing this to track in https://github.com/docker/buildx/pull/1316 and https://github.com/docker/docker.github.io/pull/15603.
