### ISSUE TITLE
raise `ghcr unexpected status: 403 Forbidden` when push ghcr image

### ISSUE THREAD

**Issue by Yikun** [docker/build-push-action#687]
### Behaviour
We didn't change any configuration before and after this error happened, same ghcr container image had permisson issue.

#### Expected behaviour

push successfully

#### Actual behaviour

```
#33 [auth] yikun/apache-spark-ci-image:pull,push token for ghcr.io
#33 DONE 0.0s

#32 exporting to image
#32 ...

#34 [auth] apache/spark/apache-spark-github-action-image-cache:pull yikun/apache-spark-ci-image:pull,push token for ghcr.io
#34 DONE 0.0s

#32 exporting to image
#32 pushing layers 1.5s done
#32 ERROR: unexpected status: 403 Forbidden
------
 > exporting to image:
------
ERROR: failed to solve: unexpected status: 403 Forbidden
Error: buildx failed with: ERROR: failed to solve: unexpected status: 403 Forbidden
```

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
# paste your YAML workflow file here and remove sensitive data
```

### Logs

https://github.com/Yikun/spark/runs/8221889583?check_suite_focus=true

**Comment by Yikun** [comment]
same issue are also happend in different developers:

- https://github.com/grundprinzip/spark/runs/8220478349?check_suite_focus=true
- https://github.com/panbingkun/spark/runs/8221478433?check_suite_focus=true

**Comment by Yikun** [comment]
https://github.com/apache/spark/pull/37745#issuecomment-1234067056

We can confirm that:
https://user-images.githubusercontent.com/1736354/187890839-2f26ce10-2e20-4d7e-ab6e-311c898fc416.png

and

https://user-images.githubusercontent.com/9700541/187891526-5938feb5-d380-4574-a81a-9b621779dead.png

and

https://user-images.githubusercontent.com/1736354/187893383-37752514-c9be-4f3b-bb53-a3f8cdc3e25c.png

We can only recover this by create a new image.

**Comment by Yikun** [comment]
OK....Related incidents: https://www.githubstatus.com/incidents/d181frs643d4

**Comment by Yikun** [comment]
After incidents is resolved, it worked as expected again.

Let me close this issue.

**Comment by Yikun** [comment]
@crazy-max this issue happened again....

**Comment by cyclinder** [comment]
Same issue for me..

**Comment by Yikun** [comment]
https://github.com/orgs/community/discussions/32184 also mentioned it

**Comment by ErikJiang** [comment]
😂I've been tormented by this problem for two days.
![image](https://user-images.githubusercontent.com/10629406/189043975-a4f01389-aef7-4992-85b6-990bb58b2770.png)

**Comment by f-strieg** [comment]
I'm working on a monorepo and I get the same error for 1 out of 3 identical workflows. Individual re-running the failed job doesn't help either.

**Comment by crazy-max** [comment]
Sorry but we can't do much about it as it's related to GitHub infrastructure. Same as https://github.com/docker/build-push-action/issues/651. Suggest to contact GitHub.

**Comment by rewlad** [comment]
For me, relinking package to repo has fixed 403:

https://github.com/orgs/community/discussions/26274#discussioncomment-3251137

**Comment by Anmol1696** [comment]
Facing this issue again. Is there no fix for this?

**Comment by mneira10** [comment]
Same here

**Comment by Anmol1696** [comment]
Retry seems to work, but this still should be solved properly.

**Comment by BenedekKoncz** [comment]
same here with `docker/build-push-action@v4`

**Comment by dhedegaard-digisense** [comment]
What seem to solve it for me is adding an explicit permissions section to the workflow yml file:

```yml
    permissions:
      contents: read
      packages: write
```

Hope this helps someone else out there 😅

**Comment by RamziRebai** [comment]
> What seem to solve it for me is adding an explicit permissions section to the workflow yml file:
> 
> ```yaml
>     permissions:
>       contents: read
>       packages: write
> ```
> 
> Hope this helps someone else out there 😅

Thank you very much, It's worked for me

**Comment by RamziRebai** [comment]
It's working fine with me, I hope it will work you guys
This is buildx.yaml file (You don't need to change anything)

name: BuildX


# This is a basic workflow to help you get started with Action

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile

and this is my repository : https://github.com/RamziRebai/CI-CD_with_fastapi_HF_Translator

**Comment by louisnow** [comment]
None of the aforementioned fixes worked for me.

However, what did work was disabling logout from the docker login action as mentioned here, https://news.ycombinator.com/item?id=28607735

```
      - name: Login to GitHub Registry
        uses: docker/login-action@v3
        with:
          logout: false
```

It turns out that the issue isn't with GHCR, permissions, etc, it's solely with the action logging us out before the image is pushed.

**Comment by crazy-max** [comment]
> It turns out that the issue isn't with GHCR, permissions, etc, it's solely with the action logging us out before the image is pushed.

Logout is done at post step of the pipeline not between so it should not be the issue you encounter. OTOH if you're using a self-hosted runner, see https://github.com/docker/login-action/issues/173#issuecomment-1079688020.
