### ISSUE TITLE
Use gha cache exporter on pull requests ?

### ISSUE THREAD

**Issue by jooola** [docker/build-push-action#688]
I was wondering if it is safe to use the gha cache exporter when running the build workflow for pull_request events as well ?

Is it a different cache location for pull requests ? Is there any way to pollute the cache from a fork ?

https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#cache-backend-api

**Comment by crazy-max** [comment]
@jooola 

> I was wondering if it is safe to use the gha cache exporter when running the build workflow for pull_request events as well ?

Yes. Restrictions on cache access are the same as GitHub currently provides: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache

> Is it a different cache location for pull requests

Cache is scoped to the pull request when exported. It also imports cache from head ref if available.
