### ISSUE TITLE
how to use existing image without Dockerfile

### ISSUE THREAD

**Issue by rodrigorodrigues** [docker/build-push-action#692]
Hi all,

I was wondering if it's possible to build a new image for different platform(`arm64`) based on existing `amd64 image` without Dockerfile?

It works already using maven plugin(`fabric8 docker:build`) with Dockerfile but would be nice to use `spring-boot:build-image` the problem is the second one use packetobuild but only has amd64.

Github action working with docker:build

https://github.com/rodrigorodrigues/microservices-design-patterns/actions/runs/3118222069/workflow#L56-L75

Docker image but with spring boot/packeto https://hub.docker.com/layers/fielcapao/microservices-design-patterns-authentication-service/0.0.1-SNAPSHOT/images/sha256-05697477be820bb8102754ad795c218900299947f9b27675a8de9c7b2850ef67?context=repo

**Comment by crazy-max** [comment]
> I was wondering if it's possible to build a new image for different platform(`arm64`) based on existing `amd64 image` without Dockerfile?

You need a Dockerfile to build. Not sure I understand what you mean.

If the base image doesn't support the target platform it will not have the expected outcome when run. Also I can't find `./authentication-service/target/docker/authentication-service/build/Dockerfile` that is being used [in your workflow](https://github.com/rodrigorodrigues/microservices-design-patterns/actions/runs/3118222069/workflow#L72).

> but would be nice to use spring-boot:build-image the problem is the second one use packetobuild but only has amd64.

Looking at the workflow, [you're using the `setup-buildx` action](https://github.com/rodrigorodrigues/microservices-design-patterns/actions/runs/3118222069/workflow#L45-L47) to create a `docker-container` builder.

If you want to use a built image in another build while using a `docker-container` builder, you can use a named context to load an image from a previous build. See https://github.com/docker/build-push-action/blob/master/docs/advanced/named-contexts.md for more info.

**Comment by rodrigorodrigues** [comment]
Thanks @crazy-max, the Dockerfile is generated automatic by docker:build(fabric8 plugin) but spring-boot:build-image doesn't generate this file, closing this ticket now.
