### ISSUE TITLE
Add capability tuning

### ISSUE THREAD

**Issue by ZackaryWelch** [docker/build-push-action#717]
Is there any way to run the equivalent of `--add-cap` or `--drop-cap` as you can through CLI `docker build`? Apart from using docker compose instead, which might be the only way right now.

**Comment by crazy-max** [comment]
We don't but you can set entitlements when creating a builder through `buildkitd-flags` input in `setup-buildx-action` or the BuildKit configuration.

If you can explain a bit more your use case and what kind of limitations you encounter when building, that would help.
