### ISSUE TITLE
Support Build Flags

### ISSUE THREAD

**Issue by coreybutler** [docker/build-push-action#72]
There doesn't appear to be a means of passing build flags. For example, `docker build -t whatever . --no-cache` doesn't seem to be possible right now.

**Comment by crazy-max** [comment]
@coreybutler All necessary build args will be available through [build-push-action v2](https://github.com/docker/build-push-action/tree/v2-build-push) (#92). You can already try it with:

* https://github.com/docker/setup-buildx-action
* https://github.com/docker/setup-qemu-action
* https://github.com/docker/login-action

**Comment by coreybutler** [comment]
Thanks @crazy-max!
