### ISSUE TITLE
Node 16 upgrade

### ISSUE THREAD

**Issue by ejgutierrezvega** [docker/build-push-action#724]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

### Behaviour
We are receiving warnings from Github actions about node 12 would be deprecated and that this action is still using it Node 12 version.

`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: docker/build-push-action@v2
`

#### Steps to reproduce this issue
N/A

#### Expected behaviour
Upgrade the Github action to node 16 before it is deprecated/not supported

> Tell us what should happen

#### Actual behaviour

> Tell us what happens instead

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
# paste your YAML workflow file here and remove sensitive data
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs) and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

**Comment by crazy-max** [comment]
Update your workflow to use `docker/build-push-action@v3`.

**Comment by nikp123** [comment]
This is not reflected in the README or any other documentation I've found so far. Please fix this. Thanks in advance.

**Comment by crazy-max** [comment]
@nikp123 

* https://github.com/docker/build-push-action/releases/tag/v3.0.0
* https://github.com/docker/build-push-action/blob/37abcedcc1da61a57767b7588cb9d03eb57e28b3/action.yml#L115

**Comment by nikp123** [comment]
Apologies, I've missed it by accident it seems.
