### ISSUE TITLE
unable to prepare context... where should I put the Dockerfile?

### ISSUE THREAD

**Issue by sir-farfan** [docker/build-push-action#73]
Sorry if this isn't the right place to ask, I don't see any other (official) help resources for this.

I'm getting this error from github which sounds like the "action" isn't finding the Dockerfile, currently I have it in the root of the project, is it expecting it in a different place?
```
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /github/workspace/Dockerfile: no such file or directory
Error: exit status 1
Usage:
  github-actions build-push [flags]
Flags:
  -h, --help   help for build-push
Building image
```

A full working hello world example would be really useful here to complement all those bits of code that doesn't do anything on their own and you have to "just know" where to put them.

**Comment by rcorrear** [comment]
Getting the same, I have a Dockerfile at the root of the repository, a README and the .github folder, nothing else. Tried playing a bit with path but didn't figure it out that way either.

**Comment by sir-farfan** [comment]
Finally got it working, now I have something in the registry, notice that I was missing the **checout@v2** action that isn't mentioned anywhere at all in the documentation:
```
$ cat .github/workflows/docker.yml 
on: [push, pull_request]

name: Docker

jobs:
  docker:
    name: Build and push to registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: account/tag
          tag_with_sha: true
```

**Comment by tonistiigi** [comment]
Assuming @rcorrear had the same issue. Feel free to do pr to improve the docs.

**Comment by rcorrear** [comment]
That was it for me as well, thanks!
