### ISSUE TITLE
GHA backend: Use cache from base branch

### ISSUE THREAD

**Issue by aerlaut** [docker/build-push-action#731]
The documentation states, that build cache is scoped [per branch](https://docs.docker.com/build/building/cache/backends/gha/#scope) by default. However, [cache from the default branch and base branch is accessible to the workflow branch](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache).

I'd like to store the build cache on the default branch, and then use this cache on branches based on it. 

Does the GHA backend provide an easy way to do this? If not, what is the recommended way to do this?

**Comment by crazy-max** [comment]
This is already the case like [actions/cache](https://github.com/actions/cache). Caches are [scoped by branch](https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache), with the default and target branches being available to every branch.

Scopes are provided through a JWT token `ACTIONS_RUNTIME_TOKEN` set by GitHub and is associated with repository scopes that can be readwrite or readonly (e.g., PR has write access to its own scope but readonly access to the target branch scope).
