### ISSUE TITLE
Action fails to build images for ARM-platform

### ISSUE THREAD

**Issue by m-genser** [docker/build-push-action#748]
After switching from 

     FROM alpine:3.16

to 

     FROM arm64v8/alpine:3.16

the **docker/build-push-action@v3** start to fail with the following error:

_**`Error: buildx failed with: ERROR: failed to solve: executor failed running [/bin/sh -c apk update]: exit code: 1`**_

It seams that for some reason BuildX can't access the bourne shell in ARM base images. The apk command is not the problem here. The first RUN command in the dockerfile always fails because of the shell.
      
On Docker-Desktop both Dockerfiles builds without any errors.

**Comment by crazy-max** [comment]
Please provide your workflow and full logs so we can repro. But I guess you're missing the `setup-qemu-action` step: https://github.com/docker/setup-qemu-action#usage

**Comment by m-genser** [comment]
As already described, the Dockerfile doesn't matter. Once you switch to an ARM Base image, every (the first) CMD in the Dockerfile fails.

I just created a bare-minimum test repo were you can see and reproduce the error: [https://github.com/m-genser/react-interface-test](https://github.com/m-genser/react-interface-test)

**Comment by m-genser** [comment]
Yes, you're right. The problem was that I haven't sertup the virtualizer.

Thanks a lot!
