### ISSUE TITLE
Rename input 'file' to 'dockerfile'

### ISSUE THREAD

**Issue by ricardo-dematos** [docker/build-push-action#752]
Renaming input named '`file`' to '`dockerfile`' would be more in line with what it holds, hence my request/suggestion.

**Comment by crazy-max** [comment]
Same as https://github.com/docker/build-push-action/issues/753#issuecomment-1508443133, we want our inputs to be as close as possible of buildx build flags: https://docs.docker.com/engine/reference/commandline/buildx_build/#options
