### ISSUE TITLE
Getting "no such manifest" since provenance was added

### ISSUE THREAD

**Issue by ddelange** [docker/build-push-action#764]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

### Behaviour

- workflow file [in the left column](https://github.com/ddelange/actions-runner-controller-releases/actions/runs/3939568621/jobs/6739577887#step:7:134)
- recently added by default: `--provenance mode=max,builder-id=https://github.com/***/actions-runner-controller-releases/actions/runs/3939568621`
- the manifest now seems broken
  ```console
  $ docker manifest inspect ddelange/actions-runner:latest
  no such manifest: docker.io/ddelange/actions-runner:latest
  $ docker manifest inspect ghcr.io/ddelange/actions-runner-controller-releases/actions-runner:latest
  no such manifest: ghcr.io/ddelange/actions-runner-controller-releases/actions-runner:latest
  ```
- it also causes a third OS/Arch to show up on ghcr.io (on hub.docker.com it is hidden) with sha corresponding to `exporting attestation manifest ...`
  <img width="300" alt="image" src="https://user-images.githubusercontent.com/14880945/212919145-2c9fa733-30aa-4fdf-9a86-aa926f24ee9c.png">
- when I set `provenance: false` (I'm running v3.3.0), the manifests are fixed

#### Steps to reproduce this issue

workflow linked above

#### Expected behaviour

i expect the manifests on docker.io and ghcr.io not to be broken (or it should be a v4 bump or so and fixed differently? should I update docker cli?)

#### Actual behaviour

manifests broken, see above

### Configuration

* Repository URL (if public): https://github.com/ddelange/actions-runner-controller-releases
* Build URL (if public): https://github.com/ddelange/actions-runner-controller-releases/actions/runs/3939568621/jobs/6739577887#step:7:134
* YAML https://github.com/ddelange/actions-runner-controller-releases/blob/b4691d61c3d4a5d8a05cff2e4c2ed2c9e8afaf96/.github/workflows/release-runners.yaml

### Logs

[logs_14.zip](https://github.com/docker/build-push-action/files/10435890/logs_14.zip)

**Comment by crazy-max** [comment]
This is expected. See https://github.com/docker/buildx/issues/1509#issuecomment-1378454396 and also https://github.com/docker/buildx/issues/1509#issuecomment-1378538197 for more context.

**Comment by ddelange** [comment]
Hi @crazy-max 👋 thanks for the quick reply!

do I understand correctly this change ships with buildx 0.10.0 ([included](https://docs.docker.com/desktop/release-notes/#4160) in docker desktop 4.16.0)?

will `docker manifest inspect` work again if I were able to upgrade Docker Deskop? (need to upgrade MacOS to v11+ first...)

**Comment by ddelange** [comment]
looks like `docker buildx imagetools inspect` misses a verbosity flag, so I can't use it as a replacement for `docker manifest inspect -v` to sum up layer sizes: https://stackoverflow.com/a/73108928/5511061

**Comment by billinghamj** [comment]
@crazy-max Could I suggest a pinned issue in this repo, to help people find the buildx issue?
