### ISSUE TITLE
docker/build-push-action@v4 Building and pushing image with 0mb

### ISSUE THREAD

**Issue by ahamroun10** [docker/build-push-action#801]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

#### Steps to reproduce this issue

1.
2.
3.

#### Expected behaviour

> Tell us what should happen

#### Actual behaviour

> Tell us what happens instead

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
# paste your YAML workflow file here and remove sensitive data
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs) and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

**Comment by jedevc** [comment]
Without further information, I'd guess that this is the provenance attestation generated by build-push-action@v4 using buildx.

See https://github.com/docker/build-push-action/issues/771 for more information :tada:

I'll close this for now, as it's duplicate issue of the above issue, but feel free to re-open if you can't find the information you need there :smile:
