### ISSUE TITLE
Documentation for subsequent build steps remains unclear 

### ISSUE THREAD

**Issue by daixtrose** [docker/build-push-action#808]
#### Steps to reproduce this issue

Read [the docs](https://docs.docker.com/build/ci/github-actions/examples/#use-image-in-subsequent-steps) and try to make sense out of it.

#### Expected behaviour

Docs should provide a **complete**, working example.

There are parts in the example that could be omitted and rather completely distract from the relevant thing:

```
with:
     context: base
```

is followed by 

```
with:
     context: .
```

And IIUC `context` is completely irrelevant in this case. The key point seems to be somehow `load: true` for the build of the base image and `build-contexts: alpine=docker-image://my-base-image:latest` for the subsequent build. Or even stricter: the prefix `docker-image://` is intended to somehow dictate local search. Still not sure if that is the key point.

#### Actual behaviour

I am [struggling to wrap my head around the example](https://github.com/docker/build-push-action/issues/807#issuecomment-1433108511). The builds [still fail](https://github.com/daixtrose/how-to-use-docker-for-copperspice/actions/runs/4194534099/jobs/7272826529#step:10:130) 

### Logs

None.

**Comment by daixtrose** [comment]
Also, please note that due to flaws in the search engine of the documentation site searching for `build-contexts` yields [everything about `build context`](https://docs.docker.com/search/?q=%22build-contexts%22), not `build-contexts`. And yeah, 

![image](https://user-images.githubusercontent.com/5588692/219386640-cfc4e295-2325-435f-a6a0-9c617da55aae.png)

**Comment by daixtrose** [comment]
On a side note: For first-time users, this is no fun:

![image](https://user-images.githubusercontent.com/5588692/219388464-880e47ad-d839-4a9d-8b17-0ee9cd70ed4e.png)
![image](https://user-images.githubusercontent.com/5588692/219389306-ab9ed9a2-e659-4c54-889a-707c0643e9df.png)

**Comment by jedevc** [comment]
@daixtrose thanks for your feedback :heart: 

These actions are open-source, so anyone can help out - would you be able to open a PR to help fix this up?

**Comment by daixtrose** [comment]
> would you be able to open a PR to help fix this up?

- Would you be able to first show me how it should work? See my struggles described in https://github.com/docker/build-push-action/issues/807.
- The sources for the docs have [vanished](https://github.com/docker/build-push-action/commit/d4c14fd0066c842daf6e6d5835f5f43a5eddd9ef), so I am very unsure how to contribute to "open" source.

**Comment by jedevc** [comment]
R.E. docs sources, they've moved to https://github.com/docker/docs/tree/main/build.

**Comment by crazy-max** [comment]
https://github.com/docker/build-push-action/issues/807#issuecomment-1442032795
