### ISSUE TITLE
what's the current directory?

### ISSUE THREAD

**Issue by jpmolinamatute** [docker/build-push-action#81]
Hello World,

awesome GitHub action! this is a lifesaver. I'm getting this error
```
unable to prepare context: path "ai-tools/airflow" not found
```
most likely is because I'm using a relative path and I'm missing a directory (or more)

any help would be appreciate it :-)

**Comment by crazy-max** [comment]
@jpmolinamatute Looks like the same issue as #90 and #51.

Fyi, this will be solved through [build-push-action v2](https://github.com/docker/build-push-action/tree/v2-build-push) (#92) as it's written as a typescript-action to be as closed as possible of the GitHub Runner during its execution. You can already try it with:

* https://github.com/docker/setup-buildx-action
* https://github.com/docker/setup-qemu-action
* https://github.com/docker/login-action

**Comment by crazy-max** [comment]
Version 2 has been [merged to the main branch](https://github.com/docker/build-push-action#readme) and is therefore available via `uses: docker/build-push-action@v2` (mutable tag).

As a reminder, this new version changes drastically and works with 3 new actions ([login](https://github.com/docker/login-action#readme), [setup-buildx](https://github.com/docker/setup-buildx-action#readme) and [setup-qemu](https://github.com/docker/setup-qemu-action#readme)) that we have created. Many [usage examples](https://github.com/docker/build-push-action#usage) have been added to handle most use cases.

And it should fix this current issue. Don't hesitate if you have any questions.

**Comment by ThisIsQasim** [comment]
@crazy-max I am still getting the same error on v2

**Comment by crazy-max** [comment]
@ThisIsQasim Can you create a new [bug report](https://github.com/docker/build-push-action/issues/new?template=bug_report.md) please? Thanks.

**Comment by ThisIsQasim** [comment]
I investigated further and found that it wasn't cloning the repo. So I added a separate checkout action before the docker build and that fixed it.

**Comment by crazy-max** [comment]
@ThisIsQasim 

> I can file a bug if not.

Yes please.

**Comment by ThisIsQasim** [comment]
@crazy-max https://github.com/docker/build-push-action/issues/120
