### ISSUE TITLE
Add distribution/distribution registry to e2e tests

### ISSUE THREAD

**Issue by jedevc** [docker/build-push-action#812]
Similar to #804 and #790 (and many others), we should add tests for the distribution/distribution registry as well: https://github.com/distribution/distribution/.

WDYT @crazy-max?

**Comment by crazy-max** [comment]
We have already this in our workflows actually like: https://github.com/docker/build-push-action/blob/7944f9a25be0279b7713908f16090a214db107ef/.github/workflows/ci.yml#L49-L53

But not in the `e2e` workflow. Fine to add a case in our matrix for this too :+1:
