### ISSUE TITLE
Feature Request: Give the option to only push a previously built docker image

### ISSUE THREAD

**Issue by cscetbon** [docker/build-push-action#825]
When a docker image is managed using a Makefile it's annoying to have to ensure we can rebuild it and get the exact same result using this Github Action just to push it.

I would love a way to prevent the build and only push it, maybe by having a push-only or a disable-build flag ?

**Comment by crazy-max** [comment]
https://docs.docker.com/build/ci/github-actions/test-before-push/ is what you're looking for. Last step will use the cache from BuildKit state and just push previously built image.

**Comment by cscetbon** [comment]
@crazy-max as far as I understand it still builds the image using the cache but that's not what I want. I have an image that is built using a Makefile and it uses extra env variables, local files that get removed after the build etc.. So if I try to rerun it using this action it doesn't work. I'd like to just say push image with tag x and just that.

**Comment by omerlh** [comment]
I am facing similar issues when using Bazel docker_rules to build the image and I am also looking for a potential solution 🙏
