### ISSUE TITLE
Publish the current tag not the "latest" name tag

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [docker/build-push-action#843]
Behaviour
I would like to push to docker the current tag not the "latest" name tag when a new release is done.

Steps to reproduce this issue
I have this github action:

publish_docker_images:
    needs: [update-version]
    runs-on: ubuntu-20.04
       
    if: github.ref == 'refs/heads/main' || github.event_name == 'release'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Docker meta
      id: meta
      uses: crazy-max/ghaction-docker-meta@v2
      with:
        images: phparkitect/arkitect-github-actions
        tags: |
          type=raw,value=latest,enable=${{ endsWith(github.ref, 'main') }}
          type=ref,event=tag
        flavor: |
          latest=false
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
Expected behaviour
I would like to see the actual tag in docker hub

Actual behaviour
In docker hub I can see only the "latest" tag

Configuration
Repository URL (if public): https://github.com/phparkitect/arkitect-github-actions
Build URL (if public): https://github.com/phparkitect/arkitect-github-actions/blob/main/.github/workflows/update_version.yml
publish_docker_images:
    needs: [update-version]
    runs-on: ubuntu-20.04
       
    if: github.ref == 'refs/heads/main' || github.event_name == 'release'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Docker meta
      id: meta
      uses: crazy-max/ghaction-docker-meta@v2
      with:
        images: phparkitect/arkitect-github-actions
        tags: |
          type=raw,value=latest,enable=${{ endsWith(github.ref, 'main') }}
          type=ref,event=tag
        flavor: |
          latest=false
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
Logs

**Comment by crazy-max** [comment]
Can you show your full workflow please?

```
if: github.ref == 'refs/heads/main' || github.event_name == 'release'
```

This condition will not work as a `release` event sets a tag ref when a release is created. Such as: https://github.com/docker/metadata-action/blob/master/__tests__/fixtures/event_release_created.env#L16

Also `crazy-max/ghaction-docker-meta@v2` is outdated for almost two years. Please use latest stable `docker/metadata-action@v4`. Other actions in your workflow look outdated too.

Closing in the meantime.
