### ISSUE TITLE
Self-hosted github runners fails on push of docker image

### ISSUE THREAD

**Issue by ShuAiii** [docker/build-push-action#847]
I'm trying to run a self-hosted runner on Windows for my private GitHub repository. My goal is to have the runner builds a Docker image, then push it to GHCR.

The runner is working properly, it is able to log into GHCR and build the image. But it fails on the last step, which is pushing the built image to GHCR.

The .yml and logs are contained in the following StackExchange post

https://stackoverflow.com/questions/75835798/github-action-docker-build-self-hosted-runner-fails-on-push-to-gh-registry

**Comment by crazy-max** [comment]
Looks to be related to https://www.githubstatus.com/incidents/x7njwb481j9b

**Comment by ShuAiii** [comment]
> Looks to be related to https://www.githubstatus.com/incidents/x7njwb481j9b

Hey, @crazy-max it says it's resolved. I'm still having the same issue!

**Comment by crazy-max** [comment]
> > Looks to be related to https://www.githubstatus.com/incidents/x7njwb481j9b
> 
> Hey, @crazy-max it says it's resolved. I'm still having the same issue!

I just run a build in our CI to make sure and looks good to push on GHCR: https://github.com/docker/build-push-action/actions/runs/4515565709/jobs/7952999725#step:11:404

It might be an issue with your self-hosted runner, I'm not sure.
