### ISSUE TITLE
Login validation must be ignored if push is false

### ISSUE THREAD

**Issue by felipecrs** [docker/build-push-action#85]
I want to run the action but not push if it is a pull request run. So:

```bash
      - name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          push: ${{ ! startsWith(github.ref, 'refs/pull/') }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_IMAGE }}
          dockerfile: docker/Dockerfile
          add_git_labels: true
          tags: ${{ env.DOCKER_TAGS }}
          tag_with_sha: true
```

It will produce the following error:

```log
Error: both username and password must be set to login
```

This is because `secrets.DOCKER_PASSWORD` is not set on pull request builds, so it's set to empty.

But the right behavior would be to skip the validation for these fields in case the `push: false`.

**Comment by tonistiigi** [comment]
Credentials are not only for pushes. Pulls may need it as well for private images and anonymous pulls get rate limited.

**Comment by felipecassiors** [comment]
True. So how about no login in case one of the two parameters is not set?

**Comment by crazy-max** [comment]
Version 2 has been [merged to the main branch](https://github.com/docker/build-push-action#readme) and is therefore available via `uses: docker/build-push-action@v2` (mutable tag).

As a reminder, this new version changes drastically and works with 3 new actions ([login](https://github.com/docker/login-action#readme), [setup-buildx](https://github.com/docker/setup-buildx-action#readme) and [setup-qemu](https://github.com/docker/setup-qemu-action#readme)) that we have created. Many [usage examples](https://github.com/docker/build-push-action#usage) have been added to handle most use cases.

And it should fix this current issue. Don't hesitate if you have any questions.
