### ISSUE TITLE
Quotation marks don't work in build-args

### ISSUE THREAD

**Issue by mallycrip** [docker/build-push-action#852]
### Troubleshooting

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

#### Steps to reproduce this issue
Below is the Docker file
```Dockerfile
FROM alpine
ARG TEMP
RUN printenv TEMP
...
```

And here is the action file.
```yaml
      ...
      - name: Get args
        id: get_args
        run: |
          STR=$(cat << EOF
          First line
          Second "line"
          "Third" "line"
          EOF
          )
          STR="${STR//'%'/'%25'}"
          STR="${STR//$'\n'/'%0A'}"
          STR="${STR//$'\r'/'%0D'}"
          echo "::set-output name=content::$STR"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          build-args: |
            "TEMP=${{ steps.get_args.outputs.content }}"
      ...
```

#### Expected behaviour
When building an image, all values including double quotes are passed as build-args arguments, and the value is printed correctly in the `RUN printenv TEMP` command.

#### Actual behaviour
After the double quotes, the `--build-arg` command was abnormally called again, and `RUN printenv TEMP` did not run because there was no value in TEMP.
<img width="677" alt="image" src="https://user-images.githubusercontent.com/44916755/229062621-9937b084-7c39-4058-bc6c-2fae109bdc01.png">
<img width="628" alt="image" src="https://user-images.githubusercontent.com/44916755/229063537-723fb311-af31-4013-b826-5d665a6188dc.png">

**Comment by mallycrip** [comment]
As additional information, it seems there is an issue with actions-toolkit.
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/44916755/229767508-705af3cf-05b1-43a4-975c-36adbafd34df.png">
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/44916755/229768180-ca34f974-4470-49f2-963f-cb0048076e88.png">

**Comment by crazy-max** [comment]
Thanks for taking time to debug.

> As additional information, it seems there is an issue with actions-toolkit.

We have test cases that look to cover multi-line value already: https://github.com/docker/build-push-action/blob/f2a1d5e99d037542a71f64918e516c093c6f3fc4/__tests__/context.test.ts#L85-L107

I don't see any issue with the result from your screenshots. Let me know what you expect from your tests.

> After the double quotes, the `--build-arg` command was abnormally called again, and `RUN printenv TEMP` did not run because there was no value in TEMP.
> <img alt="image" width="677" src="https://user-images.githubusercontent.com/44916755/229062621-9937b084-7c39-4058-bc6c-2fae109bdc01.png">
> <img alt="image" width="628" src="https://user-images.githubusercontent.com/44916755/229063537-723fb311-af31-4013-b826-5d665a6188dc.png">

If you have double quotes in a build-arg value, you need to escape them because this character is used to surround a field: https://csv.js.org/parse/options/quote/

What you can do for this case is just using an env var so you don't need to pass the build-arg value in the input:

```yaml
      ...
      - name: Get args
        id: get_args
        run: |
          STR=$(cat << EOF
          First line
          Second "line"
          "Third" "line"
          EOF
          )
          echo 'STR_TEMP<<EOF' >> $GITHUB_ENV
          echo $STR >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          build-args: |
            STR_TEMP
      ...
```

```dockerfile
FROM alpine
ARG TEMP
RUN printenv STR_TEMP
...
```

I'm closing this issue in the meantime but leave a comment if you think there is still an issue or if we can improve our documentation.
