### ISSUE TITLE
Better support annotations for OCI V1 or revert back to Docker V2?

### ISSUE THREAD

**Issue by favonia** [docker/build-push-action#854]
Around the start of this year, the manifest format (probably due to the usage of `docker buildx imagetools inspect`) was changed from Docker V2 to OCI V1, at least for multi-arch images. While the two standards are very similar, one critical difference is where the standardized labels/annotations such as `org.opencontainers.artifact.created` usually go. For Docker V2, they are probably labels, but for OCI V1, they are annotations. This discrepancy has caused issues noticed by others:

- https://github.com/docker/build-push-action/issues/447#issuecomment-1443897499
- https://github.com/docker/build-push-action/issues/747#issuecomment-1490070443

I thus wonder if we could somehow better support annotations, given that we are using OCI V1? (I understand this may involve changes to the underlying tools.) Otherwise, is it possible to revert to Docker V2 format? Thanks.

**Comment by jedevc** [comment]
Docker v2 only defines `labels` (though many implementations accept OCI-style `annotations` as well)

OCI v1 defines both `labels` on the config object, and defines `annotations` *almost everywhere*. `labels` and `annotations` are **not** exclusive, see the [OCI image-spec for more information](https://github.com/opencontainers/image-spec).

It is perfectly valid for built images to contain labels and annotations, and any combination of the two.

---

Switching the underlying tooling such as Buildkit to automatically convert labels to annotations is something I think we should avoid. Labels and annotations *are* different, and tooling may rely on the labels being present. It's also not at all clear which descriptor we'd attach these annotations to - the manifest annotations? the manifest descriptor annotations? the image config annotations? All of these sound like viable locations for the annotations (though I do suppose the manifest annotations has the strongest case).

---

> I thus wonder if we could somehow better support annotations

There's some discussion of this already in https://github.com/docker/buildx/issues/1171 - we've struggled to define a reasonable user interface for the flags, any help would be appreciated.

**Comment by jedevc** [comment]
@favonia is this issue ok to close in preference to https://github.com/docker/build-push-action/issues/958?

**Comment by favonia** [comment]
@jedevc I'm okay. I didn't close it because @jianlins seems to have another suggestion, but maybe we all should just create other more specific issues.
