### ISSUE TITLE
Can't push to ghcr on a pull request

### ISSUE THREAD

**Issue by localagi** [docker/build-push-action#870]
### Troubleshooting 

Before submitting a bug report please read the [Troubleshooting doc](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md).

=> Thanks, i added the debug flag

#### Steps to reproduce this issue

1. have a project with a docker build push action on the workflow
2. enable the runs on pull requests
3. have a pull request, the build push action fails with 403

#### Expected behaviour

The push works with the tag `:pr-123` into the target repository

#### Actual behaviour

Login into registry works with `${github.actor}`
Push should go to target repository, but fails.
`Error: buildx failed with: ERROR: failed to solve: failed to push ghcr.io/josh-xt/agixt:pr-499: unexpected status: 403 Forbidden`

### Configuration

https://github.com/Josh-XT/AGiXT/actions/runs/5111667183/jobs/9188888271?pr=499

https://github.com/Josh-XT/AGiXT/blob/main/.github/workflows/publish-docker.yml

https://github.com/localagi/AI-pipeline/blob/main/.github/workflows/operation-docker-build-publish.yml

[logs_2922.zip](https://github.com/docker/build-push-action/files/11591618/logs_2922.zip)

**Comment by vfiset** [comment]
setting [this](https://github.com/docker/buildx/issues/1613#issuecomment-1431335244) in the docker build env might help

**Comment by crazy-max** [comment]
> https://github.com/Josh-XT/AGiXT/actions/runs/5111667183/jobs/9188888271?pr=499

Don't think this is related but the build push action is not configured properly: https://github.com/Josh-XT/AGiXT/actions/runs/5111667183/jobs/9188888271?pr=499#step:15:1

![image](https://github.com/docker/build-push-action/assets/1951866/3e6285d1-ecec-4de1-ab59-49757c86ebf6)

`buildkitd-flags` does not exist in this action: https://github.com/localagi/AI-pipeline/blob/3007b9776a982006265c1fb85622248c86a6bd25/.github/workflows/operation-docker-build-publish.yml#L214

Should be done in setup-buildx-action: https://github.com/docker/setup-buildx-action#inputs

> The push works with the tag `:pr-123` into the target repository

Doesn't look possible from a public forked repo as stipulated in GitHub docs. See "Maximum access for pull requests from public forked repositories": https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token.
