### ISSUE TITLE
[Question] Running container before pushing

### ISSUE THREAD

**Issue by benmezger** [docker/build-push-action#89]
Is there anyway to execute my docker-entrypoint before pushing to registry? My `Dockerfile` build correctly, however, I need to run my entry-point to install any related dependency. Is there any easy way to achieve this with this action?

**Comment by crazy-max** [comment]
@benmezger The purpose of this action is to build and push Docker images. The execution of an image is out of scope but you could do something [like this](https://github.com/crazy-max/docker-cloudflared/blob/8a0ff9574ad8ed3d06bc3eda864d80c20b6e25b8/.github/workflows/test.yml#L44-L73).
