### ISSUE TITLE
Backwards compatibility

### ISSUE THREAD

**Issue by chrzanxq** [docker/build-push-action#899]
Any possibility to use older version of node? Using quasar 1 with the app, with no current possibility to upgrade it, and this github action fails since last release due to incompatibility between upgraded node and quasar.

**Comment by crazy-max** [comment]
> Any possibility to use older version of node?

I don't think so but you can downgrade to build-push-action v2. Although this version is not supported anymore and GitHub dropped support for Node 12: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

> Using quasar 1 with the app

Sorry I don't know what this means. I guess you install an older version of Node on the runner and therefore the action fails to execute. Can you post a repro with your workflow and Dockerfile?

I'm closing this one as we don't intend to add support for deprecated versions of Node.
