### ISSUE TITLE
Feature request: support for SOCI index

### ISSUE THREAD

**Issue by dannyibishev** [docker/build-push-action#907]
AWS have just announced a new open source feature for making docker images load faster. It would be great if support can be added for the build, and push stage of the action. 🙏 

- AWS Blog: https://aws.amazon.com/about-aws/whats-new/2023/07/aws-fargate-container-startup-seekable-oci/

- Getting started with the SOCI snapshot tool: https://github.com/awslabs/soci-snapshotter/blob/main/docs/getting-started.md

**Comment by crazy-max** [comment]
Can you open this issue on BuildKit repo instead please? Thanks.
