### ISSUE TITLE
cache image for different OS-Arch

### ISSUE THREAD

**Issue by ghost** [docker/build-push-action#916]
### Hi
I used `docker/build-push-action@2` to cache my docker images in github action cache. the problem arose when I use `ubuntu-latest` runner. but I want to create and cache linux/arm64 image.

- name: Cache Docker layers
  uses: actions/cache@v2
  with:
    path: /tmp/.buildx-cache
    key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
    restore-keys: |
      ${{ runner.os }}-multi-buildx

- name: Build production image
  uses: docker/build-push-action@v2
  with:
    context: .
    platform: linux/arm64
    builder: ${{ steps.buildx.outputs.name }}
    push: true
    tags: ${{ steps.prep.outputs.tagged_image }}
    cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

- name: Move cache
  run: |
    rm -rf /tmp/.buildx-cache
    mv /tmp/.buildx-cache-new /tmp/.buildx-cache

#### Steps to reproduce this issue

1. create linux/amd64 image
2. cache linux/amd64 image

#### Expected behaviour
1. It must create linux/arm64 image as I specified with platform property.

**Comment by crazy-max** [comment]
`linux/amd65` :thinking:

**Comment by arifizx** [comment]
> `linux/amd65` thinking

thanks, it corrected
