### ISSUE TITLE
Surface Google Artifact Registry Usage More Prominently

### ISSUE THREAD

**Issue by GLStephen** [docker/build-push-action#921]
As Google transitions to artifact registry it would be nice to surface more concise docs on how to use it more prominently in the project. This ticket was ultimately the one that solved it for me.

              @Hyperclaw79 It's possible to push to a regional GAR registry, just tag your images like this, e.g.: `us-west4-docker.pkg.dev/project-id/repository/image-name...`. It's buried somewhat [here in the documentation](https://cloud.google.com/artifact-registry/docs/transition/setup-repo#push-pull).

That's been working well for me using this action. HTH!

_Originally posted by @mikepilat in https://github.com/docker/build-push-action/issues/765#issuecomment-1397921930_

**Comment by crazy-max** [comment]
I don't think this is the right place and doesn't seem related to the action but how to tag for a specific registry which can be anything being able to push images such as this action or any other tool.
