### ISSUE TITLE
ERROR: failed to calculate checksum of ref 2be76fa3-2818-4c9b-915a-8fa715bd0b82::lhij89b8k6fneaah4jc4kjrg2: "/jenkins-agent": not found

### ISSUE THREAD

**Issue by moulikatusam** [docker/build-push-action#934]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [ ] There are no open or closed issues that are related to my problem

### Description

Behaviour

ERROR: failed to calculate checksum of ref 2be76fa3-2818-4c9b-915a-8fa715bd0b82::lhij89b8k6fneaah4jc4kjrg2: "/jenkins-agent": not found

I am getting the above error for the following code. I have tried different ways for the COPY line but none worked.         
![image (19)](https://github.com/docker/build-push-action/assets/136565076/5b6d52cd-2a2e-44ec-bcee-18886f09de71)
          USER root
          RUN ls -al
 >>> COPY ./jenkins-agent  /usr/local/bin/jenkins-agent
         RUN chmod +x /usr/local/bin/jenkins-agent &&\
          ln -s /usr/local/bin/jenkins-agent /usr/local/bin/jenkins-slave

### Expected behaviour

expecting this - COPY ./jenkins-agent  /usr/local/bin/jenkins-agent  to pass with no error as
failed to calculate checksum of ref 2be76fa3-2818-4c9b-915a-8fa715bd0b82::lhij89b8k6fneaah4jc4kjrg2: "/jenkins-agent": not found.

the jenkins-agent file and Dockerfile both are in same directory. Yet it is throwing the above error.

### Actual behaviour

10:54:53  #32 ERROR: failed to calculate checksum of ref 2be76fa3-2818-4c9b-915a-8fa715bd0b82::lhij89b8k6fneaah4jc4kjrg2: "/jenkins-agent": not found
10:54:53  #8 extracting sha256:de6a43bfad433fa7a8b0c1b364fe2bfb9cdd6b8315a9a71e5252e46c0d00d039 1.1s done
10:54:53  ------
10:54:53   > [24/28] COPY ./jenkins-agent /usr/local/bin/jenkins-agent:
10:54:53  ------
10:54:53  Dockerfile:100
10:54:53  --------------------
10:54:53    98 |     USER root
10:54:53    99 |     RUN ls -al
10:54:53   100 | >>> COPY ./jenkins-agent /usr/local/bin/jenkins-agent
10:54:53   101 |     RUN chmod +x /usr/local/bin/jenkins-agent &&\
10:54:53   102 |         ln -s /usr/local/bin/jenkins-agent /usr/local/bin/jenkins-slave
10:54:53  --------------------
10:54:53  ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 2be76fa3-2818-4c9b-915a-8fa715bd0b82::lhij89b8k6fneaah4jc4kjrg2: "/jenkins-agent": not found

**Comment by crazy-max** [comment]
Sorry but I'm not sure how this is related to this GitHub action?

Please provide a minimal repro (workflow, Dockerfile and logs). Closing in the meantime.

**Comment by jeankhawand** [comment]
Hello @crazy-max , that seems to be valid https://github.com/jeankhawand/wazuh-docker/actions/runs/5930142902/job/16079285528

**Comment by moulikatusam** [comment]
It is not related github actions. The script (Dockerfile) is used in Jenkins. The concern is the file "jenkins-agent" which the log says is not found is actually  present in the Build-context folder.
![image (20)](https://github.com/docker/build-push-action/assets/136565076/5c6807f1-5fcc-4adc-b600-285d95d4a5d9)

**Comment by moulikatusam** [comment]
the above shared image is the part of code in Dockerfile where the build is failing which is exactly at line 100. The file "jenkins-agent" is present in the same folder where the Dockerfile is present. Yet it is saying the file "jenkins-agent" is not found.

**Comment by jeferson-guedes** [comment]
I have the same problem !

**Comment by sangram0609** [comment]
Did you find any solution for this issue?
