### ISSUE TITLE
Build fails with "use of closed network connection"

### ISSUE THREAD

**Issue by max-sixty** [docker/build-push-action#939]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

Build fails to export to GitHub Actions Cache, with:

```
Error: buildx failed with: ERROR: failed to solve: error writing layer blob: Patch 
"https://acghubeus1.actions.githubusercontent.com/5N3JStGpyutUxUNE6d0DiRJnZQnrlB8wC9uh9kIr6Mh2GUFhf9/_apis/artifactcache/caches/11895": 
read tcp 172.17.0.2:42302->185.199.109.154:443: use of closed network connection
```

When I had manually deleted the caches, it had run successfully — though this no longer seems to make it work now (and I'm not sure whether it was causal or a coincidence prior)

### Expected behaviour

(as above)

### Actual behaviour

(as above)

### Repository URL

https://github.com/PRQL/prql

### Workflow run URL

https://github.com/PRQL/prql/blob/2ac9cb81433334c3bbbf70b27ee137013324f714/.github/workflows/build-devcontainer.yaml

### YAML workflow

```yaml
Linked above
```

### Workflow logs

https://github.com/PRQL/prql/actions/runs/5943427532/job/16118539440#step:6:263

### Additional info

The cache entries are extremely small — 100-400 bytes...

<img width="973" alt="image" src="https://github.com/docker/build-push-action/assets/5635139/56d133ca-4340-4b41-8b97-9e4b9d65f4ae">

link: https://github.com/PRQL/prql/actions/caches (but may not exist for long)

---

https://github.com/docker/build-push-action/issues/677 has the same error message but otherwise looks unrelated

**Comment by crazy-max** [comment]
This is a transient network error with GitHub infrastructure. Suggest to contact them. Also check https://www.githubstatus.com/.
