### ISSUE TITLE
Support ability to skip pushing

### ISSUE THREAD

**Issue by reynoldsm88** [docker/build-push-action#94]
For some projects I don't want to push images for branch builds, but would still like to verify that the Docker build is working.

**Comment by mat007** [comment]
Is this not: https://github.com/docker/build-push-action#push ?

**Comment by crazy-max** [comment]
Version 2 has been [merged to the main branch](https://github.com/docker/build-push-action#readme) and is therefore available via `uses: docker/build-push-action@v2` (mutable tag).

As a reminder, this new version changes drastically and works with 3 new actions ([login](https://github.com/docker/login-action#readme), [setup-buildx](https://github.com/docker/setup-buildx-action#readme) and [setup-qemu](https://github.com/docker/setup-qemu-action#readme)) that we have created. Many [usage examples](https://github.com/docker/build-push-action#usage) have been added to handle most use cases.

And it should fix this current issue. Don't hesitate if you have any questions.
