### ISSUE TITLE
Add option for host address for S3 cache

### ISSUE THREAD

**Issue by TheRealRolandDeschain** [docker/build-push-action#944]
### Description

Hi, I wanted to test around with the (currently still experimental?) S3 cache for image building. 
Our company hosts a internal Minio S3 storage as well as a Github enterprise server on-premise and we currently have the problem that too many heavy image-dependencies are too often re-downloaded for use in our kubernetes cluster. 

I think a central cache on a S3 bucket might help with this, however I currently do not find any option to point to a privately hosted S3 storage. Adding this option would be quite helpful I think.

**Comment by crazy-max** [comment]
@TheRealRolandDeschain You can use the following attributes in `cache-from`, `cache-to` inputs: https://docs.docker.com/build/cache/backends/s3/#synopsis

**Comment by crazy-max** [comment]
Actually we have the `endpoint_url` attribute: https://github.com/moby/buildkit#s3-cache-experimental

@dvdksn I think we should update our docs in https://docs.docker.com/build/cache/backends/s3/#synopsis to add the missing attributes?

**Comment by TheRealRolandDeschain** [comment]
Hi, thank you - I will test this :)
