### ISSUE TITLE
Support quiet option

### ISSUE THREAD

**Issue by mikkelti** [docker/build-push-action#953]
### Description

When I build my Docker image in GitHub Actions, it seems like the build output logging itself takes up quite a lot of time. Would it be possible to add the `--quiet` option? Otherwise, is there something else I can do to minimize the output?

**Comment by crazy-max** [comment]
> it seems like the build output logging itself takes up quite a lot of time

I don't think it would make any difference. Do you have a repro to confirm this?

**Comment by mikkelti** [comment]
No, I don't have a minimal working example to repro. You may be right, it would just be very easy for me to test with the `--quiet` option.
