### ISSUE TITLE
Support `annotations` option

### ISSUE THREAD

**Issue by favonia** [docker/build-push-action#958]
### Description

(I am creating a new issue because the focus of the old issue #854 is unclear.)

I wish `build-push-action` can support `annotations` just like `labels`, once the new `--annotation` shortcut (https://github.com/docker/buildx/pull/2020) is officially available. Essentially, the script should append a new parameter `--annotation "line"` for each line in the value of `annotations`, just like how it appends a new `--label "line"` now for each line in the value of `labels`.

**Comment by crazy-max** [comment]
`--annotation` flag PR has just been merged on buildx repo https://github.com/docker/buildx/pull/2020 and will be available on next 0.12 release. We could then add a new input for this action as follow-up. (cc @jedevc)

**Comment by jedevc** [comment]
@crazy-max sgtm :tada: I think the release of v0.12 should be scheduled for fairly soon?
